### ISSUE TITLE
[design] Website Graphic Requests

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-marketing#10]
Requesting new/updated graphics for the following sites/pages:

- [Security Centre](https://developer.joomla.org/security-centre.html) - A graphic we can use for content in this category in place of the generalized social media graphic
- [Developer Network](https://developer.joomla.org/)/[API](https://api.joomla.org/) - Updated CMS/Framework/Tracker graphics

**Comment by mikeveeckmans** [comment]
Thank you @mbabker for your request.
We'll have a go at this after the 3.6 launch

**Comment by Sandra97** [comment]
@designbengel @mikeveeckmans, did you work on this graphic request? 
Thanks!

**Comment by designbengel** [comment]
Sorry guys, just realized that the github inbox is overfloating, will have a better eye on this in future. pic will be there as soon as possible.

**Comment by mikeveeckmans** [comment]
@mbabker , sorry it took a while before picking up. 
the imagery you want for security center : is it a blog post image? Any specific text on it? 
like "security announcement" or something ? 

For DN/API : same size ?

**Comment by mbabker** [comment]
Security Center - Blog post image works.  Basically instead of getting our generic Twitter card image when folks share links to that section of the site, a more contextually appropriate image is what I'd prefer.

DN/API - Same size would be easiest to just drop in without any other changes.

**Comment by mikeveeckmans** [comment]
![securitycenter](https://cloud.githubusercontent.com/assets/4589318/18377535/1a4b21ee-7668-11e6-98dd-42f2da3c5850.png)
What do you think of this one for SC?

**Comment by Sandra97** [comment]
My 2 cents; Centre instead of Center ;)
Thank you!
(I'm happy to see consistency in all our graphics)

**Comment by mikeveeckmans** [comment]
OK will change

**Comment by mikeveeckmans** [comment]
![securitycentre](https://cloud.githubusercontent.com/assets/4589318/18383976/62132876-7688-11e6-8c45-f3ab39c99076.png)

**Comment by Sandra97** [comment]
One question (sorry should have asked it before, but I'm not yet awake): is the display ok if we keep Joomla! Security Centre on the same line?

**Comment by mikeveeckmans** [comment]
No that's why it's on 2 lines ...

**Comment by mikeveeckmans** [comment]
![joomlacms](https://cloud.githubusercontent.com/assets/4589318/18384210/a05947cc-7689-11e6-99cc-3d3024748a94.png)
First on for DN page.

About framework : still use the blueprint logo or revert to official logo ? 
Same for issue tracker, i checked the site and the current logo version on DN is not used, my suggestion is to use official instead of yellow one (as currently on DN page).

**Comment by mbabker** [comment]
IIRC the blueprint logo was designed specifically for the Framework versus just using the official logo.

As for issue tracker, I honestly don't care.  I forget who had the idea to just make it all one color but that's what it's been and that's what all of our GitHub bot accounts use for avatars now (not a strong argument to keep it though).

**Comment by mikeveeckmans** [comment]
![joomlacms](https://cloud.githubusercontent.com/assets/4589318/18398232/1be93126-76cc-11e6-88aa-d065f142019b.png)
![joomlaframework](https://cloud.githubusercontent.com/assets/4589318/18398234/1bed8e9c-76cc-11e6-9f19-c35f6fe7e3d8.png)
![joomlaissuetracker](https://cloud.githubusercontent.com/assets/4589318/18398233/1beb83c2-76cc-11e6-866d-ec04e680bfd1.png)
@mbabker here you go ;-)

**Comment by mbabker** [comment]
Thanks!
