### ISSUE TITLE
Images for an article 

### ISSUE THREAD

**Issue by webdjam** [joomla/joomla-marketing#105]
Hello @Sandra97 
I'm publishing an article on the Joomla! Community website, the article is a call for translators, to translate our JUG Rules and Faqs on docs.joomla.org, to illustrate the article I need an Image that fit the content of the article.
Thank you,
Djamel

**Comment by Sandra97** [comment]
Here it is:
![1](https://user-images.githubusercontent.com/4682328/27507812-69dd7cd2-58a5-11e7-8427-a6dd7d329c39.jpg)

Tell me if it's ok for you.

**Comment by webdjam** [comment]
Awesome @Sandra97  thank you very much!

**Comment by Sandra97** [comment]
Article published.
I'm closing this issue.
