### ISSUE TITLE
[URGENT] Blogpost for CMS Critic 2017

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#106]
The 2017 CMS Critic Web Awards are open for nominations (from June 26, 2017 until August 27, 2017).

We need a blogpost to publish on cjo as soon as possible. 
I'll take care of the picture. 
I've forwarded you the email from CMS Critic so you have all information.

Give a look of what has been done last year for the blogpost: 
https://community.joomla.org/blogs/community/3061-the-cms-critic-awards-are-the-best-thing-since-the-internet.html

**Comment by Sandra97** [comment]
Tell me what you think

![cms-critic-2017](https://user-images.githubusercontent.com/4682328/27558616-24a7c762-5a94-11e7-8952-09ecdd3b5ff4.jpg)

**Comment by parthlawate** [comment]
On it !

**Comment by parthlawate** [comment]
Done https://docs.google.com/document/d/1xJGCl2JT0erT3QpS5CEhnk9IwrtMdKvcJSaE1Ax2JVk/edit#
Please review and add comments. When ready i can publish

**Comment by Sandra97** [comment]
Review and comments done.
Ok for me.
Can we publish it today?

**Comment by parthlawate** [comment]
Replied.. Should be good to Publish today.. @Sandra97 will you be able to publish ? Stepping out of office for a couple of hours now.> Have done the changes you requested

**Comment by Sandra97** [comment]
@parthlawate Yes I can publish it. In a few hours so that most of the world is awake

**Comment by mikeveeckmans** [comment]
added 2 comments

**Comment by Sandra97** [comment]
Accepted!

**Comment by Sandra97** [comment]
I will publish it in approx. 3 hours

**Comment by Sandra97** [comment]
Ready in the cjo backend!

**Comment by Sandra97** [comment]
Published.
https://community.joomla.org/blogs/community/3120-the-cms-critic-awards-nominate-joomla-today.html
Closing this issue.
