### ISSUE TITLE
[Printed Magazine] Organize a Team

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#108]
At the JoomlaDay UK in London wo talked with Simon Grange. He showed us his Cinnk Magazine. He is willing to do something like that for the Joomla Project. I add him here, after i get his github account and we can start with the plannings.

**Comment by MATsxm** [comment]
Maybe you should ask for help from @sanderpotjer (AFAIR he managed the NL Mag that was a real success) and also Simon Grange (http://cinnk.com/magazine) who is doing a tremendous job with his Mag

**Comment by Joomv** [comment]
It was conversations with both of them that started this thread.  Simon in particular.

**Comment by Sandra97** [comment]
Closing this issue for the same reasons mentioned in #127
