### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by netamity** [joomla/joomla-marketing#109]
I am interested in producing a podcast about Joomla, and I'm seeking people's input on that they'd like to listen-to, and how they might be able to help.
There have been previous and current podcasts related to Joomla:
http://joomla.org.au/forum/general-discussions/7018-new-joomla-podcast-the-tim-plummer-joomla-show
and
http://joomlabe.at/

I have things in mind that I'd like to have included in the podcast, and how it might differ from the above offerings, which I'll list, and i would love for others to contribute their thoughts:

What I'd like less of:
-Extension reviews / extension guides

What I'd like more of:
-News: events, new core releases and announcements (speaking to the team member leading the topic)
-In-depth interviews with the people behind Joomla: who they are, how they came to Joomla, their role, where they see Joomla heading.
-Hot topics: in-depth analysis of an issue or debate within Joomla (Is Joomla dying? Where does Joomla fit in the CMS marketplace? How can open source be profitable? etc, etc ). For these I'd like to invite community leaders and topic experts to speak
-Technical deep dive into a part of the system: the router, juri, MVC overriding, etc. (This has been suggested to me, and I'm interested in such a thing, but I'm wondering about how effective it would be for an audio-only medium?)
-Event reports: A run down of conferences, speakers, with vox pop interviews with people at the event (It'll give me an excellent excuse to get to them)
-Listener requests, shout-outs, questions

The goal of the podcast:
-To bring greater transparency to how the Joomla project works, the different parts, people of interest. As we know, people (including myself) have previously accused Joomla's management as being opaque and unresponsive to complaints or organisational issues raised. I hope the 'direct-line' to those co-ordinating things will help everyone to understand the challenges they face, and what things are being done to improve.
-To encourage people to get involved and help bring Joomla on, and to inform people about how to air issues constructively. 
-To build a sense of community where people don't have access to a JUG or can attend events
-To easily keep people up-to-date with important topics and news

The target audience for this podcast would be people already using Joomla, and with some investment in it. It wouldn't be an idiot's guide or a Joomla 101 type thing for beginners. I want to make it intentionally erudite. I do want it have fun with this though. I don't want it to be impossibly serious.

About me:
I have no experience of podcasting, and I'm not sure I have the best broadcast voice, but I'm willing to give it a shot, and would like to produce something of high production quality. I'd need help, and would even be happy for someone else to host the podcast if their skillset is better suited to it than mine. 

What I need now:
-Ideas and opinions for the podcast: segments, format preferences, etc
-Expressions of interest: Whether you want to host the show, edit the news.
-Introductions to the VIPs in the Joomla community, and an indication from them that they'd be willing to feature on the show
-Generally any guidance on how to do a podcast from anyone who has created one before and can offer general advice, dos/don'ts

Later I'll need (so get in touch now):
-Audio editing. I guess i could do it, but if we have some pro who can do it better,...
-Music and effects: Podcast jingle, segment intros, background music
-Artwork: Logos, page banners for wherever the podcast is available
-Marketers: Help to market and distribute the show to itunes, Stitcher, moderate comments

OK, over to you all....

**Comment by netamity** [comment]
Is there a place i can share this with the whole Joomla volunteer community, not just the marketing bods? I really want to get everyone's input, regardless of how they are involved

**Comment by Joomv** [comment]
This is a public facing repo.  Anyone can view these posts.
We have a private repo too for more sensitive discussions, but this repo is fully public facing.

**Comment by parthlawate** [comment]
We had an idea in the past which we started and did 2-3 editions was as a Google Hangouts on air..  It was a lot of fun and we got anywhere between 100-150 people passing through.. and many more views later on youtube.. I'd love to be part of something like that again ! You can see some of them here https://www.youtube.com/watch?v=ScrYMaZTxWY & here https://www.youtube.com/channel/UCrY5f72iOIh7vzuc6OrekGQ

**Comment by netamity** [comment]
Great idea, that google hangout thing, and obviously great scope for live involvement if it had a regular live audience. I'll watch in full. 
I am more interested in a making a produced/edited, audio-only podcast. I listen to podcasts constantly, and often while doing working or commuting, so something eyeball independent works better for me. I also fancy the idea of watching myself on camera even less than the idea of listening to my voice.
There's definitely room for both though, and for us to partner and support each other with cross-promotion!

**Comment by netamity** [comment]
The visual medium I think is MUCH better for the 'technical deep dive / analysis' segment I proposed. I was always skeptical if that could work on an audio-only format, but it's something I'd watch if it were available.

**Comment by JoeJoomla** [comment]
Would there be any value in getting in touch with others who have done this sort of thing in the past? There use to be a great Internet radio show called Joomstew that was run by Robert Vining and Peter Bui did a podcast for a long time too. Each of them ran out of steam trying to keep it going on their own which was unfortunate.

Do you want to get in touch with either of these Joomlers to gather information based on their experiences?

btw - Sarah Watz is doing a Facebook Live series which you can see on https://pixpro.net/labs/live-show <https://pixpro.net/labs/live-show>

**Comment by netamity** [comment]
I've tried to make contact with Peter Bui and Tim Plummer, but been unable to get a response. If you know these individuals personally, would you mind getting in touch to see what news and insights they can offer?
Peter Vining, I don't have his contact or links to the show- can you provide?
I'll check out Sarah Walz' facebook series and get in touch with her.
Many thanks for all this!

**Comment by netamity** [comment]
With regard to the previous podcast type things, it'd be interesting to hear why they ran out of steam from the people who made them, and from their listeners. 
My other concern is that I'm scratching my own itch here, because I'd love such a podcast, but it'd be nice to know that enough others would listen to such a thing to make it worthwhile.
How can I unobtrusively get a show of hands from the millions of Joomla users? ;)

**Comment by JoeJoomla** [comment]
I’ve reached out to Peter the only way I can, via Glip. If I don’t hear back from him I’ll try him through his website.

I’ll ping you on the side with Robert’s contact information shortly.

**Comment by parthlawate** [comment]
If we can it would be good to do as a 'Joomla' thing with a way to pass the baton to ensure continuity.. Robert and Pete did an awesome job with the Podcasts.. If we can institutionalise it , it would be fantastic..

**Comment by netamity** [comment]
Absolutely, I want to learn from the lessons and carry on the good work or previous podcasts. By 'institutionalising' the podcast, do you mean have it under the direction of the Joomla team, rather than a joomla user's side project, as previously? I see that having it's merit, as you say, so that it can be carried on and be an 'official' podcast. I like the idea, as long as the people producing it have editorial control, perhaps following some kind of 'charter'?

**Comment by netamity** [comment]
By the above, I want the podcast to be a mouthpiece for the community as much as the Joomla team

**Comment by JoeJoomla** [comment]
If the Joomla project takes this on officially it should only be done with very careful consideration. It's going to need a lot of support to keep it going long term. Being realistic in expectations with regards to how many official episodes are done would be prudent. Less, done well, is better than a lot done poorly. Making promises such as a monthly broadcast and breaking that promise will only cause frustration.

This could be a great thing. Imagine doing official broadcasts from major events like Joomstew once did. Those were a lot of fun and many good Joomlers were featured in those broadcasts which helps new Joomlers discover the who's who of the Joomlasphere.

If it's an official Joomla thing I'd like to see a decent sized team behind it.

**Comment by netamity** [comment]
Agreed, and I don't wish to underestimate the amount of effort required for such a thing. I agree that quality is much more important than quantity. I'd love for the Joomla project to buy into this! I think the podcasts from events would be great too!

**Comment by Joomv** [comment]
I've pinged Pete on Facebook and linked to this.
Done right this is not a huge amount of work and doesn't need a massive team.
It needs some planning and scheduling and community member co-operation, but not some massive team.

**Comment by pbwebdev** [comment]
Hello!

> I’ve reached out to Peter the only way I can, via Glip. If I don’t hear back from him I’ll try him through his website
@JoeJoomla I don't use glip, really dislike the platform. Slack is much better for me and our teams. I wish the Joomla Project paid for a Slack account :(

> I've pinged Pete on Facebook and linked to this.
@Joomv Yes I'm always on the bookface.

> I've tried to make contact with Peter Bui and Tim Plummer, but been unable to get a response. If you know these individuals personally, would you mind getting in touch to see what news and insights they can offer?
@netamity Hey Andy, I don't recall seeing any messages from you via the website or social media. I'm usually very responsive to any emails and requests that come through.

The main reason why I stopped recording the podcasts is that I've been travelling almost non stop for well over a year now. You can see all of my snaps and food pics from around the world on [Instagram](https://www.instagram.com/astroboysoup/) 

Highlights include:

- [Working with our team in Manila](https://www.instagram.com/p/BTnacBZgp8c/?taken-by=astroboysoup)
- [Sunrise over Angkor Wat](https://www.instagram.com/p/BSnMvKlAHwQ/?taken-by=astroboysoup)
- [Eating a cheeseburger from a Thai equivalent of a food truck](https://www.instagram.com/p/BJ7JgESACeA/?taken-by=astroboysoup)
- [Working from co-working spaces in the jungles in Pai, Thailand](https://www.instagram.com/p/BJM6IeGAgny/?taken-by=astroboysoup)
- [Cat cafes](https://www.instagram.com/p/BI4hmqRA-zP/?taken-by=astroboysoup)
- [Getting to understand by heritage and background in Vietnam](https://www.instagram.com/p/BH37K3WAtxs/?taken-by=astroboysoup), e.g food
- ['working' out of the Red Web offices in Vietnam](https://www.instagram.com/p/BHJQ4EOgiE7/?taken-by=astroboysoup)
- [I'll let people caption this one](https://www.instagram.com/p/BGh_1T6Dz-Q/?taken-by=astroboysoup)
- [Swimming with whale sharks](https://www.instagram.com/p/BGJRTgljz40/?taken-by=astroboysoup)
- [cliff jumping](https://www.instagram.com/p/BFxuphbDzwg/?taken-by=astroboysoup)
- [coconuts](https://www.instagram.com/p/BFGXMBzDzy6/?taken-by=astroboysoup)

It's been quite a journey and I'd love to share it with you all.

There are two other reasons why I had to pause the podcast for a bit.

1) I had to make more money. I've been concentrating on the business and have increased the turn over by 4 fold. I'm happy with that now and the machine is well oiled to keep going itself now.
2) The podcast didn't grow any more. At about the 2 year mark, it plateaued at 4000 uniques listens a week. With increased marketing spend and further engagement on social, email and the lot, I couldn't break the 5000 listener level for well over a year.

Here are some stats for you all
![screen shot 2017-07-20 at 9 07 52 am](https://user-images.githubusercontent.com/3688954/28393602-f7bc03fe-6d2a-11e7-85b1-2a086069e5ba.jpg)

More than happy to start it up our podcast again soon and help with an official Joomla Podcast.

**Comment by JoeJoomla** [comment]
Peter,

Thank you for the great information and insight. 

An official Joomla podcast could have the support of our advertising and promotional efforts to the Joomla community. Surely this could be helpful in breaking through 4,000 views a week. Regardless, it would be a good indicator of how we are doing with regards to reaching the community and the projects popularity within it.

Joe

**Comment by netamity** [comment]
Yes, thank you Peter,

Great info!

I believe I tried to contact you through your site about a month, but whatever the case, I’m pleased to make contact with you now, and thrilled to get that data.

As with all aspects of the podcast, the format is up in the air, but I’d be interested to get your take on these:

- Extension reviews and guides: I know these were a regular segment on your podcast. Ufuk who is leading the marketing team has expressed concern that including such a segment in an official podcast would lead to bias, so it may not be considered for our podcast. Did you get much audience response from this segment? Would we be making a huge mistake avoiding the ‘extension options’ topic completely?
-Did you find the process very time consuming? We're just trying to get an idea of what size an undertaking this is and how big a team we need.  Every case is different, but I'd be interested to hear your experiences: how long it took you to produce an episode, what items took the longest, etc.

Joe, I agree the marketing team getting behind an official podcast could break listener limits, and it might have a snowball effect, because i think the podcast itself will be an amazing marketing, promotional tool for all areas of the Joomla project.

All great stuff!

**Comment by ufuk-avcu** [comment]
Great discussion here! @netamity after contacting @pbwebdev, contact me aslo please. Then we can do a small skype or hangout conference and define the next steps and what you can do, what do you need and so on...

**Comment by netamity** [comment]
Tim Plummer responded to an email i sent, and I'm sure he wouldn't mind me sharing it here:
Hi Andy,
Thanks for getting in touch, and that’s great that you are thinking of starting a Joomla podcast, I highly encourage you to do it.
I never took my podcast seriously. I mainly started it so that I could learn about how podcasting works, plus Peter had given up on JoomlaBeat and I thought that Joomla should have an active podcast somewhere. As you can see, I didn’t do it regularly enough, and while several people have mentioned to me that they listened to my podcast, I doubt that I had a very big audience. I’ve kind of let it die off (and no one has really noticed), but I might do the odd episode here and there if I get round to it.
If you do start a podcast, then my first tip would be to try to do it regularly.
Happy to chat further if you want to know more.
Good luck.
Regards 
Tim Plummer

**Comment by RobertVining** [comment]
Sorry for the delayed response here... but this is why I stopped doing Joomstew. Work and life have to come first, and I was spending 10 to 20 hours a week doing each episode. I had help at times, but we went on for well over a year. It just became too much to do each week, and I burnt out.

Here's the first 11 episodes in full:
http://www.blogtalkradio.com/joomstew

And as for the full catalog of episodes, I hope to put it up again 1 day soon. It was a wordpress site and got hacked... go figure. But I have a wife and 2 kids to feed on a 1 income family. So it's tough for me to dedicate my time to a volunteer project as I did in the past.

@netamity I am happy to discuss this via skype as you suggested, I just wanted to throw my hat in the ring in the public discussion.

As far as my 2 cents, I think having a project run podcast would be difficult to keep going. There would have to be a lot of passing of the baton. People burn out. Also, politically, it would be a pain in the butt. Think about the last time you were displeased with a project decision, or something similar.. would you really want to put on the happy face and go be a project representative for the show that day?

It would be awesome to get Andy to spearhead it since he has the drive right now, and get Sarah, Peter, myself, Parth, Joe, and anyone else that has a notion to support you with help. But do it as an independent, like I did with Joomstew. We had Dianne and Alice as co-hosts with me, both sitting on the OSM board at the time. They hosted all the remote shows from events as well, without me.

But I owned the domain and the show outright. If we wanted to talk about something on the show, we didn't have to worry about anyone telling us we can't say that. But having Alice and Dianne involved kept us from stepping over the line, as far as the project was concerned.

But bottom line for me, it takes a minimum 10 hours to produce a 1 hour show with 1 to 3 guests, track down the week's news, write the questions, record the show, edit out any bad words, find an image, write a 3 to 5 paragraph outline for the episode as a blog post and publish.

10 hours minimum... every week. And I can't volunteer that much time today... I'm 48. Life is short. My kids are 8 and 9 and cooler than you guys. I would rather give them 10h a week of my time.

But I'm open to giving 1 or 2 h a week. If anyone wants to take this ball and run.

Good to see some familiar faces in this discussion. Hope all is well!

**Comment by RobertVining** [comment]
Just looked at the stats from the first 11 episodes on blog talk radio. They average about 400 listens ALL TIME for each one. So Pete had 10 times more market share than we did when we ran 5 to 7 years ago.

**Comment by netamity** [comment]
Thank you Robert,
I can see what you're saying about having independence from the Joomla Project. While the success of the podcast would rely on participation and co-operation from the the leadership, I want to be able to ask challenging questions and ensure that the people producing the podcast have editorial control.
I'm going to draft a few documents and ask for people's input:
-A charter style document stating the aims of the podcast, its editorial guidelines and proposed means of oversight/scrutiny
-A proposed outline of the format of the show and segments
-A list of job roles and other support required (as best as I can predict now)

I'll then link to them here and ask for your input, help, etc. I'll also speak to ufuk about how the marketing team and the podcast can support each other.

**Comment by netamity** [comment]
Here we go. Some very early scribblings, and I'd love people's input on all aspects of all documents for which they have ideas and suggestions. These really are designed as a conversation-starter only. I've been quite ambitious. I'd very much like to produce something of high quality, but I'm conscious of the undertaking that is and the support I'll need.
[Joomla Podcast Requirements.docx](https://github.com/joomla/joomla-marketing/files/1188565/Joomla.Podcast.Requirements.docx)
[Joomla Podcast Charter.docx](https://github.com/joomla/joomla-marketing/files/1188567/Joomla.Podcast.Charter.docx)
[Joomla Podcast Format.docx](https://github.com/joomla/joomla-marketing/files/1188566/Joomla.Podcast.Format.docx)
If you have any comments or offers you'd prefer to pass on privately, then you can email andy@netamity.com , otherwise I think an open discussion here would be great

**Comment by pbwebdev** [comment]
Hey Andy
Can you make those docs google docs for contributions or md file on a git repo ?

I'd also recommend high quality audio equipment. 

Anything sub par will result in average quality in audio and put off a percentage of listeners. This would be for all hosts especially if they're in different locations. Ideally record audio. At all presenter locations and sync the audio. 

I've had a lot of comments on audio quality and questioning if I knew what I was doing all the way to the end.

**Comment by pbwebdev** [comment]
@netamity 

> 
Extension reviews and guides: I know these were a regular segment on your podcast. Ufuk who is leading the marketing team has expressed concern that including such a segment in an official podcast would lead to bias, so it may not be considered for our podcast. Did you get much audience response from this segment? Would we be making a huge mistake avoiding the ‘extension options’ topic completely?


you will have problems with people complaining about their plugin not being promoted. If you're getting the reach you should be with the podcast you can make or break an extension with a good or bad review. I'd tread carefully there. Avoiding it might be easier.

> -Did you find the process very time consuming? We're just trying to get an idea of what size an undertaking this is and how big a team we need. Every case is different, but I'd be interested to hear your experiences: how long it took you to produce an episode, what items took the longest, etc.

The process of making the podcast for me was 9 hours. Pretty exact.

- Research
- Show notes
- pre-marketing
- Interview
- preparing the co-host
- recording
- audio post production
- Uploading and blog post
- post marketing
- follow up with interviewee

I never really documented the process but that is essentially what I followed

**Comment by netamity** [comment]
Thanks Peter, that's really good stuff.  3am here in London, so I'll let it sink in, but you've left a couple of comments and I wanted to let you know I was listening and appreciate your input

**Comment by netamity** [comment]
The time and process are important- I'd like to be ambitious with what can be done so long as not biting off more than I can chew.

**Comment by uglyeoin** [comment]
Hi @netamity it was nice to meet you at JDUK 2017 and I'm very much looking forward to your output.  This is a fantastic idea.  Why not post a link to here in the forum?  I've spread it around a few channels and I'll do a post on Joomla! London too in the hope that it gets you some traction.  I'm afraid I know nothing of podcasts but I'll gladly listen.  

Also like Parth's idea of a Google Hangout.  Would be great to do some walk through tutorials.

**Comment by uglyeoin** [comment]
Recommend getting Brian Teeman's input if he has a spare 5 minutes for you.  He makes a great headline at JDUK so he might be able to give you some advice.  I think he did a video on how to present well too.  Or maybe it was this blog post.  https://brian.teeman.net/joomla/the-art-of-presentation

**Comment by uglyeoin** [comment]
Since a few people out there who have done it and burned out.  And the 9 hours that Peter Bui said is a burden on anyone.  His one was really good quality so I suggest you aim for similar.

The thing is, if it was 9 hours every 3 months it would be much more manageable right?  So consider having 3 teams rotating.  And consider having a place people can send you ideas for the podcast which would reduce some of the work perhaps?

**Comment by parthlawate** [comment]
@netamity If you leave out extensions you will loose out on showcasing the real power of Joomla .. However @ufuk-avcu 's concern is very real..  So it might make sense to make this a 'non Official' thing which is loosely supported by the project. A lot of people have commented on making it a non official thing has a lot of advantages.

I have always in the past supported making it official.. but i see now that it could create more issues than help..

**Comment by uglyeoin** [comment]
@parthlawate but @netamity specifically doesn't want to review extensions from a personal point of view.  I think I understand what he's doing and from a marketing perspective having a way for the teams to communicate with the wider community would be a really good idea.  It helps people to get involved, to understand why things do or don't happen, and is the start of us pushing marketing messages.  So for example in any large organisation there is direction from the top, and the podcast could be one way of implementing that to people who are not volunteers but are still users/evangelists.

**Comment by netamity** [comment]
Well, my preference is to have the podcast non-official (but obviously working in co-operation and contact with the project) and not to have extension reviews.
It's true that extensions are a massive part of using Joomla, but my objections are:
-Personally, it just doesn't interest me. It was the only part of Pete's podcast that I used to fast forward.
-Staying impartial would be a minefield- with such a range of extensions in each category, there's no way to appear even-handed, even if there was no intention bias or vested interest
-Because of the range of use cases for Joomla, you'd either cover the big categories (backup, security) which people usually already know about, or cover niche extensions that will be a huge hit for a few but irrelevant to most.
-I just don't think it's an audio-only type thing. To give any kind of explanation of an extension requires seeing it.

@uglyeoin I'm not sure if you're saying it should be an official thing, or it shouldn't
I think this is something that needs deciding before moving forward. I'd be happy to be involved in an official podcast, but I'd prefer to have it independent of the project for reasons discussed.

But other than that important decision, I think I've just got to get started and let it evolve. If I came up with a few 'roles', what's the best way to recruit people. Just post them here? I created some documents related to a charter and segments and roles.

Here are the google docs as Pet suggested:
Requirements: https://docs.google.com/document/d/1rbrA7C6ioROyA20OnTpMhpon66_qQ765IxF9hSEGqq8/edit?usp=sharing

Charter: https://docs.google.com/document/d/1Y_8nm-WaqwEfTu48xZ63AEHW6aoLoIGICuFz9KXMC9M/edit?usp=sharing

Format: https://docs.google.com/document/d/1RIfaxJtgQ8R9jOM1k9XSB62qn7gv_-zhJAmgj-RA42Q/edit?usp=sharing

**Comment by parthlawate** [comment]
@uglyeoin Yes I Absolutely respect that view :) .. But just my 2 cents.. If its a way to better manage communication in the community and spread word within community it works well.. It also works well for some section of the 'Market'

What I would suggest is the same thing I suggested to JED and what we are doing for the use cases campaign is promoting extension categories rather than a specific extension

**Comment by brianpeat** [comment]
I'd be interested in helping with this (and listening to it). I haven't done any podcasts specifically, though I've created a few from pre-recorded files, and I've got a decent technical background (and I'd love to be interviewed as the AV lead for JWC among other things) :)

**Comment by Sandra97** [comment]
Any update about this project?

**Comment by Sandra97** [comment]
I'm closing this issue for lack of interest.
It still can be re-opened if some volunteers would be ok to make it happen.
