### ISSUE TITLE
Representing Joomla at the FISL 2016 event in Brazil

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-marketing#11]
Event : FISL (Forum International Software Livre)
Event site : http://softwarelivre.org/fisl17
Event place: Porto Alegre
Event Date: 13 - 16 July
Flight Cost : 400 USD ( Depends if I book late then might be plus a little)
Expected people turnaround: 2000+ https://www.flickr.com/photos/fisldezesseis/19582546965/ ( It was over 5000 in last years as well )
My Matrices would be : To get more people using Joomla and get more people to involve in the community and in Brazilian community as well.

There is an event coming up which is next month and sorry that I missed to ask earlier about it. As I am already in Brazil so I would love to spread more words about Joomla and do more outreach to all open source platform out there. There will be a space to have a Joomla community booth out there and also few Joomlers from Brazil to support. I am not sure if there is a time to get the Joomla booth within the time but definitely can do some marketing material printed.

There will be people from all different area of Open Source including wordpress and Drupal. It will be great if I can reach out there and represent the community. I have covered my stay if I will be able to go there.

I have been contacted by organizers as they are looking for speakers and someone from other communities as well. They have told me to be a part of it and probably they will have a slot for me to speak at the event if I tell them early. I have asked them to cover my travel and stay cost but they can not cover flight ticket due to Brazil crisis. I have got stay covered during the event though as mentioned before. So I just need travel cost covered now. It will be less than 500 USD.

Ryan Ozimek knows this event and he represented twice earlier as well. "  I've presented there twice. It's a massive event, and one of the few that had a lot of people attending for a Joomla session in the past.

Let me know if required anything else from me.

**Comment by mikeveeckmans** [comment]
Hi @Saurabh1 ,

At this point i have no confirmation on budget yet from OSM, so i can't confirm, i'm sorry.
As soon as i do, i will let you know.

**Comment by Saurabh1** [comment]
Thanks for the reply @mikeveeckmans 
I thought for now I needed approval from Marketing team so I can move ahead and not miss the opportunity to represent Joomla in front of huge audiance. I can wait till the reimbursement part later. 
So even if this is going to be reimburse later, still you need budget approval from OSM now ?

**Comment by Saurabh1** [comment]
Please consider this event for next year if we wish to do more outreach. 
Closing the issue as event will be starting on 13th July(Today)
