### ISSUE TITLE
[LandingPage] 3.8 Features for the LandingPage

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-marketing#110]
New Features/Functionality and general changes/improvements:
- Joomla 4 compatibility layer
    - The core PHP classes are shifting to using PHP namespaces, in 3.8 we have moved the majority of the core library classes to use the new class names and created class name aliases for the old names.
- New Routing (for real this time)
    - The new routing system comes with new options for users and developers to give them more control over their URL structures and addresses some long standing quirks with Joomla's routing, one of the new options being the highly requested "remove IDs" option.  Because the URLs generated with the new routing system are not 100% compatible with the existing router and its URLs, it is suggested that existing sites do not enable the new system without thoroughly testing their sites in a staging environment and addressing any URL changes.  New sites are encouraged to make use of the new system immediately.
- Enhanced Encryption Support
    - The core encryption library supports the new `sodium` extension which will be added to PHP 7.2 and through a polyfill this library will be available to all users of Joomla on all of our supported platforms.
- Admin language specific menus and modules
    - The administrator interface can now be customized with menu items and modules for each language, similar to the frontend
- Event hook for frontend `mod_stats`
    - The module can now be expanded with custom statistics from any source
- Add a CSS class to menu item images
    - Provides more styling options to images set to menu items
- General code review
    - A large majority of the codebase has been reviewed with updates for improved readability and more efficient processing

Full list of changes: https://github.com/joomla/joomla-cms/milestone/19?closed=1

**Comment by Sandra97** [comment]
Thank you!

**Comment by Sandra97** [comment]
@parthlawate If you would like to do a live video, the best person would be the 3.8 Release Lead.

**Comment by parthlawate** [comment]
By live video you man like a Liv video event that I mentioned on the other thread ?

**Comment by mikeveeckmans** [comment]
any document open for this yet ?

**Comment by parthlawate** [comment]
Hi not yet..  Any suggestions for timezone that @mbabker would be wake in and most of the rest of the world will be too ?

**Comment by mbabker** [comment]
1) I'm in the Minneapolis, MN, USA area (UTC-6 normally, UTC-5 during DST)
2) My availability during my 9-5 job is generally limited, so most of my time these days is either very early in the morning for me, late evening (when Europe and Asia are usually offline), or weekends
3) Please remember that I'm just the cat herding button pusher here, there are loads of people who have done much more than me for this release and would be better individuals to talk to and work with (plus, it lets those people get the spotlight they deserve instead of just using a face that people know for ranting)

**Comment by parthlawate** [comment]
Ok.. Do suggest who else could be on this.. We can make it a group thing.. Also if a lot of them are in the US either Central or Eastern time, someone in EU to coordinate might work better for timezones @ufuk-avcu can you or someone in EU be the host ?

**Comment by Sandra97** [comment]
Content of the landing page is ready.
Parth, you know that it has been decided to see if we can interview the developers of the 3.8 main features or at least having a short explanation from them to describe the benefits of the news 3.8 features so that we can have a blogpost.
I'm closing this issue.

**Comment by Sandra97** [comment]
@parthlawate I already gave the names of people to contact.

**Comment by parthlawate** [comment]
Sorry i think i have been commenting on the wrong issue.. I have been commenting about the Live Hangout on air we decided we shall do about 3.8.. This would be a little different than an itnterview or blog post..  Will create a separate issue for it
