### ISSUE TITLE
[COPYWRITING] JORG  - Core Features/About/Contribute/Benefits/Use Cases Pages

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#113]
The content of these pages of https://www.joomla.org/ need to be carefully reviewed and completed. 

- [x] About Joomla - Rethink and renew it. Some of the text is covered by the new Benefit and Use Cases page. - **Published on Nov. 9, 2017**
- [x] Core Features - Rewrite it, new Icons - **Published on Nov. 9, 2017**
- [x] Add Benefits Page - [New](https://docs.google.com/document/d/1dbzwkJuiSiqo-yV9bhkf_pxwkLz1sfbEztUhu6OON0Y/edit) - **Published on March. 9, 2018**
- [ ] Add Use Cases Page - [New ](https://drive.google.com/drive/u/0/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA)(see also #64 ) 
- [x] Contribute - Rewrite it, with more focus on benefits maybe - **Published on Nov. 9, 2017**

**Comment by mikeveeckmans** [comment]
Contribute - Rewrite : done 
Please review : https://docs.google.com/a/community.joomla.org/document/d/1HqhQ6c7qFWHbMUjo0N6bKnVPyz7Chj29U5L54Q64Zsk/edit?usp=sharing

**Comment by mikeveeckmans** [comment]
about joomla rewrite : https://docs.google.com/a/community.joomla.org/document/d/1ivDva0VJAQC0_MRZ5_G-zPuxWdWAMok1dEDv21HZknI/edit?usp=sharing

**Comment by Sandra97** [comment]
@ufuk-avcu @parthlawate Could you please review these 2 articles.
When validated, I will edit the ones currently online.

**Comment by ufuk-avcu** [comment]
@Sandra97 i reviewed and commented them.

**Comment by mikeveeckmans** [comment]
Review core feature page please : https://docs.google.com/a/community.joomla.org/document/d/1W3V9JrRPosr0gTv8VnbksRIkEsdcXtjAk2h0JBZATEA/edit?usp=sharing

**Comment by mikeveeckmans** [comment]
Benefits page : https://docs.google.com/a/community.joomla.org/document/d/1dbzwkJuiSiqo-yV9bhkf_pxwkLz1sfbEztUhu6OON0Y/edit?usp=sharing 
Took the copy from the brochure which is great, so no need to change it... 
Thanks @Joomv  ;-)

**Comment by Sandra97** [comment]
@ufuk-avcu @parthlawate Please review the About / Contribute and Core Features pages. 
I would like to publish them next week. 
Without any answer/comment, I'll consider them as approved and I'll publish them. 
Deadline: Nov 8th.

**Comment by Joomv** [comment]
Need to en-gb it

**Comment by parthlawate** [comment]
Joomla Use Case  Example - Joomla for Non Profits https://docs.google.com/document/d/13DaPrUBH4n44AT_qFW56PSSo-hNYEpdtAU0277Iq7MU/edit#

**Comment by Sandra97** [comment]
New  content about About/Contribute/Core Features pages has been published.

Please feel free to post here any edits, suggestions... so that we can continue to improve the content.

Thanks @mikeveeckmans  for your work!

**Comment by mikeveeckmans** [comment]
You're welcome

**Comment by Sandra97** [comment]
Benefits content has been published on jorg.

**Comment by Sandra97** [comment]
@mikeveeckmans Seems we need a new sprint together to get the use cases done, as it seems nobody is interested in helping and nothing happened since Nov 17.

**Comment by Sandra97** [comment]
As there's already an issue for use case #64, I'm closing this one
