### ISSUE TITLE
[J3.8] Write a dev-oriented blogpost to publish on jorg

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#114]
The goal would be to target extension devs as this version is more for devs than for integrators.

**Comment by ufuk-avcu** [comment]
@mbabker have you time for this task?

**Comment by ufuk-avcu** [comment]
Here are some informations, what is planned for J3.8: https://github.com/joomla/joomla-marketing/issues/110

**Comment by Sandra97** [comment]
Closing this issue as it won't happen.
