### ISSUE TITLE
Create a reusable form for collection of information from developers on features in new releases

### ISSUE THREAD

**Issue by Joomv** [joomla/joomla-marketing#115]
Starter question ideas:
What is your feature called?  
Who is this feature for?  (Developers/Integrators/Admins/Designers - select all that apply) 
What does this feature solve/do?  
What challenges did you face building this feature?  
How did you overcome those challenges?
What makes this feature a great addition to Joomla?

**Comment by AlisonAMG** [comment]
Do you have other comments or things you want users to know?

**Comment by aDaneInSpain** [comment]
**Release information**
- Release version
- Release type
  - Major
  - Minor
  - Maintenance
  - Security
- Release Name (optional)
----
**Features** (Repeatable)
- Name of feature
- Describe feature in detail
- Who does this feature help (check all that apply)
  - [ ] Administrators
  - [ ] Web site owners
  - [ ] Web site visitors
  - [ ] Web developers
  - [ ] Web designers
  - [ ] Web integrators
  - [ ] Extension developers
  - [ ] Joomla community
  - [ ] Joomla marketing (it helps promote Joomla)
  - [ ] Other (please describe)
- What challenges did you face building this feature and how did you overcome them?
- What makes this a good feature to have in Joomla
- Link to main pull request for this feature

**Comment by zero-24** [comment]
> Security

Why do you want to add Security? Any kind of release can be a Security release. Also the dev don't know if the next version is a Security release anyway ;) Just the groups involved in the release know that ;)

**Comment by mbabker** [comment]
You can scratch maintenance and security off that list.  New features should pretty much never go into those release types per our release strategy (derived from Semantic Versioning).

We stopped doing code names for releases ages ago, except for someone electing to randomly change it in the version class.  We don't have release names and there has been no push from anyone to restart that AFAIK.

**Comment by aDaneInSpain** [comment]
Thanks for the input. I have edited the post to reflect your comments except I have kept "Release name" as I have overheard someone talking about naming the 4.x series after Cities.

**Comment by zero-24** [comment]
Just to be sure this is a list any developer of a feature get to provide information correct?

Is'nt the release name a global decision by the release leader and the individual developer has no idea what this is called? I have not heard anything about `Cities` yet.

**Comment by aDaneInSpain** [comment]
Well... maybe we need something a little bit more advanced. Where the release leader fills in the "Release information" and the contributing developers fill in the "Features" section for each feature?

**Comment by zero-24** [comment]
I would seperate that forms. You need the "release information" only once but you can have XXX features so why should the release leader repeat itself on any feature? ;)

**Comment by aDaneInSpain** [comment]
Yeah, that is why I say we might need something a little bit more advanced than a simple form. A release leader __first__ adds the release and then each developer can "attach" features to it.

**Comment by zero-24** [comment]
Is'nt the complete thing just to collect information about the features? This sounds over engineered to me.

IMO that complete form can be a simple plugin for the contact component attaching the addtional fields (or custom fields) and send that to a email or a google form that does the same => done. Just the definition of the fields is that what this issue here is for or do i missunderstand that?

**Comment by aDaneInSpain** [comment]
No you are probably right. We could make it a simple form where all there is to say about the release is what is the version number.

**Comment by zero-24** [comment]
👍 That sounds good! Just keep off that `release information` beyond planed version number ;)

**Comment by ufuk-avcu** [comment]
- Feature Name
- Feature Function
- Feature Description
- Expected Release Date
- Main developer(s)
- Feature landing/documentation page?
-- Point to the GitHub page?
-- Point to docs.joomla.org
- For whom?
-- Developers, Design, Site Integrator
- Tags
-- Security, Bugfixing,...
- Dependencies
- Marketing liaison
- Pictures, Screenshot, Screencast

**Comment by zero-24** [comment]
### my notes

> Expected Release Date

This has again nothing todo with the feature ;)

> Tags
>-- Security, Bugfixing,...

Is'nt this a 

>Create a reusable form for collection of information from developers **on features** in new releases

> Security

Is not going to be public anyway.. 

> Bugfixing

Do you want to get a submission per PR? Is'nt this a massive overkill?

> Marketing liaison

Where should the **developer** know that?

### cleaned list

- Feature Name
- Feature Function
- Feature Description
- Main developer(s)
- Feature landing/documentation page?
-- Point to the GitHub page?
-- Point to docs.joomla.org
- For whom?
-- Developers, Design, Site Integrator
- Dependencies (optional)
- Pictures, Screenshot, Screencast (optional)

**Comment by ufuk-avcu** [comment]
We can close this: https://docs.google.com/forms/d/e/1FAIpQLSc-xwsYVHTj1ANOPWf0Ek18zkfDnbUrA7zFjhRgOm80gA9Ing/viewform
