### ISSUE TITLE
[Blogpost] Peakon - write a blogpost

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#118]
What is Peakon? What is our goal? Try to engage the people, to answer the questions regulary.

**Comment by Sandra97** [comment]
@mikeveeckmans 
Dear plumber, what's the progress about this blogpost?

**Comment by parthlawate** [comment]
Hi, 

Have done a blog post here. Please review the content and make any suggestions you might have. I aim to publish on CJO this week. 
https://docs.google.com/document/d/12a4x04TCAS9N3JxCA1brZncSo6qNbi871FVhNJJ2-es/edit
Parth

**Comment by Sandra97** [comment]
I'm gonna merge the article to CJO and try to publish it today.

**Comment by parthlawate** [comment]
Thanks @Sandra97 !

**Comment by Sandra97** [comment]
Published.
I'm closing this issue.
