### ISSUE TITLE
Proofread the Intreview with Hannes Pappenberg about the new Router

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#119]
We need to prepare this, before the Joomla 3.8 Relanch (expected next thuesday)

https://docs.google.com/a/community.joomla.org/document/d/1fat7F4bq0SyGIk7KmCaPNlGwtQR8qk4X_yHNibxEDQk/edit?usp=sharing

**Comment by Sandra97** [comment]
@ufuk-avcu What the status of this article?  Is it ready to publish?

**Comment by ufuk-avcu** [comment]
@Sandra97 this should be now ready. @Joomv has an another Blogpost regards the Router in the pipeline. But you can publish this one and close after that this issue.

**Comment by Sandra97** [comment]
@ufuk-avcu, As commented on the Google Doc, I would like a short intro to be able to publish it. And where did you want it to be published? JCM (but it means waiting for November) or Dev?
I'll prepare a pic.

**Comment by Sandra97** [comment]
The article will be published today on the Dev site.
Closing this issue.
