### ISSUE TITLE
[video]Record and Post a Joomla Selfie Video Testimonial with a hashtag #joomla #jwc17 #jtestimonial - target 150

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#120]

**Comment by Sandra97** [comment]
#jwc18?

**Comment by parthlawate** [comment]
fixed :)

**Comment by Sandra97** [comment]
Some interviews have been done during JWC, nothing has been done with them, sources are not in our GG Drive. I'm closing this.

**Comment by agerix** [comment]
however, I've share all the images and videos :(

**Comment by Sandra97** [comment]
I have all your images and the slow motion but not the 'interview' videos

**Comment by Sandra97** [comment]
Thank you Eric!

**Comment by rvbgnu** [comment]
Thank you Eric!
