### ISSUE TITLE
Organise the Joomla Social Media Database in a central sheet  https://docs.google.com/document/d/14pHmjsEMu-UYbEwJuvH8oVL1A52_9571uaK2at1rIHo/edit

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#121]
https://docs.google.com/spreadsheets/d/1cSaKSKyi4bgCdkOgPKXQ9JKr2mnSJKAsFMOHdCi_BIs/edit#gid=0

**Comment by Sandra97** [comment]
@parthlawate When opening an issue, could you please describe what's the task about? If we want volunteers to help us, they will need some guidelines and information about what we want, what's the goal... 
Thank you!

**Comment by Sandra97** [comment]
This is for Social Media and we already have a doc for our properties promotion. So I'm closing this issue
See https://github.com/joomla/socialmedia/issues/11
