### ISSUE TITLE
Social Media imagery 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-marketing#123]
![facebook_shared_image_1200x630_image_bg](https://user-images.githubusercontent.com/828371/32503223-fde82952-c3dc-11e7-8675-7e03d28bd1cb.png)
![facebook_shared_image_1200x630_image_small](https://user-images.githubusercontent.com/828371/32503224-fe5d4732-c3dc-11e7-9f7e-7a637e2a674b.png)
![facebook_shared_image_1200x630_long_text](https://user-images.githubusercontent.com/828371/32503230-ff1ec916-c3dc-11e7-864c-3d1839b0d76b.png)
![facebook_shared_image_1200x630_small_text](https://user-images.githubusercontent.com/828371/32503234-ff74e5bc-c3dc-11e7-941d-f56308db03f1.png)
![facebook_shared_image_1200x630_image_small kopie 2](https://user-images.githubusercontent.com/828371/32503235-ff9c45c6-c3dc-11e7-8a0b-7dfc5c59c5d7.png)
![facebook_shared_image_1200x630_image_small kopie 3](https://user-images.githubusercontent.com/828371/32503236-ffc2444c-c3dc-11e7-9ca4-0131017f1515.png)
![facebook_shared_image_1200x630_image_small kopie](https://user-images.githubusercontent.com/828371/32503237-ffe3b3a2-c3dc-11e7-8c6f-230d2cc29efe.png)
![facebook_shared_image_1200x630_image_small](https://user-images.githubusercontent.com/828371/32503238-00480adc-c3dd-11e7-9038-0720331d7015.png)

[joomla_facebook_shared_image_1200x630_image_bg.psd.zip](https://github.com/joomla/joomla-marketing/files/1450704/joomla_facebook_shared_image_1200x630_image_bg.psd.zip)
[joomla_facebook_shared_image_1200x630_image_small .psd.zip](https://github.com/joomla/joomla-marketing/files/1450706/joomla_facebook_shared_image_1200x630_image_small.psd.zip)
[joomla_facebook_shared_image_1200x630_image_small_2.psd.zip](https://github.com/joomla/joomla-marketing/files/1450707/joomla_facebook_shared_image_1200x630_image_small_2.psd.zip)
[joomla_facebook_shared_image_1200x630_image_small_3.psd.zip](https://github.com/joomla/joomla-marketing/files/1450708/joomla_facebook_shared_image_1200x630_image_small_3.psd.zip)
[joomla_facebook_shared_image_1200x630_image_small.psd.zip](https://github.com/joomla/joomla-marketing/files/1450709/joomla_facebook_shared_image_1200x630_image_small.psd.zip)

[Uploading joomla_facebook_shared_image_1200x630_long_text.psd.zip…]()
[Uploading joomla_facebook_shared_image_1200x630_small_text.psd.zip…]()

**Comment by ufuk-avcu** [comment]
Thank you Elisa!
