### ISSUE TITLE
Customer Profiling/Personas

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#124]
Company Description 
Problems/Pain Points they face
What Solutions are they looking for
What budgets do they have

**Comment by Sandra97** [comment]
Tasks not defined enough. 
I'm closing this issue. 
We still need to improve the profiles we currently have to be able to show that Joomla can answer many needs. 
It's better to create separate task so that volunteers can have a good understanding and overview of what is needed
