### ISSUE TITLE
Define Industry Verticals to Target

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#125]
Find key Industries to Target in verticals Joomla can service. And actual Companies/People that fall under the below 

Management Consultants
Design Agencies
CTO's 
CIO's
Chamber of Commerce, Trade bodies 
Development Shops 
-Wordpress & Joomla 
Key Magazines/Media - Design & Dev Mags
Tech handles like PHP/JS related ones 

Prepare a list of companies/individuals with their Social Media Accounts

**Comment by Sandra97** [comment]
Due to the lack of volunteers, I'm closing this issue.
It can still be re-opened when we have new volunteers.
And better to have one issue = one defined task than an issue containing a list of tasks to achieve.
