### ISSUE TITLE
Collect Article Ideas

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#128]
Define Article Ideas for 3 Main Target Groups 

1. Agencies & freelancers
2. Designers
3. Consultancies
4. Professional Agencies

https://docs.google.com/forms/d/1EjZ0936SGkM3keBjISnRJYBJVzc7ZD3WLVKPjaxX2EA/edit

**Comment by Sandra97** [comment]
@parthlawate Do you know what's the status for this project? Did anyone contact the people who filled the form? Any update?

**Comment by Sandra97** [comment]
Instead of only waiting volunteers to give ideas of articles and do nothing with their ideas, it's better to have a list of articles we would need and create tasks for each, and follow up.
So I'm closing this issue.
