### ISSUE TITLE
Joomla 4 Survey Series

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#129]
In previous releases of Joomla new versions, the project has relied on the feedback gathered from reported issues from community testers and volunteers of the core team. Since most community members are only able to partially test a version, due to lack of time or skills, the final release of a Joomla version is frequently followed by minor versions that correct bugs not found in the initial development process. This process erodes the trust and the collaboration of the whole volunteering effort.

For the next release of the next major version of Joomla, we must double our efforts to communicate the impact of the new features and enhancements to increase the engagement and reduce the loss of developers or extensions in the transition to Joomla 4.

https://docs.google.com/document/d/1QR10j4IaHjaF7w-gns3viob631IZfvnKvQ_AFgyUcyg/edit

**Comment by brianteeman** [comment]
How does this survey satsify any of these goals or go towards educating the userbase about the new features?

**Comment by coolcat-creations** [comment]
Where did all my comments go?

**Comment by parthlawate** [comment]
@brianteeman thanks for jumping in ! 
If you read the later section of the gdoc - you will see this is the first in a series of surveys.. quoting here : 

"For the next release of the next major version of Joomla, we must double our efforts to communicate the impact of the new features and enhancements to increase the engagement and reduce the loss of developers or extensions in the transition to Joomla 4.

To support the communicational effort with a statistical tool, this proposal introduces the Joomla 4 Readiness Survey. The survey will provide indicators about the community awareness of the technical change and the acceptance of the new release. In this way, we will be able to monitor the progress of the communicational effort and the perception of the general community.

Target: All Joomla developers, integrators and tech-savvy users
Frequency: Monthly, after the initial release of the Alpha 1 "

Pls see specifically the target group. The idea is to do this survey in addition to regular communications to check how ready these target audiences are for J4

@coolcat-creations I do see the comments. Are you not able to see them ?

**Comment by brianteeman** [comment]
@parthlawate yes i read all of that and tbh i dont see that this survey satisfies any  of those goals 

When writing a question you have to make sure that they are not leading or vague

For example - what is the purpose of saying
Do you know the benefits of bootstrap 4? etc

The answers don't go towards answering your aim "to communicate the impact of the new features and enhancements"

Assume that the answer is no. Then AFTER posts educating people about the benefits of bs4 you can do another survey to see if your post has had an impact. Creating a survey like this just to get a baseline is a waste of everyone's time - including those who write the survey and those that answer it.

Finally your comments in the introduction are very disrespectful to all the people who are working very hard to produce joomla 4 (and j3 before it) - it states that these people are not very effective and that they produce buggy ill thought out code and features etc.

**Comment by coolcat-creations** [comment]
thats like exactly what i explained on glip earlier today...

**Comment by parthlawate** [comment]
@brianteeman
1. The first section is an internal introduction and I don't think the Author meant any disrespect. But you are right it should be rephrased. I'll pass on the feedback and make sure it is. Also the marketing copy that this goes with is different and external facing and will have a short and clear intent 

2. I've already given my feedback about the second part of the survey - those questions need work.. I'm happy with the first 2-3 questions since it's a monthly survey post the alpha releases till the stable gets out, it would give us an idea on progression of acceptance 

There have been some good suggestions on what the questions can be on the Marketing public room and doc.. We'll which ones can be used to make this effective.. 

The benefits  I saw of the base  idea (not the current questions) are as below : 

1. Gets us an idea of readiness of our audience at regular intervals
2. It's an opportunity to remind them to get ready
3. An opportunity to communicate what they need to do to get ready 
4. It's also a way to check if they have heard about key benefits and impacts J4 will make 

A. Do you agree on the above ? ( Assuming questions are right of course !) 
B. Can you suggest questions that would satisfy the above goals ?

**Comment by mbabker** [comment]
Internal or not, it is a publicly accessible document linked from a publicly accessible resource and the commentary on that should have been thought about before publishing and the fact that project team members are saying that about our release process is just as Brian says disrespectful to all of us who put in the time and effort to make that happen at any level.

**Comment by parthlawate** [comment]
@mbabker I agree completely I should have rephrased the original document even before opening it up for internal consumption. However I do think if anyone has ideas to improve the process there is no harm in accepting them. But yes how it is phrased can ofcourse be improved..

**Comment by brianteeman** [comment]
1. as i said assume a base level of zero at this time
2. reminding them without the information required (eg how to move to namespace code) is pointless
3. thats not the role of a survey. thats the role of a series of "howto" and  "101" articles
4. benefits check is fine but then dont have such loaded questions that only address such a small part of j4. impacts is unknown without information. eg do i have to convert my code to namespace or will it work without converting

A survey is only as good as the questions and the available information.

**Comment by brianteeman** [comment]
Having read the report from the dept meeting at JWC https://volunteers.joomla.org/departments/marketing-communication/reports/709-jwc-16-nov-2017-department-sprint I don;t see how this survey helps match those aims.

If I didnt know better I would say that this survey is purely motivated by a desire from someone to find proof to justify not adopting certain technologies in J4

**Comment by parthlawate** [comment]
I really hope thats not the case @brianteeman ! But as an idea i think its good.. So I'll reword for it to achieve its aim and repost here for comments. 

Those notes are from Mkt & Communication. This wasn't discussed there. Its come up post JWC.

**Comment by brianteeman** [comment]
I hope not too but the concentration on just one area suggested that was the case.

I stand by my view that this is the wrong time to do the survey.

Btw I published a post with notes from a lecture I attended about writing survey questions that you might find useful. https://brian.teeman.net/web/ten-commandments-for-creating-a-survey

**Comment by parthlawate** [comment]
Hello Once again !   @brianteeman thanks went through the blog.. its a good read :) 

I have rephrased the survey, purpose as well as questions. Please review and comment on the same . Page 1-4 only ! 

https://docs.google.com/document/d/1QR10j4IaHjaF7w-gns3viob631IZfvnKvQ_AFgyUcyg/edit#

**Comment by brianteeman** [comment]
Now that's a valid survey. Thanks ms for taking on board the comments

**Comment by parthlawate** [comment]
thanks !

**Comment by Sandra97** [comment]
Due to the lack of volunteers and the fact we had for this reason to switch the team to unofficial, I'm closing this issue.
It would be great to be able to have good user surveys but volunteers are needed to help.
I'm closing this issue, can be re-opened when volunteers are willing to help.
