### ISSUE TITLE
[design] Picture request PLT

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-marketing#13]
Hello,

PLT will open a Call for Volunteers for the Joomla! Security Strike Team (JSST), can you please provide a picture to be published together with the call post?

Thank you for your help!

**Comment by mikeveeckmans** [comment]
@Jeckodevelopment on which page will this be published?

**Comment by jeckodevelopment** [comment]
developers.joomla.org

**Comment by mikeveeckmans** [comment]
@jeckodevelopment what's the title of the article?

**Comment by mikeveeckmans** [comment]
![jsstpost](https://cloud.githubusercontent.com/assets/4589318/17170645/6b2d0f02-53ed-11e6-8a22-ac54950a3f2e.png)
@jeckodevelopment here you go, hope the title is ok.

**Comment by jeckodevelopment** [comment]
Thank you Mike! :)

**Comment by mikeveeckmans** [comment]
You're welcome ;-)

**Comment by MATsxm** [comment]
My 2 cents but I confess I'm not an expert on design :stuck_out_tongue_closed_eyes: 
The "line" for the Visuals is IMHO really great as we can see the interaction between Joomla! (a dematerialized software) and human (at least I guess :wink:).
I'm also really pleased to see that finally we have reference to the Web site (I still don't understand how not every single marketing visual can exist without this mention) really pleased to see things changing.
Now the 2 cts: I would prefer (not saing it should be) the mention to `.org` to be standardized. Could be even smaller, align left and `joomla.org` is more than enough.
In another hand, it could also be a kind of: `more information on joomla.org` or `discover joomla.org` or something this way. The only thing would be to be consistency.
Just a proposal - Thanks

**Comment by Sandra97** [comment]
Or just visit joomla.org ;)

**Comment by jeckodevelopment** [comment]
Thank you very much for your input @MATsxm and @Sandra97

**Comment by mikeveeckmans** [comment]
Thanks @Sandra97 & @MATsxm
