### ISSUE TITLE
JoomlaDay Florida Promotional Material - Joomla Stickers

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-marketing#131]
Joomla stickers needed for the event.   We have been using sticker giant to provide us with free sticker sheets for the past few years.  We have a custom sticker sheet for this year and would like to request 150 official Joomla stickers for the event.

March 3rd 2018 - Tampa, FL

**Comment by ufuk-avcu** [comment]
We have currently no stickers. You can also ask the Events Team for Stickers.
