### ISSUE TITLE
Startup conference marketing event

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-marketing#132]
I approached our start up week about speaking about Joomla and Open Source.  All speaker positions are filled for the year, but they offered a special session and sponsorship.  I know this is way out of the project budget to be the Web Development Track Sponsor.  I submit for approval.  If not approved.  We should really look into how we can get new users and volunteers via marketing.  Any way it goes I will be attending to spread the love of Joomla

[TBSW Sponsorship Proposal Deck_2018.pptx](https://github.com/joomla/joomla-marketing/files/1669629/TBSW.Sponsorship.Proposal.Deck_2018.pptx)

**Comment by ufuk-avcu** [comment]
We wish also to sponsor many events, but we need to choose wisely, how we spend our money - like you said. Otherwise it's always our goal to attract people for Joomla! If you have some Ideas, then you are welcome in the Marketing Group!
