### ISSUE TITLE
JoomlaDay Texas 2018 

### ISSUE THREAD

**Issue by mediaateam** [joomla/joomla-marketing#135]
Hello,
Can you guys makes some posts from the Joomla social media accounts about JoomlaDay Texas? We are pushing to get a few more signup before the event Saturday. Maybe something like this:

@JoomlaDayTexas is this Saturday in Houston, Texas. The code JOOMLAROCKS will give the first ten signups free entry to the event! For more details about the #joomladay visit: www.joomladaytexas.com #jdaytexas2018

**Comment by Sandra97** [comment]
Hi,

We already did a post on our social media channels 
For example: https://twitter.com/joomla/status/987280164487925760

We will do this one with pleasure.

**Comment by mediaateam** [comment]
Thank you guys!

**Comment by hvdmeer** [comment]
I'm the only guy on the team. :grinning:

**Comment by Sandra97** [comment]
Closing this issue as all has been done and the event passed
