### ISSUE TITLE
[COPYWRITING] Use Case: Joomla for Small Business Websites

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-marketing#136]
### Keywords & Phrases to Optimise for : 
Small business websites
Affordable small business websites
Marketing
Websites
SEO
Search engine optimisation

### Quick Background & Problem Statement
Every small business needs a website. In the ‘old days’, a simple static website would suffice for most but in a rapidly changing business environment a company’s website needs to be dynamic and responsive to meet new challenges.

To remain responsive, a small business website needs to be easily updatable. This is achieved by using a content management system (CMS) like Joomla! 

Joomla allows website owners to add and edit pages quickly and easily without the need to know how a website works behind the scenes. This means Joomla can be crucial to the success of your small business by enabling your website to meet the new challenges and needs of your business.

### Basic Features Needed
A modern small business website must have the following basic features:

* Easy Content Management - ability to add, edit and organise pages
* Contact forms
* Security
* Design flexibility

### Advanced Features Needed
* Integrate with 3rd party systems
* Manage marketing campaigns
* User Management and Access control
* Events, Calendar
* Forms management
* SEO - search engine optimisation

### Possible Solutions
Once you have realised that a static website is no longer sufficient, business owners have several choices for managing their website. One option is to use an online SAAS website services provided some some hosting and domain name registration companies. Another option is to buy a closed source content management system. Both these options have important drawbacks, and these include:

- You don’t own the website, or often even your own content.
- Baked in designs make it harder to differentiate your site via its design.
- The flexibility of your website is restricted by the limitations of the chosen platform.
- Limitations that can hamper effective SEO campaigns.

So, while these systems often look like an obvious quick win, they are a false economy that may cost your business in the long run.

For the best business solution, read on!

### How Joomla can help you build a successful small business website
https://docs.google.com/document/d/1GlmlwBMMthKh13La5sZozmrsOeFeSt0FxwitoW4h9V0/edit#

Matching category with the Joomla Showcase Directory: **Business**
https://showcase.joomla.org/browse-sites.html?search=showcase_search&task=search&item_category_frontend=35

## Guidelines

**Volunteer Requirements**
We need 1-2 Content writers (Per subject) who can help either individually write content or collaborate on it and publish these articles in the Joomla community magazine.

**Complete information on the campaign & some work done in earlier MIH sessions**
https://docs.google.com/document/d/1Oytc-aFZ1SZ17bYP4Vj5YEopLmHXo-jKMBJ1tfbtvwE/edit#

_Please note that if you do need to mention extensions, please use JED Links (Preferably link to the [overall Extension category](https://extensions.joomla.org/category/photos-a-images/slideshow/)) rather than a specific extension if possible._

_Please give the link to real case(s) through the [Joomla Showcase Directory](https://showcase.joomla.org/), instead of the website link directly._

**Staging Area to upload your content**
https://drive.google.com/drive/u/3/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA

**Main Guidelines and General Discussion**
[Copywriting] The Joomla Use Cases #64

**Comment by rvbgnu** [comment]
@freshweb Your document **Use Case: Joomla for Small Business Websites** is now referenced in this issue. Discussion and comments are welcome here!

Please for content suggestions, use the **Suggesting** mode in the document below
https://docs.google.com/document/d/1GlmlwBMMthKh13La5sZozmrsOeFeSt0FxwitoW4h9V0/edit#

**Comment by Sandra97** [comment]
I'm closing this task as we're reorganising this repository.
