### ISSUE TITLE
[COPYWRITING] Use Case: Joomla for Events and ticketing

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-marketing#139]
### Keywords & Phrases to Optimise for : 
building an event website
Joomla event template
event websites on joomla
Conference website
Meetup website

### Quick Background & Problem Statement
Whether you’re organizing a local meetup or a global conference, a small party or a 3 day festival, you’re creating an event and you need a website. What makes an event happen? The answer is simple: people. However, the execution definitely gets more complex. You need to first convince people that they need to be at your event; then you need to make them commit to it (most often through buying a ticket); and then you have to make sure they actually show up.

Fortunately, a relatively simple website can help you achieve all your event marketing goals. Even better, the free Joomla! CMS is perfectly suited for such a site.

### Basic Features Needed

- Schedule/Agenda Page
- Speakers/Sessions Page
- Testimonials
- Photo Gallery
- Sponsor List
- Blog/News

### Advanced Features Needed
- Ticket Sales and Management
- Guestlist Management
- Invoicing

### Possible Solutions

https://splashthat.com/

Matching tag with the Joomla Showcase Directory: **Event**
https://showcase.joomla.org/browse-sites.html?search_generic_showcase_items=&item_tags_search%5B%5D=24&item_featured=&item_joomla_version=&item_country_search=&item_search_ordering=art_id%3Adesc&responsive=&submisison_date=&cck=showcase_items&art_created=&art_created_hidden=&art_created_datasource=computed&item_category_frontend=&item_creator=&item_state=1&art_access=1&moderation_status=1&tags_id_for_join=24&search=showcase_search&task=search

## Guidelines

**Volunteer Requirements**
We need 1-2 Content writers (Per subject) who can help either individually write content or collaborate on it and publish these articles in the Joomla community magazine.

**Complete information on the campaign & some work done in earlier MIH sessions**
https://docs.google.com/document/d/1Oytc-aFZ1SZ17bYP4Vj5YEopLmHXo-jKMBJ1tfbtvwE/edit#

_Please note that if you do need to mention extensions, please use JED Links (Preferably link to the [overall Extension category](https://extensions.joomla.org/category/photos-a-images/slideshow/)) rather than a specific extension if possible._

_Please give the link to real case(s) through the [Joomla Showcase Directory](https://showcase.joomla.org/), instead of the website link directly._

**Staging Area to upload your content**
https://drive.google.com/drive/u/3/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA

**Main Guidelines and General Discussion**
[Copywriting] The Joomla Use Cases #64

**Comment by Sandra97** [comment]
I'm closing this task as we're reorganising this repository.
