### ISSUE TITLE
[capital] Joomla Media Kit for Potential Sponsors

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-marketing#14]
It would be great to have a media kit available for those who are requesting such.

The kit should include, among other things, all the official Joomla logos and brand materials that anyone might need for their landing pages and print requirements.

It needs to be in an easily available and always up to date.

**Comment by MATsxm** [comment]
And available for t9n...
At this point... See the Doc

**Comment by designbengel** [comment]
First we would need to define what´s exactly included in the Media-Kit (For example also basic designfiles for JoomlaDays, Joomla! Blogpost Templates, ...) And who is allowed to use them. Everything is available on Google Drive right now... Is your issues related to a current project, Joe ?

**Comment by JoeJoomla** [comment]
Some of the things we need in a media kit are the technical details of the packages and banner sizes which is easy to compile. Mike Demopoulos has lots of good stuff that he has been using for the World Conference sponsorship pitching that could be used in a general media kit.

Other items we need are statistics on page views for the various website properties. That will come from Analytics. This may not be part of the standard media kit but be handy to have for more specific and targeted pitches.

The current things that are being pitched to potential new sponsors right now are for the Global Sponsor packages <https://www.joomla.org/current-sponsors.html <https://www.joomla.org/current-sponsors.html>>.

We have also long wanted to sell banner advertising space directly to sponsors on various Joomla website properties.

The Revive Ad Server is all set up and currently all http://magazine.joomla.org/ <http://magazine.joomla.org/> site ads are being served by the ad server. At the moment all the ads are simply AdSense ads but once the training site is made public we’ll introduce specific banner advertising in the rotation to help drive traffic to it. We can also start implementing general community advertising for things like the World Conference into the mix as well.

Joe

**Comment by jayblaq** [comment]
Bump.   Yes!  A full Media Kit is needed!

**Comment by cpaschen** [comment]
We'll add this to the (growing) to-do list; however, we have a few other urgent things right now that must come first.
If anyone is able to connect with Mike D and see if he could share some of his material (and post links here) that would help this move forward a bit faster.

**Comment by ufuk-avcu** [comment]
Is this enough or need we more? If yes what is needed?
 https://docs.joomla.org/Joomla:Brand_Identity_Elements/Official_Logo

**Comment by ufuk-avcu** [comment]
@mdemop can you share with us the materials you have?

**Comment by ufuk-avcu** [comment]
Merged here: https://github.com/joomla/joomla-marketing/issues/111
