### ISSUE TITLE
[COPYWRITING] Use Case: Joomla as a CRM Plateform

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-marketing#140]
### Keywords & Phrases to Optimise for : 
CRM 
Open Source CRM 
Online CRM

### Quick Background & Problem Statement
Your customer base is growing and keeping the contact with them is getting harder and harder? Then you may should think about using a customer relationship management system to keep all data together. With a great customer relationship you can track your customer behaviour, get to know them better and give them the feeling you are interested in them. 

### Basic Features Needed

- Customer Profiles
- Define Lifecycle milestones
- Reporting 
- ACL (Core)
- Workflow
- Lead Management
- Marketing Analytics

### Advanced Features Needed

- Automatic mailings
- Notification center

### Possible Solutions
A possible solution for your CRM could be a special application like Microsoft Dynamics CRM or Salesforce. These systems are feature rich and provide everything you need but they have their price. If you are looking for a free or low cost solution an open source application may be your way to go. SugarCRM or YetiForce for example are special CRM applications which are free to use and easily extendable. 

### How Joomla! Can help you Build a CRM Platform
To use Joomla! As a CRM Platform we recommend using one of the [CRM extensions](https://extensions.joomla.org/category/crm/) which you can find in our Joomla! Extension Directory. The good part: You can extend your CRM even more. Combine it with a [helpdesk](http://extensions.joomla.org/category/help-desk) or even a [social network](http://extensions.joomla.org/category/communities) for your customer. 

## Guidelines

**Volunteer Requirements**
We need 1-2 Content writers (Per subject) who can help either individually write content or collaborate on it and publish these articles in the Joomla community magazine.

**Complete information on the campaign & some work done in earlier MIH sessions**
https://docs.google.com/document/d/1Oytc-aFZ1SZ17bYP4Vj5YEopLmHXo-jKMBJ1tfbtvwE/edit#

_Please note that if you do need to mention extensions, please use JED Links (Preferably link to the [overall Extension category](https://extensions.joomla.org/category/photos-a-images/slideshow/)) rather than a specific extension if possible._

_Please give the link to real case(s) through the [Joomla Showcase Directory](https://showcase.joomla.org/), instead of the website link directly._

**Staging Area to upload your content**
https://drive.google.com/drive/u/3/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA

**Main Guidelines and General Discussion**
[Copywriting] The Joomla Use Cases #64

**Comment by Sandra97** [comment]
I'm closing this task as we're reorganising this repository.
