### ISSUE TITLE
[COPYWRITING] Use Case: Joomla for Non Profits

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-marketing#142]
### Keywords & Phrases to Optimise for :
Non profit website
Non profit template 
Free website 
Charity Website
Charity hosting
Donation Website
Online Donations 

### Quick Background & Problem Statement
A non profit organisation faces its unique set of challenges. Championing their cause, getting found online, inspiring members to join as volunteers, collecting donations, managing donor communication & increasing engagement are just some of these! 

A big part of the solution to these challenges can be provided with the right set of tools. A website or application that can help the non profit organisation management and volunteers can be a great way to make these tools available. So what does a typical non profit organisation need ? 

### Basic Features Needed
* Easy Content Management for Updates, Blogs, Photos, Videos for not necessarily technically proficient staff
* Ability to search content
* Ability for Visitors to contact them
* Access control

### Advanced Features Needed
* Share Documents
* Fundraising / Donation
* Donor Communications via Newsletters
* Donor Community
* Events, Calendar

### Possible Solutions
If you want an easy-to-use and modern looking website, it is recommended to go for a online website building tool like wix.com, squarespace or jimdo. With such tools you can easily create your content, adjust the design and be visible for your members and donors. If you want something even more basic, you could consider a Facebook page. 

While these tools would be good to get started with a basic site, they offer a limited set of features. Here a customised solution based on an open source CMS like Joomla which will offer you a solution that is extremely customisable, scalable, future-proof and cost effective. 

### How Joomla Can help you Build a Non Profit Website
https://docs.google.com/document/d/13DaPrUBH4n44AT_qFW56PSSo-hNYEpdtAU0277Iq7MU/edit#

Matching category with the Joomla Showcase Directory: **Non-Profit Organization**
https://showcase.joomla.org/browse-sites.html?search=showcase_search&task=search&item_category_frontend=54

Matching category with the Joomla Showcase Directory: **Society**
https://showcase.joomla.org/browse-sites.html?search=showcase_search&task=search&item_category_frontend=47

## Guidelines

**Volunteer Requirements**
We need 1-2 Content writers (Per subject) who can help either individually write content or collaborate on it and publish these articles in the Joomla community magazine.

**Complete information on the campaign & some work done in earlier MIH sessions**
https://docs.google.com/document/d/1Oytc-aFZ1SZ17bYP4Vj5YEopLmHXo-jKMBJ1tfbtvwE/edit#

_Please note that if you do need to mention extensions, please use JED Links (Preferably link to the [overall Extension category](https://extensions.joomla.org/category/photos-a-images/slideshow/)) rather than a specific extension if possible._

_Please give the link to real case(s) through the [Joomla Showcase Directory](https://showcase.joomla.org/), instead of the website link directly._

**Staging Area to upload your content**
https://drive.google.com/drive/u/3/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA

**Main Guidelines and General Discussion**
[Copywriting] The Joomla Use Cases #64

**Comment by rvbgnu** [comment]
@parthlawate Your document **Use Case: Joomla for Non Profits** is now referenced in this issue. Discussion and comments are welcome here!

Please for content suggestions, use the **Suggesting** mode in the document below
https://docs.google.com/document/d/13DaPrUBH4n44AT_qFW56PSSo-hNYEpdtAU0277Iq7MU/edit

**Comment by Sandra97** [comment]
I'm closing this task as we're reorganising this repository.
