### ISSUE TITLE
[COPYWRITING] Use Case: Joomla for Enterprise

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-marketing#152]
### Basic Features Needed
* To add

### Advanced Features Needed
* To add

### Possible Solutions

Matching category with the Joomla Showcase Directory: **Business**
https://showcase.joomla.org/browse-sites.html?search=showcase_search&task=search&item_category_frontend=35

## Guidelines

**Volunteer Requirements**
We need 1-2 Content writers (Per subject) who can help either individually write content or collaborate on it and publish these articles in the Joomla community magazine.

**Complete information on the campaign & some work done in earlier MIH sessions**
https://docs.google.com/document/d/1Oytc-aFZ1SZ17bYP4Vj5YEopLmHXo-jKMBJ1tfbtvwE/edit#

_Please note that if you do need to mention extensions, please use JED Links (Preferably link to the [overall Extension category](https://extensions.joomla.org/category/photos-a-images/slideshow/)) rather than a specific extension if possible._

_Please give the link to real case(s) through the [Joomla Showcase Directory](https://showcase.joomla.org/), instead of the website link directly._

**Staging Area to upload your content**
https://drive.google.com/drive/u/3/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA

**Main Guidelines and General Discussion**
[Copywriting] The Joomla Use Cases #64

**Comment by Sandra97** [comment]
I'm closing this task as we're reorganising this repository.
