### ISSUE TITLE
[COPYWRITING] Use Case: Joomla for Multilingual Websites

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-marketing#159]
### Basic Features Needed
* To add

### Advanced Features Needed
* To add

### Possible Solutions
Joomla has always been a great tool for building multilingual web sites and has multilingual content built right into the core, as well as several really powerful extensions that help you manage and translate your content. Features such as content association and the support for Right To Left (RTL) languages makes Joomla the solid choice for growing multilingual websites.

Matching tag with the Joomla Showcase Directory: **Multilingual**
https://showcase.joomla.org/browse-sites.html?search_generic_showcase_items=&item_tags_search%5B%5D=39&item_featured=&item_joomla_version=&item_country_search=&item_search_ordering=art_id%3Adesc&responsive=&submisison_date=&cck=showcase_items&art_created=&art_created_hidden=&art_created_datasource=computed&item_category_frontend=&item_creator=&item_state=1&art_access=1&moderation_status=1&tags_id_for_join=39&search=showcase_search&task=search

## Guidelines

**Volunteer Requirements**
We need 1-2 Content writers (Per subject) who can help either individually write content or collaborate on it and publish these articles in the Joomla community magazine.

**Complete information on the campaign & some work done in earlier MIH sessions**
https://docs.google.com/document/d/1Oytc-aFZ1SZ17bYP4Vj5YEopLmHXo-jKMBJ1tfbtvwE/edit#

_Please note that if you do need to mention extensions, please use JED Links (Preferably link to the [overall Extension category](https://extensions.joomla.org/category/photos-a-images/slideshow/)) rather than a specific extension if possible._

_Please give the link to real case(s) through the [Joomla Showcase Directory](https://showcase.joomla.org/), instead of the website link directly._

**Staging Area to upload your content**
https://drive.google.com/drive/u/3/folders/0B-ot4td3p7XeV2JScHFwU0VPZDA

**Main Guidelines and General Discussion**
[Copywriting] The Joomla Use Cases #64

**Comment by Sandra97** [comment]
I'm closing this task as we're reorganising this repository.
