### ISSUE TITLE
Joomla 4 WG Lead

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#162]
The Joomla Marketing team is looking for a Joomla 4 Marketing Team Lead who will be in charge of:
-  Applying the agreed marketing plan, 
- Coordinating the whole marketing campaign
- Creating a team to achieve the mission.

 The Lead will be in close contact with the Release Lead. 

https://volunteers.joomla.org/teams/joomla-4-marketing-team

**Comment by acvmultimedia** [comment]
OK, I'll do my best.
