### ISSUE TITLE
[imagery] JoomlaDay Chicago 2020

### ISSUE THREAD

**Issue by sdwdeiahil** [joomla/joomla-marketing#164]
Would it be possible to get an image for JoomlaDay Chicago 2020?  The event is Oct 17, 2020 at DePaul University Loop Campus.  We have updated the website and will push out requests for sponsors and speakers (we already have 1 signed up) before the end of the month.

**Comment by AlisonAMG** [comment]
Hi sdwdeiahil 

I have created images to use for promotion on our official channels and have attached them here. 

You are in charge of creating specific promo images for your event. :) 

Have a super day! 
Alison

![JDayChicago-2020](https://user-images.githubusercontent.com/3825882/70850285-9c81e280-1e56-11ea-8c18-ef8e0ece874f.png)
![JDayChicago2020-Insta](https://user-images.githubusercontent.com/3825882/70850286-9c81e280-1e56-11ea-8201-db3877866811.png)

**Comment by sdwdeiahil** [comment]
THANK YOU
___________________________________________________________________________
SD Williams | sdw@danicoenterprises.com | office: 847-241-4227 direct: 847-241-4227 x801
Danico Enterprises, Inc - Arlington Heights | www.danicoenterprises.com
Web & Marketing Services

Need assistance? help@danicoenterprises.com
