### ISSUE TITLE
Social Media WG Contributor(s)

### ISSUE THREAD

**Issue by mqueme** [joomla/joomla-marketing#169]
Please fill in a comment to sign up to this WG and list skills you can contribute with together with number of hours you can contribute per month.

You will be assigned to the WG related to this issue.

**Comment by Sandra97** [comment]
More information on the dedicated repository: 
https://github.com/joomla/socialmedia/issues

**Comment by OnTheMarkDesign** [comment]
I'm on the JCM Team as an Editor/Proofreader, and will also be networking in our Joomla! (and Open Source) Community for new Authors (and potential JCM Team Members)

There is NO "label" in this GH repository for "JCM", perhaps it can be added?

**Comment by hvdmeer** [comment]
I don't see the need for a JCM label on this issue. In fact, to me this issue can be closed as we from the SMT have our own official team @mqueme . We do not fall under the Marketing team, both our teams are in the Marketing and Communication Department.

**Comment by OnTheMarkDesign** [comment]
From https://github.com/joomla/joomla-marketing

The aim of this repo is to manage the work of the Marketing Team and promote transparency a**cross all areas of The Joomla! Project**

Seem to me that the JCM would be a venue for getting "word" out about any marketing efforts of the Joomla! project!

**Comment by AlisonAMG** [comment]
That may be Mark but this is the Social Media not Magazine. *Edit* and SMT already promotes the magazine and all contents every month something is put out.

**Comment by hvdmeer** [comment]
Mark, your asking your question in the wrong place. Please create a new issue in this repo about your question. Now you are just using another issue for your own purpose. Thank you!

**Comment by OnTheMarkDesign** [comment]
Sorry for taking up everyone's time
