### ISSUE TITLE
Imagery for the Joomla! L10N Centre (Twitter)

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#17]
In order to improve the communication of this [Twitter Account] (https://twitter.com/JoomlaL10nC), we would like some generic imagery:
- A nice cover picture related to translation
- Pictures for our most frequest Tweets: 

1. Official Component Patchtester from The Joomla! Project™: New strings to translate 
2. Official Joomla! Issue Tracker™ website: New strings to translate 
3.   Joomla! CMS: New strings to translate 
4.  New Languages available! 

Thank you!
(PS: not urgent)

**Comment by designbengel** [comment]
First one:
If you like this, please test if the flags stay at the top by scrolling. if not i´ll have to change the position of the flags :)
![l10_twitter_cover_1500x500](https://cloud.githubusercontent.com/assets/828371/17636815/e900cda2-60df-11e6-93de-5b0cd1f1d89d.png)

**Comment by designbengel** [comment]
![l10_twitter_cover_1500x500](https://cloud.githubusercontent.com/assets/828371/17636902/826317ca-60e0-11e6-9e18-d7f0c6e402fc.png)

**Comment by designbengel** [comment]
![l10_account_twitter_cover_1500x500](https://cloud.githubusercontent.com/assets/828371/17642821/779609a4-6155-11e6-833f-2fa91f727779.jpg)

**Comment by Sandra97** [comment]
Thank you Elisa. Better like this. I like it!

**Comment by MATsxm** [comment]
you could have had the flag of SXM just saying :stuck_out_tongue_winking_eye: 
Great!

**Comment by MATsxm** [comment]
OH BOY!!!! need another :coffee: 
it **IS** just in front :stuck_out_tongue_winking_eye:

**Comment by designbengel** [comment]
:-D

**Comment by Sandra97** [comment]
@designbengel, one more image to create...
 Could you create a nice generic image to say thank you to the translators?
Thanks!

**Comment by Sandra97** [comment]
For the generic images, please forget in my first message points 1-2-3 and replace it by:

- [ ] New strings to translate for The Joomla! Project
- [ ] Joomla! needs your talent! Join us and help us to translate into your language

Thank you!

**Comment by Sandra97** [comment]
As I have the PSD template for the imagery, I can do the pics we need.
Thank you.
Closing this issue.

**Comment by coolcat-creations** [comment]
@Sandra97 We already have one generic for the translators - or i can change the text for you. It´s the Thank you image on the 3.6. Landing page - i think the heart fits good?

**Comment by Sandra97** [comment]
Don't worry, I know you can do them when we need. 
As when we need a specific pic for a Tweet, all has to be done in the minute, so that's why I think it's better if I do them myself and not ask you to stop  all you're doing to create a pic.

**Comment by coolcat-creations** [comment]
Allright :)
