### ISSUE TITLE
[event] JoomlaDay Kenya 2016 Promotional Material..

### ISSUE THREAD

**Issue by Shedyk** [joomla/joomla-marketing#18]
Hi, 
JDayKe will be on September 17th and we would like some support on promotional materials. We are expecting an attendance of approx 100.

**Comment by mikeveeckmans** [comment]
Hi @Shedyk ,
Thank you for your request. Can you tell me where Jday Kenya will take place ? 
Also if possible clarify the "promotional materials" you want. Thank you.
What is the delivery deadline?

**Comment by Shedyk** [comment]
Hi @mikeveeckmans ,

Sorry it seems information I provided is a little sketchy.  So here goes,
Venue: iLabAfrica, Nairobi, Kenya.
Date: 17th Sept 2016
No. Attendees: Apprx 100
link: [www.joomladay.or.ke](www.joomladay.or.ke) 

For the promotional materials we were thinking in the line of tshirts, bags, pamphlets, stickers and/or any giveaways as may be available.

Thanks

**Comment by Shedyk** [comment]
Hi @mikeveeckmans 
Just a follow up, are this items available and would will it be possible in the time frame given.

**Comment by mikeveeckmans** [comment]
Hi @Shedyk , i can send you stickers and flyers, however none of the others. 
You can sent me a quotation on the shirts and or bags by email, and we'll review then.

**Comment by Shedyk** [comment]
Thanks Mike. Will send you email

**Comment by mikeveeckmans** [comment]
Shipped ;-)

**Comment by Shedyk** [comment]
Thanks.. :+1:
