### ISSUE TITLE
Joomla 3.10 Release

### ISSUE THREAD

**Issue by andreagentil** [joomla/joomla-marketing#183]
- [x]  Preparing the 3.10 Blog Post + image
- [x] Sharing with the Marketing Liaisons Team the blog post
- [ ] Setting up the blog post in jorg 
- [x] Preparing newsletter

On release day:

- [x] Inform the SM team and liaisons teams once the release is live
- [x] Send the newsletter
- [x] Add the translations to the blog post

**Comment by zero-24** [comment]
As it is going to be released alongside beta 3 this here is the blog post: https://docs.google.com/document/d/1sdZ6VKcN0EFh6Hw649YMNpDNiLUMt2gN77Znm9oyuLo/edit#
