### ISSUE TITLE
[copywriting] Improving consistency of the "Contribute" page.

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-marketing#19]
Hello!

Can you please improve the text on the "Contribute" page, adding a paragraph about the Volunteers Portal? 
URL: https://www.joomla.org/contribute-to-joomla.html 

Thank you

**Comment by mikeveeckmans** [comment]
Sorry it took me a while but here you go, this is a suggestion : 
<h2>The Joomla! Volunteers Portal</h2>
<p>All our volunteers, working groups and their (meeting)reports are listed on the <a href="https://volunteer.joomla.org/">Joomla! Volunteers Portal</a>. If you are contributing to the project, don't hesitate to add yourself to the portal. Are you willing to contribute to Joomla!, but haven't got an idea yet on how? Each Working Group has an overview on how to get involved with that Working Group.</p>

**Comment by mikeveeckmans** [comment]
`<h2>The Joomla! Volunteers Portal</h2>
<p>All our volunteers, working groups and their (meeting)reports are listed on the <a href="https://volunteer.joomla.org/">Joomla! Volunteers Portal</a>. If you are contributing to the project, don't hesitate to add yourself to the portal. Are you willing to contribute to Joomla!, but haven't got an idea yet on how? Each Working Group has an overview on how to get involved with that Working Group.</p> `

**Comment by jeckodevelopment** [comment]
Just two small typos:
> their (meeting)reports 

missing space between (meeting) and reports.

And, please remove the bang from "Joomla!" (or the comma) here:
> Are you willing to contribute to Joomla!, but haven't got an idea yet on how

@mikeveeckmans can you add it to the "Contribute" page?

**Comment by Sandra97** [comment]
I'm gonna add it now to the page as well as corrected the other typos of the page

**Comment by jeckodevelopment** [comment]
Thank you both!

**Comment by mikeveeckmans** [comment]
Thank you @Sandra97 
You're welcome @jeckodevelopment

**Comment by Sandra97** [comment]
Done!

**Comment by Sandra97** [comment]
Related to this "issue", I think the paragprah "Join a Joomla! Working Group" should also be reviewed. The name of the teams are not correct for example. Maybe we should "mix" both?

**Comment by mikeveeckmans** [comment]
Yeah, that's needs reviewing as well. -->

Join a Joomla! Working Group

Hundreds of community members contribute by participating in the Joomla! Working Groups. Each group focuses on a specific aspect of Joomla! essential to the Project's overall growth and all have formal expectations and goals. Anyone interested in helping Joomla! grow is encouraged to join a working group where they feel their talents and interests lie. See the team pages and blogs below to find out more about each group and how you can help:

    Development Team
    Documentation Team
    Extension Directory Editors
    Sites and Infrastructure Team / Forum Moderators
    Translation Teams (Translations Forum)

**Comment by jeckodevelopment** [comment]
Development Team ... anyone can contribute with code on GitHub. I guess that it could be splitted in a separate paragraph, "Contribute to Joomla! with Code".

Extension Directory Editors... it's a Team and we're not "editors", furthermore there're a variety of roles that people could have in JED. And, finally the name should be "Extensions Directory", plural.

Sites and Infrastructure Team... do we have one? We have "Webmasters Team" that includes all website mainteiners... but they're mainly member of other teams. 
Forum moderators is ok :)

Translation Team, i think that it need to be splitted (as for Code)

**Comment by Sandra97** [comment]
@mikeveeckmans, could your team help with the review of this  "Join a Joomla! Working Group" part?

**Comment by mikeveeckmans** [comment]
Join a Joomla! Working Group
Hundreds of community members contribute by participating in the [Joomla! Working Groups](https://volunteer.joomla.org/teams). Each group or team focuses on a specific aspect of Joomla! essential to the Project's overall growth and all have formal expectations and goals. Anyone interested in helping Joomla! grow is encouraged to join a working group where they feel their talents and interests lie. Have a look at the volunteers portal and get involved!

**Comment by mikeveeckmans** [comment]
@Sandra97 : or do you want mentions of some teams/groups ?

**Comment by Sandra97** [comment]
Personally, I'm not for mentioning only some groups. All or none. 
If we're removing the team part, I think we should mix this part with the "The Joomla! Volunteers Portal" part. No need to have twice nearly the same thing. (Note that if we mix them, I prefer Join a Joomla! Working Group as title than The Joomla! Volunteers Portal)

**Comment by mikeveeckmans** [comment]
@Sandra97 i understand, however 2 "items" here , 1 the volunteers portal already changed "working groups" to teams it seems, and in the (nearby-far future) transition working groups will be renamed to teams... 
So it would become : Join a Joomla! Team ? 
 I'll get the 2 items in a blender and come up with 1 mix ;-)

**Comment by Sandra97** [comment]
Join a Joomla! Team is fine for me.

**Comment by mikeveeckmans** [comment]
@Sandra97  what about this? 

Join a Joomla! Team
All our [volunteers](https://volunteer.joomla.org/joomlers) contribute by participating in the [Joomla! Teams](https://volunteer.joomla.org/teams). Each team focuses on a specific aspect of Joomla! essential to the Project's overall growth and all have formal expectations and goals.  If you are contributing to the project, don't hesitate to add yourself to the [portal](https://volunteer.joomla.org/). Are you willing to contribute to Joomla! with your talent or interest? Each team has an overview on how to get involved with that team.

**Comment by Sandra97** [comment]
Would it be possible to integrate, maybe in a different way, "All our volunteers, woring groups/teams and their (meeting) reports are listed on the Joomla! Volunteers Porta"l?

**Comment by mikeveeckmans** [comment]
Join a Joomla! Team
All our volunteers contribute by participating in the Joomla! Teams. Each team focuses on a specific aspect of Joomla! essential to the Project's overall growth and all have formal expectations and goals. If you are contributing to the project, don't hesitate to add yourself to the portal. Are you willing to contribute to Joomla! with your talent or interest? Each team has an overview on how to get involved with that team their (meeting) reports are also posted on the Joomla! Volunteers Portal.

**Comment by Sandra97** [comment]
Approved. I'm gonna make the change.

**Comment by mikeveeckmans** [comment]
@Sandra97 Thank you ;-)

**Comment by Sandra97** [comment]
And thank you for the text!

**Comment by Sandra97** [comment]
Page updated.
