### ISSUE TITLE
[imagery] request from PLT, call for volunteers

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-marketing#20]
Hello,
Can you please provide an image for the blog post for PLT?
Text: call for volunteers CMS Release Team.

Thank you

**Comment by designbengel** [comment]
![joomla_call_volunteers_plt_release_team](https://cloud.githubusercontent.com/assets/828371/17585459/2dc86a32-5fbc-11e6-9569-87c7386f258e.jpg)

**Comment by Sandra97** [comment]
In order to create consistency, would it be possible to have "Visit joomla.org" on every imagery?

**Comment by jeckodevelopment** [comment]
Thank you very very very much Elisa!
The image is really GREAT!

**Comment by mikeveeckmans** [comment]
Agree with Sandra

Sent from my iPhone

On 11 Aug 2016, at 12:11, Sandra Thevenet <notifications@github.com<mailto:notifications@github.com>> wrote:


In order to create consistency, would it be possible to have "Visit joomla.org<http://joomla.org>" on every imagery?

-

**Comment by jeckodevelopment** [comment]
So i'll wait for the "consistency update" :)

**Comment by jeckodevelopment** [comment]
BTW, I've to say that the image is not compliant with our brand manual: https://tm.joomla.org/brand-manual-and-limited-use-logos 
Because of the clover logo placed without the correct spacing.

**Comment by MATsxm** [comment]
@jeckodevelopment 
I would say here it's not a big deal as it is not a substantial modification of the logo and made by/for an official Team
(Have you seen the Pokemon Drupal's logo integration? - it's just a matter of policy choice)

**Comment by jeckodevelopment** [comment]
So, ok! Please @designbengel update the image with "visit joomla.org" so i can publish the call for volunteers.

**Comment by designbengel** [comment]
Sorry didn´t get the notifications somehow
@Sandra97 - thats why i removed visit - like i was asked to remove more at: for the LP images, i can add it of course again.
@jeckodevelopment Thank you for taking care of the brandmanual, that´s a very important thing. It´s right that the brandmark has to have some space around it. It´s used here in a creative way, including the TM and the original Logo is embedded in the right way and spaces. The reason why i point out that often to the brandmanual is, that it´s difficult for some not much experienced designers "breaking the rules" by still remaining brand compliant.
will update the pic asap.

**Comment by designbengel** [comment]
![joomla_call_volunteers_plt_release_team](https://cloud.githubusercontent.com/assets/828371/17615611/b2c1705e-606f-11e6-9c6d-a86102b0964c.jpg)

**Comment by jeckodevelopment** [comment]
thank you @designbengel !

**Comment by Sandra97** [comment]
@designbengel, I asked you to remove the "more at" on the LP imagery as it was not translatable (next time it will). For this one, it's different as it's a "one shot pic" so no need to translate it.
I'm gonna be a PITA, next time, could you please capitalize Visit?
Thank you!
