### ISSUE TITLE
[imagery] Touch Icon on Websites

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-marketing#22]
Please refresh the icon that gets used for our `apple-touch-icon` metadata in the template (https://www.joomla.org/templates/joomla/images/apple-touch-icon-144-precomposed.png).

Please provide a larger size file that I can downsize as appropriate.  I'll handle sizing it correctly for all references it'll have.

x-ref: https://github.com/joomla/jdotorgtemplate/issues/64

**Comment by mikeveeckmans** [comment]
[iconified.zip](https://github.com/joomla/joomla-marketing/files/461109/iconified.zip)
and 
![base](https://cloud.githubusercontent.com/assets/4589318/18341833/260b32b0-75ac-11e6-9d0c-45e25ca7f2e9.jpg)

**Comment by mikeveeckmans** [comment]
@mbabker these good ?

**Comment by mbabker** [comment]
That'll work!
