### ISSUE TITLE
[event] Add JWC to the home page

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-marketing#23]
While I'm not the marketing lead for JWC, I realized, this is OUR conference. It's our once a year official way to connect people with people. It shouldn't be relegated to a tiny mention in the community footer.

If you look at other CMS sites that have annual conferences, they get a prominent spot on the home page. 

Is there ANY way possible to do this to the joomla.org home page? Like, make a new row that has a graphic and some text plugging JWC 2016?

We can sort out how that would look on the NEW home page design once that launches, but for now, it sure would be great to get SOMETHING bigger than a footer mention for JWC on the home page.

**Comment by mbabker** [comment]
In years past there was a banner placed on the homepage.  Should be doable as long as there's a graphic.

**Comment by brianpeat** [comment]
Who would I connect with to get a proper size for it?

**Comment by mbabker** [comment]
All you need is a standard sized banner.  We don't need to go overboard with it.

https://web.archive.org/web/20151007060403/https://www.joomla.org/
https://web.archive.org/web/20141007014252/http://www.joomla.org/

**Comment by brianpeat** [comment]
Ah thanks, seems we DID have them the last 2 years. I'm letting the JWC team know and we'll get a new banner made.
