### ISSUE TITLE
[imagery] Images for "Test Drive" and "Download"

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-marketing#24]
If you go to: https://www.joomla.org/about-joomla.html 

The images at the bottom to test drive and download Joomla! are old-looking.

![oldbuttons](https://cloud.githubusercontent.com/assets/733133/18095579/b487fcca-6ed7-11e6-9bbe-0256e7951154.PNG)

Can we have new fresh images for this?

Thank you

**Comment by mikeveeckmans** [comment]
@jeckodevelopment working on it

**Comment by mikeveeckmans** [comment]
just an idea 
![testdrive](https://cloud.githubusercontent.com/assets/4589318/19151610/e4c65f86-8bcd-11e6-9e68-009e80eec7d0.png)

**Comment by zero-24** [comment]
Much better but why test drive? As it links to demo.joomla.org ;) maybe just "Test Joomla"?

**Comment by beat** [comment]
Just a suggestion:

How about "Try Joomla" (means try before adopting) or "Try and adopt" ?

"Test" means it needs to be tested, and thus might not work. And "Test Drive" is longer and internationally less understood than "Try".

**Comment by Sandra97** [comment]
We have updated this part and removed the out of date pictures. 
I don't think we really need images for this part, but if you want some, then, I'll need 3.

**Comment by Sandra97** [comment]
Sorry, I clicked the wrong button....

**Comment by coolcat-creations** [comment]
I agree @Sandra97. How about just converting the links into buttons like it is on the Frontpage?

**Comment by Sandra97** [comment]
In order to be consistent with all the other internal pages of the website, it's better to not convert the links into buttons here.

**Comment by coolcat-creations** [comment]
fair enough :) If you decide to want an image just let me know. But i agree that it´s not needed there...

**Comment by Sandra97** [comment]
We both agree about not displaying images so I can close this issue.
Re-open if needed.

**Comment by jeckodevelopment** [comment]
Why not a button?

**Comment by Sandra97** [comment]
As said previously, because it will not be consistent with the layout of the rest of the website (the homepage is the landing page, so that's completely different).

**Comment by jeckodevelopment** [comment]
Thanks
