### ISSUE TITLE
Bluehost Platinum Sponsor Logo to Replace Arvixe

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-marketing#27]
Bluehost has taken the place of Arvixe for the Platinum Sponsor package.
https://www.joomla.org/current-sponsors.html

The Capital Team agreed on a new banner size to accommodate existing artwork by Bluehost. I am attaching the banner here.

Please note: we agreed to a 468px wide banner. The supplied banner is larger than this.

To date we do not have new copy for the sponsor page. I will be requesting this today.

Can we swap out the banner artwork with the new logo provided and put this link on the image: https://www.bluehost.com/open-source/joomla

Bluehost has paid for the sponsorship and we should get their logo up as soon as possible.

![bluehost-banner](https://cloud.githubusercontent.com/assets/1197717/19566597/e36e6b56-96b8-11e6-854d-1261a61093a2.jpg)

**Comment by mikeveeckmans** [comment]
@JoeJoomla : you want this one in revive ad server ?

**Comment by JoeJoomla** [comment]
That's a great suggestion Mike.
I'll make a zone for this and send you the code.

**Comment by mikeveeckmans** [comment]
Zone is already created Joe.
Just need to replace the banner, I'll take care of it

Sent from my iPhone

On 20 Oct 2016, at 17:44, JoeJoomla <notifications@github.com<mailto:notifications@github.com>> wrote:


That's a great suggestion Mike.
I'll make a zone for this and send you the code.

-

**Comment by JoeJoomla** [comment]
Hi Mike,
Oops, I just created a campaign, zone and all for it.
If you are in Revive you may want to delete what I just did (Website property, campaign, zone, banner, etc)
I resized the banner to the exact proportions too, 468 x 72.
Sorry to duplicate your efforts.
Joe

**Comment by JoeJoomla** [comment]
One more thing Mike,

Bluehost just sent me a different link for the banner:

https://mailtrack.io/trace/link/77d78fb6ad707f78bb53011dedda4b36365c32f4?url=http%3A%2F%2Fbluehost.com%2Ftrack%2Fjoomlaorg&signature=e46edbe739b0411d

They requested we use the one above please.

Best regards,

Joe Sonne

**Comment by JoeJoomla** [comment]
Hi @mikeveeckmans 

Here's the text for the sponsorship:

"Bluehost is one of the largest and most trusted web hosts, helping millions of people around the world build and manage the site of their dreams. Offering 24/7 support and a myriad of professional services, Bluehost is the premier and comprehensive solution for getting online.

One simple click is all it takes to install Joomla on the Bluehost platform, plus you receive a free domain and $175 in advertising offers. It’s the performance, reliability, functionality, and support you need to perfectly power your Joomla project."

**Comment by mikeveeckmans** [comment]
@JoeJoomla do you want the banner there instead of the logo? 
Already changed the copy and added the logo. 

I need to check with @Sandra97 if you want the banner there.
And the banner that was created in #28 or just the logo?
