### ISSUE TITLE
Downloads Page Sponsor Banner Redesign

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-marketing#28]
Bluehost has requested changes to their banner on the download page:

https://www.joomla.org/download.html

This gives us the opportunity to redesign it to look nicer for the new download page.

The change they are requesting on the banner is:

> can you remove the word preloaded with joomla and use something like "Web Hosting Optimized For Joomla" , also can we use the Sponsor instead of Advertisement? i remember you guys agreed on that.

Thanks and best regards,

Joe Sonne

**Comment by Sandra97** [comment]
Would be nice if we can have the new design before the launch of the Downloads portal. ;)
Thank you!

**Comment by coolcat-creations** [comment]
👍

**Comment by coolcat-creations** [comment]
![bluehost_banner](https://cloud.githubusercontent.com/assets/828371/19770510/d40739e8-9c5f-11e6-8a38-614713d72069.jpg)

**Comment by JoeJoomla** [comment]
Thank you!

I will send this to the client for an approval.

Best regards,

Joe Sonne

**Comment by JoeJoomla** [comment]
@coolcat-creations Bluehost loves the banner. They are eager for it to be up on the downloads page now. 👍

**Comment by mikeveeckmans** [comment]
I'll put it in revive

Sent from my iPhone

On 27 Oct 2016, at 20:27, JoeJoomla <notifications@github.com<mailto:notifications@github.com>> wrote:


@coolcat-creations<https://github.com/coolcat-creations> Bluehost loves the banner. They are eager for it to be up on the downloads page now. ?

-

**Comment by mikeveeckmans** [comment]
@JoeJoomla Does the link needs changing as well ?

**Comment by mikeveeckmans** [comment]
@Sandra97 new banner already added to the zone, and active. 
Only need confirmation from @JoeJoomla  on the link.
Thank you @coolcat-creations for the banner.

**Comment by Sandra97** [comment]
I confirm the new banner is displayed on org and Downloads.

**Comment by mikeveeckmans** [comment]
@JoeJoomla never mind ;-) already got the answer from #27
