### ISSUE TITLE
[imagery] Replacement JSST badge

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-marketing#29]
Please create a new badge to replace [this JSST badge](https://developer.joomla.org/images/jsst_logo_125x125.jpg)

**Comment by Sandra97** [comment]
@coolcat-creations, @mikeveeckmans, could you provide a new badge? Thanks

**Comment by coolcat-creations** [comment]
yes! i´ll apply it to the other new badges.

**Comment by coolcat-creations** [comment]
![jsst_logo_joomla_horizontal](https://cloud.githubusercontent.com/assets/828371/20259989/edb4b644-aa57-11e6-9bdc-1a1d11faefd6.png)
![jsst_logo_joomla_squared](https://cloud.githubusercontent.com/assets/828371/20259988/edb29c24-aa57-11e6-9a80-678edef3b6d6.png)

These would be the logos and they have the same design like the other new conditional logos.

**Comment by Sandra97** [comment]
Thanks @coolcat-creations! 
Badge integrated.
Closing this issue. 
Re-open if needed.
