### ISSUE TITLE
Just testing

### ISSUE THREAD

**Issue by cpaschen** [joomla/joomla-marketing#30]
Just testing to see if the issues area works and what access I have.

**Comment by MATsxm** [comment]
what do you wanna do?

**Comment by cpaschen** [comment]
Just seeing how we might want to use Github more in managing Marketing Team stuff.

**Comment by cpaschen** [comment]
But I see I don't have access to create anything other than issues. (not projects, milestones, etc.)

**Comment by MATsxm** [comment]
@jeckodevelopment could you take a look please... even if I stay skeptical about the usefulness of these features for such topic... 😝

**Comment by cpaschen** [comment]
Yes, I'm skeptical too, but want to make sure I pursue all available options for our team needs.

**Comment by jeckodevelopment** [comment]
@cpaschen what kind of permission do you need?

**Comment by MATsxm** [comment]
Thanks Luca @jeckodevelopment 
(as long as I can use my Emoji 🚽 👅 😉 )

**Comment by cpaschen** [comment]
Possible to get permission to Projects/Milestones/Labels and to assign people to projects?

**Comment by jeckodevelopment** [comment]
well, you have an invitation now. Please accept it.

**Comment by cpaschen** [comment]
Thanks.
I'll check it out over the next few days to see IF this will do what we need for the Marketing Team.
Thanks!
