### ISSUE TITLE
[event] HostingCon 2017

### ISSUE THREAD

**Issue by mdemop** [joomla/joomla-marketing#32]
@cpaschen We spoke about this below but wanted to put in as a ticket.

- Need 1500 Swag Items for Joomla Booth, Those Screen Protectors Should Work Fine.

- Help with the social posts and banner ads as required by HostingCon contract for comp booth.

- Help provide up to 5 videos and up to 15 PDFs for different target markets (Hosts, users, SASS companies) so that we can include in media kit.

**Comment by mdemop** [comment]
@JoeJoomla Already took care of the banner ads, FYI.

**Comment by Sandra97** [comment]
@mdemop On this page http://global.hostingcon.com/hcg17/Public/eBooth.aspx?IndexInList=21&FromPage=Exhibitors.aspx&ParentBoothID=&ListByBooth=true&BoothID=1276744, would it be possible to change the number of downloads? We're over 79 millions, not 60. And the logo displayed has strange colors..

**Comment by mdemop** [comment]
Can someone get me a vector logo and high res PNG to send them? Also should
be able to update that text.

**Comment by Sandra97** [comment]
Here's the folder for the offical logos: https://drive.google.com/drive/u/1/folders/0B-WMsfRg_wivSV83SzZzZ2tRM2M

**Comment by mdemop** [comment]
@Sandra97 I updated the text (but had to cut it since they only allowed 500 characters (this was copied from last year so was fine until we touched it)). I also uploaded the logo but it is small. These are the specs if you want to provide new art: "Company Logo/Image (gif,jpeg or png, less than 30KB and not exceeding 250 W x 120 H pixels)."

**Comment by Sandra97** [comment]
I'll provide you the logo at the right size

**Comment by Sandra97** [comment]
Here are the Horizontal and Vertical logos (I think the display of the horizontal one is better as bigger)
![horizontal-logo](https://cloud.githubusercontent.com/assets/4682328/22331338/4ece472e-e3a1-11e6-875e-b79d9168860a.png)
![vertical-logo](https://cloud.githubusercontent.com/assets/4682328/22331343/50f34522-e3a1-11e6-91d0-9d69196fb370.png)

**Comment by mdemop** [comment]
I just uploaded the horizontal one and is still tiny. maybe send me just the brand mark?

**Comment by Sandra97** [comment]
Here it is
![joomla-brandmark-flat-rgb](https://cloud.githubusercontent.com/assets/4682328/22331739/658098a8-e3a3-11e6-9c5d-6cb9263f5ac1.png)

**Comment by mdemop** [comment]
Please work with Robert Jacobi to finish this. We still owe social posts to cover our legal contract. However, Robert also needs those PDFs and/or videos for the badge scanners. In addition they offered free press support for exhibitors:

- https://www.imillerpr.com/landing-page/hostingcon-press-opportunities-for-sponsors-and-attendees

- https://www.imillerpr.com/landing-page/submit-a-press-release-hostingcon

- https://www.imillerpr.com/landing-page/hostingcon-press-opportunities-for-sponsors-and-attendees

Greetings,
 
HostingCon 2017, scheduled April 3-6, 2017 at the LA Convention Center, will feature a Press Room, providing HostingCon sponsors, speakers and exhibitors with multiple opportunities to engage and interact with leading media organizations from around the country.

iMiller Public Relations (iMPR) is managing the press room, located at the LA Convention Center, Room #512. iMPR will accept press kits and press releases during the conference on your behalf, as well as to provide general assistance to you during the event. In addition, we have created a landing page for your company to submit press releases electronically. We will be accepting EMBARGO press releases and all materials will be made available to the media.  

HostingCon 2017 offers multiple ways to tell your company's story in the press, you can:

Directly request an interview with a media outlet
·         The attending press are available for direct outreach via this link
Submit embargo press releases, day-of announcements and press kits to the media
·         Companies can go directly to the following website to upload information electronically along with a cover letter and specific information to be shared with the attending press via this link
 
Location and Sign-up

• A number of press organizations have already registered for HostingCon 2017. To view the current list of attending media, go to this link.
• The press room will be located in Room 512 at the LA Convention Center. This area can be used to schedule 1:1 meetings
• To be sure you don’t miss any key presentations, please review the HostingCon 2017 online agenda when submitting interview requests to ensure there is no overlap.  

Hours of operation for the press room in the Press Room are as follows:

        Monday, April 3, 2017                 12 p.m. to 5 p.m.
        Tuesday, April 4,, 2017               9 a.m. to 4 p.m. 
        Wednesday, April 5, 2017           9 a.m. to 4 p.m.  

Submitting Information to the Media
Electronic press release submissions are being accepted until 11:59pm EST April 1. After April 1, press releases may be dropped off on site to the press room. Before April 1, you may upload your release electronically to this link.
 
All press releases must be submitted in word format and an exact publication day/time must be cited. Head shots and graphics should be in JPEG format with a minimum of 300 dpi resolution. All embargoes will be honored. To ensure your press release is distributed to all attending media and printed for distribution onsite, please be sure to upload them directly here.

If you would like to submit a press kit, you may choose to follow these guidelines: What Is a Press Kit? Simply upload it as you would a press release here.

If you have any questions, please contact HostingCon@imillerpr.com and one of our  team members will assist you.

Regards,
 
The iMiller Public Relations team on behalf of HostingCon 2017

**Comment by mdemop** [comment]
HostingCon Marketing Webinar: https://www.imillerpr.com/wp-content/uploads/2017/03/Leveraging-PR-Marketing-Initiatives-Before-Events-to-Maximize-ROI-at-Data-Center-World-and-HostingCon-20170320-1510-1-1.mp4

**Comment by cpaschen** [comment]
Mike,
I'm trying to get the press release out the door, but I want to make sure that we 'aim' this in a direction that will play well against the Hosting Con crowd. Can you tell me which topic you think would get the best traction for Hosting Con?
- New Joomla! leadership and board structure (esp. president)
- New 3.7 release
- 80 mil downloads
- (or some other major event in Joomla! life)

We can only focus on one of these in a press release so I'd like to make sure we're hitting a hot-button for this crowd if possible. And I'm guessing/hoping that you know this group better than I do from just reading their stuff.

**Comment by mdemop** [comment]
@cpaschen IMHO I would think 80 million downloads OR do a general "Joomla is stronger then every" with a few points. It is important o note that we need to upload the press release into HostingCon system and have it hit via our wire system on same date DURING hosting con (not prior). Info on how to upload into hostingcon system is above. Once it is in that system with a embargo date, then we should contact media in attendance and setup interviews with Robert.

**Comment by cpaschen** [comment]
A 'general' press release usually doesn't get much 'traction' with media agencies. They want/need one specific topic to talk about.
We don't presently have marketing staff to handle contacting media outlets and setting up interviews. We're probably quite a ways away from being that 'organized' (but some day we should be).
We are planning to release this through PR Newswire also. We can set the release date for the same time as the HostingCon release.
And I'm guessing we should set that date in consultation with Robert Jacobi (and I think I'll also get his input on what 'talking points' he is hoping to promote when he is there - and possibly use that for content).
I'll update this ticket as soon as I hear back from him on those topics and have a date and direction.

**Comment by mdemop** [comment]
As long as date and time is the same that is what is important and what they require. Robert should also be the Media contact I think for the release. HostingCon lists the media in attendence: https://www.imillerpr.com/landing-page/hostingcon-press-opportunities-for-sponsors-and-attendees

in looking at the list seems a dozen or so emails could get the trick done, but you can talk with Robert about that.

Also please ask robert about the PDFs he needs to load into the scanners.

**Comment by cpaschen** [comment]
I'm planning for an April 3 release at this point (which is the first day of the event).
Mike - let me know if there is any reason to NOT release on the first day (like if that day gets filled with everyone else's release - so delaying a day has less 'competition' for eyes).

Also, the 'media' contact for the release will list Robert's direct (cjo) contact information so that media can contact him directly to request a meet-up.
(The media contact for general release (via PR Newswire) will be the general marketing contact info). I will personally be monitoring any responses that come in and then either I will connect with those media outlets or I'll route them to others (Robert - if the media are at HostingCon, etc.).

**Comment by mdemop** [comment]
I think first day is fine, Maybe right when the press room opens:

 Monday, April 3, 2017                 12 p.m. to 5 p.m.

This is the first year they are doing this so we don't know which is best. I would also list Robert cell on the HostingCon release.

**Comment by cpaschen** [comment]
yes, we'll have Robert's phone listed as one of his contact means.

**Comment by ArcTechnologyGroupJacobi** [comment]
The Press Releases have been submitted to hostingcon and pr newswire. Please do not submit anything additional.

**Comment by Sandra97** [comment]
As HostingCon has already started and all is now as ok as possible, I'm closing this issue.
Re-open if needed
