### ISSUE TITLE
[other] US Joomla Booth Kit Repair

### ISSUE THREAD

**Issue by mdemop** [joomla/joomla-marketing#33]
Since JoomlaDay Flordia 2016 got the booth it has been missing the middle support bar. please let me know who and how to buy a replacement and I will put with the kit. In addition if you can get me cleaning directions I want to send in for cleaning before HostingCon 2017.

**Comment by jayblaq** [comment]
I believe the middle bar was not included at JoomlaDay Florida - It came to us for SunshinePHP.  I am unsure when it went missing.

**Comment by mdemop** [comment]
@cpaschen Replacement part delivered today, please close issue.

**Comment by cpaschen** [comment]
Thanks for the update
