### ISSUE TITLE
[imagery] New Twitter Card

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#34]
Further to the update of joomla.org hero part, would be nice to have a new design for the Twitter Card

Here is the current one:
![a14b8110-0fee-11e6-89eb-0e1b1c492a8c](https://cloud.githubusercontent.com/assets/4682328/22607486/7c39b390-ea2e-11e6-96a4-665b1ec5c9d1.jpg)

Here is the type of card we're using on org properties:
https://dev.twitter.com/cards/types/summary-large-image

Dimensions: at least 280 px by at least 150 px
Aspect ratio: 1.867:1
Less than 1MB.

@liliespinosa, I need your talent!

**Comment by Sandra97** [comment]
Here is some suggestions (but Lili has far better ideas tham me)
Size: 747x400px
![1](https://cloud.githubusercontent.com/assets/4682328/22618424/392af378-eab2-11e6-8e6d-6d11062471d3.png)
![2](https://cloud.githubusercontent.com/assets/4682328/22618425/3930b59c-eab2-11e6-8a22-572f39cae847.png)

**Comment by tonypartridge** [comment]
I like 2. Looks like a good replacement to the current one.

**Comment by Sandra97** [comment]
I like the 1st one but it's a bit too dark, and not enough "punchy".
I'm not a big fan of the 2nd one, it's a bit too simple. 
But it's maybe just me.

**Comment by tonypartridge** [comment]
@Sandra97 do you have the original images? we could then lighten up the shadow on the first?

**Comment by Sandra97** [comment]
I don't have the orginal file, I have this one: 
![header](https://cloud.githubusercontent.com/assets/4682328/24080611/8e201b2c-0c79-11e7-87c8-c0e3e2494c04.jpg)
But I'm sure I can get have the source file

**Comment by tonypartridge** [comment]
Perfect :-)
![jomla-twitter-card](https://cloud.githubusercontent.com/assets/1400982/24080647/c62801fc-0c9b-11e7-8972-ba33a17225bd.png)

**Comment by Sandra97** [comment]
Better like that! I'll try to test it to be sure the display is ok on Twitter.

**Comment by Sandra97** [comment]
@tonypartridge Could you also add your psd file in the Drive? 
https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8SDNMMW5sSm5rYXM

**Comment by tonypartridge** [comment]
Sure, just requested access from admin at xws.im

**Comment by Sandra97** [comment]
Access granted

**Comment by tonypartridge** [comment]
PSD Image uploaded :-)

**Comment by Sandra97** [comment]
Thanks Tony!

**Comment by Sandra97** [comment]
Display of the new Twitter Card tested. It's ok on my computer, tablet and phone
![index](https://cloud.githubusercontent.com/assets/4682328/24081575/4cc8f330-0c95-11e7-906d-f6e769bbae62.png)

Maybe we should also create a new visual for Facebook?
Here is the current one: https://cdn.joomla.org/images/joomla-org-og.jpg

**Comment by tonypartridge** [comment]
The same image could be used for facebook header. And a different one for the profile photo?

Close this if you are happy with the result for twitter it looks good to me. Then open one re Facebook :-)

**Comment by Sandra97** [comment]
I won't close this one yet. I don't want to decide by myself. I need more people to confirm if they are ok or not with your picture.
I'm gonna open a task for the other one.

**Comment by MATsxm** [comment]
just ping :stuck_out_tongue_closed_eyes: 
+1

**Comment by Joomv** [comment]
+1

**Comment by yvesh** [comment]
+1 - Thank you @tonypartridge - our new design boy (ping him for more images)

**Comment by tonypartridge** [comment]
Btw, I'm crap at designs but ok at hacking stuck together.

**Comment by yvesh** [comment]
You have time to practice :-) And see everyone is happy with your first work

**Comment by Sandra97** [comment]
Twitter card is ready. Will be implemented soon.
Closing this issue.
