### ISSUE TITLE
[Imagery] 3.7 Release on joomla.org

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#35]
We will need a graphic to announce the 3.7 Release + the landing page. 
It will be display at the right of the announcements part on joomla.org homepage when 3.7 stable will be released.

- Dimensions: 750x525px
- Deadline: 25 March 2017

@liliespinosa I need your talent (again)!

**Comment by liliespinosa** [comment]
Done! 
https://drive.google.com/open?id=0B9Wt6WtQbUobcWZKTzI0Um1mbDA

**Comment by Sandra97** [comment]
Thank you Lili!
