### ISSUE TITLE
[Imagery] 2017 Template

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#38]
https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8eVNwak5GV1N1VGM

The new layouts for imagery on our property blogposts (BlogPost-Templates-2017-2.psd) have been approved by the Marketing Team, Social Media Team and Department Coordinator. 
Small edits  can be seen in the file EDITS-SandraforLily.psd

Using the same layouts, could you please create them also for:
- Instagram 1080 x 1080
- Facebook 1200x630
- Twitter 1024x512

Thank you!

**Comment by liliespinosa** [comment]
Hi Sandra!
Here are the three PSD files :) 
https://drive.google.com/open?id=0B9Wt6WtQbUobV3NkMkRJM3NzV2c

**Comment by Sandra97** [comment]
Thank you Lili!
