### ISSUE TITLE
[copywriting] 80 millions downloads blogpost

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#39]
Should be nice to prepare a blogpost to publish on jorg when this milestone is reached (with other key numbers/elements)

Thank you!

**Comment by cpaschen** [comment]
@parthlawate Are you handling this?

**Comment by cpaschen** [comment]
Sorry to 'beat a dead horse', but I think the purpose is to draw attention to the popularity of Joomla! We need to get something out that will get shared and re-tweeted. The best way to do that is with an 'engaging' graphic. And this one seems to lend itself to info-graphic.
Do we have anyone who has any experience in creating info-graphics?
(You can do basic ones with Canva that look decent).

**Comment by parthlawate** [comment]
I'm on this... I agree an infographic would be nice.. Let me put it on the Design group and see if we can get someone to help

**Comment by siddharthkabra** [comment]
Hi,

Have a look at what I could come up with till now. @parthlawate as discussed, eye-catching, easy to read and highlights the best of joomla! 
![infographic](https://cloud.githubusercontent.com/assets/25842720/23540684/ceb4513a-0008-11e7-8b80-dbe4e3d4c8e5.jpg)

**Comment by parthlawate** [comment]
The stats about docs.. Its not very clear its about docs itself.. We might want to say 2000+ contributors instead of registered users.. but that might not be true.. It might need to be more clear that the section is about docs.. and not overall Joomla..  

By the way the Joomla forum page has some nice numbers at the bottom.. 

Total posts 3117245 • Total topics 745650 • Total members 698645 https://forum.joomla.org/

@Sandra97 @cpaschen any comments ?

**Comment by zero-24** [comment]
Where is the launch a new version every 36 days sentence come from?

**Comment by franz-wohlkoenig** [comment]
- What means Numbers in "Built with Joomla!"-Section: Thousands, Millions "Canada 3355"?
- Also should named "Joomla!" than "Joomla"

**Comment by ot2sen** [comment]
It does look like that the documentation section is missing a larger title below the graphics as the other sections have. Therefore it is not clear that those stats are about documentation.

For typos and wording it would be a good idea to have a native speaker review when a final draft is ready. Can see some adjustments needed with non native eyes :)

**Comment by Sandra97** [comment]
Goog morning all, 

My 2 cents... (I'm sure you were waiting for them ;) )

- Please  add everywhere where compulsory the bang (!) to Joomla! (and always capitalise Joomla)
- In the timeline, shouldn’t it be X million'S'?
- Maybe a good idea to add 2005. Birth of Joomla! (or another word but it allows to have a starting point)
- I don’t understand a new version every 36 days? 
- For the extensions, please mention it’s about the JED. We have fare mor extensions for Joomla, as templates are an extension but are not present in JED
- It’s 'its' documentation not ‘it’s’. And maybe better to mention ‘its official documentation site’. And for the related numbers better to mention 7000+ pages, 2,900+ registered users (unfortunately, it's not contributors), and I don’t think the number of uploads is interesting, maybe better to mention the numbers of edits 500,000+
- Please remove the part build with Joomla, these 3 sites are using Drupal, not with Joomla. Maybe replace this part by something about the Showcase site?
- You  should see to add the number of language packages (it's a big strengh), the number of contributors/commits on GitHub, the number of posts on the forum (like mentioned by Parth)…
And maybe other things, but I need a coffee first, it's not yet 6am here ;)

**Comment by parthlawate** [comment]
Noted will close max by tomorrow ..

**Comment by franz-wohlkoenig** [comment]
@Sandra97 is there a live-counter i missed?

**Comment by mbabker** [comment]
It comes out of the downloads site API.  Or the backend if you've got access.

https://downloads.joomla.org/api/v1/downloads/cms

**Comment by franz-wohlkoenig** [comment]
@mbabker Thanks for Link. Would be nice to have a Page similar https://developer.joomla.org/about/stats.html

**Comment by Sandra97** [comment]
We already have a counter on the Downloads Homepage (in millions). Not sure we need one elsewhere with the exact number. It would be just a kind of gadget IMHO.

**Comment by franz-wohlkoenig** [comment]
Thats true Playmobile for old Man, i like stats and Numbers.

**Comment by parthlawate** [comment]
Article started here https://docs.google.com/a/community.joomla.org/document/d/1CnGBycjTfFY5-EN1EzJlsvg7KftFpfNMYdJ00UnD_jE/edit?usp=drivesdk

**Comment by mbabker** [comment]
The whole point of having the API was to enable people to grab the data or make their own widgets as desired.  That's actually how the stats page works too (it just read's the server's public API and makes it look pretty).

It's in the roadmap to one day do some frontend stats.  But for me that's lowest priority, we've still got hundreds of language packages and 60 translation teams to move onto the site.

**Comment by Sandra97** [comment]
@parthlawate, some more ideas for the key numbers to add to the infographic:

- Volunteers on the portal: 833
- User groups: 177 
- GitHub commits for the CMS: over 28,000

Also, when the infographic is ready, please provide the source file so that we can update it when needed.

**Comment by parthlawate** [comment]
@siddharthkabra @baruahr Please note updated stats. This is super urgent now as we are almost at 80 Million !

**Comment by siddharthkabra** [comment]
Yes. Will upload a version in 30 minutes.

Siddharth.

**Comment by siddharthkabra** [comment]
![joomla-infographics-03](https://cloud.githubusercontent.com/assets/25842720/23745060/dcf35cf4-04dc-11e7-8c6f-8ddea6295013.jpg)

**Comment by siddharthkabra** [comment]
@Sandra97 @parthlawate

**Comment by Sandra97** [comment]
@siddharthkabra 
My 2 cents:
- Timeline: it would be better to start by 2005 with the "birth of Joomla", I would remove 2011 as well as the "1 million monthly"
- Remove the "updated every 36 days" and you could replace it by "156 releases since 2005"
- With the 7.1%, you can add that Joomla! is powering over 2,4 million websites
- What are the numbers displayed on the map? The map is nice, but people won't understand what is the meaning of these numbers.

Thank you!

**Comment by franz-wohlkoenig** [comment]
- looks like 80 Mio. Downloads where at 2015 ("Joomla! turns 10") cause Timeline ends not 2017
- what are the Numbers below "Canada" and other Countries?

**Comment by siddharthkabra** [comment]
![joomla-infographics-05](https://cloud.githubusercontent.com/assets/25842720/23750289/3f031730-04f2-11e7-8e75-231e2440195b.jpg)

**Comment by mikeveeckmans** [comment]
Sorry to bug in, but not convinced on the documentation part ... 7000+ content pages indeed, but it's not clear it's about the documentation (docs.joomla.org) it comes after 156 releases and the text above which actually tells you it's about docs is so small that people will not read it properly... #IMHO , and now i'm gone again , cheers ;-)

**Comment by siddharthkabra** [comment]
btw, the numbers below the countries are the number of businesses using Joomla! in that country. Just thought that the global spread might be a nice thing to have.

**Comment by mikeveeckmans** [comment]
One last thing : all sources look good to me , but why put joomplace (an extension provider) on there as well? that's asking for troubles with others...

**Comment by franz-wohlkoenig** [comment]
👍 looks now clear.

**Comment by siddharthkabra** [comment]
![joomla infographics-0 7-01-01](https://cloud.githubusercontent.com/assets/25842720/23784758/dc743ffc-0589-11e7-9a13-6800eda1b98f.jpg)
finalised announcement. Can someone guide me to a place where I can upload the open file?

**Comment by Sandra97** [comment]
Thanks Siddharth!

2 little things to edit:
- For docs: it's docs.joomla.org not .com
- The Joomla! Forum: please capitalise "Forum"

For the source file, you can download it here: 
https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8VFRIVGEyWXp4bDQ

Thank you!

**Comment by parthlawate** [comment]
Looking fantastic @siddharthkabra ! Thank you for you help :) :100:

**Comment by siddharthkabra** [comment]
thanks @parthlawate here's the updated one:

![joomla infographics-0 8-01](https://cloud.githubusercontent.com/assets/25842720/23786447/270c9c90-0593-11e7-9394-0a8d2e81525d.jpg)

**Comment by Sandra97** [comment]
Thank you Siddharth!!!

**Comment by franz-wohlkoenig** [comment]
"80 Million Downloads in 2017" – as no-native Speaker this reads like "we have 80 Million Downloads in the Year 2017" (in 2+ Months).

**Comment by Sandra97** [comment]
Fully agree with you Frantz.
Better to just remove "in 2017"

**Comment by Sandra97** [comment]
As you have probably noticed, we have reached today 80 million downloads. 

Do I have to mention that I've been asking for this blogpost since January 7th?

As we needed to do something today, I did a picture so that the social team and myself were able to do something.

@cpaschen @parthlawate Please finish the blogpost.
@siddharthkabra Could you please upload the source file in the Google folder (I gave you the link this morning)
I would like to be able to post it on Monday 13th March 2017. If published later, it doesn't make sense anymore.

**Comment by siddharthkabra** [comment]
Here's the source file
https://drive.google.com/open?id=0BwhC9FZgIkmZRDNkR0gwT1B3czg

**Comment by Sandra97** [comment]
Thank you @siddharthkabra

**Comment by brianteeman** [comment]
I know its too late but for historical reference it is not 80 million downloads. we passed that some unknown time ago. At some point in the dim and distant past when we switched from one download location to another (2006 i believe) the count was reset to zero :)

**Comment by Sandra97** [comment]
Thanks for the information Brian. And in fact it's impossible to have an accurate number, as for example we don't know the numbers of download on joomla.fr, the number of donwload of quickstarts at template clubs.

Anyway, it hasn't been possible to publish the blogpost in time (despite my numerous requests to have something ready in time), and I have too many questions without answers regarding the infographic. So I had unfortunately to use my plan B: a post on our social media channels only last week. 
And I'm not happy with that but let's say it's better than nothing.

**Comment by MATsxm** [comment]
and the infographic is not yet published... wait to see the mess and comments you will have...
Infographics are the best way to give the stick to be beaten with
lesson learnt? not sure...

**Comment by Sandra97** [comment]
Closing this issue.
I should stop dreaming we can do things in time and in the right way.

**Comment by franz-wohlkoenig** [comment]
@Sandra97 whats the Reason for not in time and right way?

**Comment by Sandra97** [comment]
Not in time because I'm asking for it since January 7th, so it should have been ready last Friday. And because I can't get a confirmation if we are allowed or not to use the icons of the infographic, because I don't know from where some numbers are coming and can't get cofirmation, because some sources are incorrect.  And better if I stop here my list ;) 
I can't publish something if I have doubts and if it can result in an embarassement for the Project.

**Comment by franz-wohlkoenig** [comment]
my knowledge how Community works is less. If you need help and i can, i do.

**Comment by Sandra97** [comment]
Yes I need help! I'll contact you on Glip to talk with you

**Comment by siddharthkabra** [comment]
@Sandra97 sorry couldn't respond earlier. had to travel out of town on something. I thought the open files could suffice for any further changes at your end. The icons used are from a free source and have been modified enough. To be on the safer side, we can include an acknowledgement to the source (that's what they ask for). Let me know if we need to continue on this. Again, apologies could not respond earlier. hopefully, I can get all the requirements beforehand so that there are no gaps.

**Comment by Sandra97** [comment]
@siddharthkabra, you don't have to apologise, you can't know everything at your first contribution. And you should have had over 2 months to create the infographic. It's a pitty that it took one month just to decide to do an infographic instead of a blogpost.

**Comment by Sandra97** [comment]
Let's re-open this issue.

It has been discussed and agreed to publish this in the next JCM edition, with some edits discussed in the marketing room. 

@siddharthkabra Here is the list of edits for the infographic:
https://docs.google.com/document/d/10t3DTLVrzaG57aWw9W-OYmQ385-CeGfiMG-ey1Y8E1Y/edit#

Thank you!

**Comment by brianteeman** [comment]
>  we can include an acknowledgement to the source (that's what they ask for).

If thats what they ask for then they should be provided

**Comment by Sandra97** [comment]
For information, here is the Terms of Use for the vectors.
http://www.freepik.com/terms_of_use
Sorry, I really don't have time now to read them carefully

**Comment by brianteeman** [comment]
The license of the Content in the FreePik Selection shall be free provided that any use of the Content in the FreePik Selection by the User **is credited to FreePik** as stated by FreePik from time to time. For any use of the Content in the FreePik Selection **without the credit to FreePik, the User must purchase a subscription** (hereinafter, the “Subscription”) in the Website and download the Content in the FreePik Selection during the term of any such Subscription. Conditions in Section 8 shall apply to the purchase of the Subscription.

**Comment by siddharthkabra** [comment]
@parthlawate @Sandra97 ![joomla infographics_21-03-2017- 04 -01-01](https://cloud.githubusercontent.com/assets/25842720/24136548/549a0288-0e35-11e7-8a33-c20a447b8b0e.jpg)

**Comment by Sandra97** [comment]
@siddharthkabra Thank you!!! It's better like that

Last things:
- On the infographic, there's no elements coming for the dev page mentioned in the sources. But there are elements coming from other of our properties. So instead of mentioning a long list of Joomla! sites, maybe better to just mention joomla.org?
- I still don't know from where is coming the number of GitHub contributors. Can you (or anyone) tell me where you find it?
- Regarding the number of volunteers, I think it would be better to mention 800+ instead of 833, same for the number of user groups, would be better to mention 170+ instead of 177 

Thank you!

**Comment by siddharthkabra** [comment]
@Sandra97 Can't find the 1700 contributors source.. @parthlawate do you remember? If not, lets just remove it?

**Comment by parthlawate** [comment]
@mbabker @wilsonge What's the source of truth to find number of contributors ever to Joomla ?

**Comment by Sandra97** [comment]
@siddharthkabra Could you please put your edited ai file in the Google Drive folder so that I can close this issue?
Thank you.

**Comment by ufuk-avcu** [comment]
@siddharthkabra is there any chance to get the source file? Please can we concentrate on the blogpost. It should be doable.

**Comment by siddharthkabra** [comment]
@ufuk-avcu @Sandra97 here's the link to the editable file: https://drive.google.com/open?id=0BwhC9FZgIkmZNkQ3emZ3SFNTQ2c

**Comment by ufuk-avcu** [comment]
@parthlawate  and i decide today, that the 80 million post comes to late. We open an another issue for the infogrpahic here: https://github.com/joomla/joomla-marketing/issues/62
