### ISSUE TITLE
[event] Joomla Promotional Materials

### ISSUE THREAD

**Issue by puneet0191** [joomla/joomla-marketing#4]
I wanted to ask about Joomla Stickers and Promotional material for Joomla Day India event on August 28th 2016. Is it possible we could distribute some during the event, also what is the procedure to get them shipped?

**Comment by mikeveeckmans** [comment]
Hi @puneet0191 ,
We will check the according budget line and will get back to you. 
Could you give me a number of attendees? 
What other "promotional material" did you have in mind? 

Thanks

**Comment by parthlawate** [comment]
Some ideas -  
Fridge Magnets
Pinup Badges (We had those at JWC and they were a big Hit) 
Stickers
template for a Joomla Day Tshirt ? Not sure if we want to templatize that

@mikeveeckmans as per my knowledge - attendees will be between 125-150. I think we could help with the design and the Printing/creation can be done locally. That will be way cheaper.

**Comment by puneet0191** [comment]
@mikeveeckmans as @parthlawate mentioned, expected number is 150 max. Apart from Stickers, I also had Pinup Badges, Fridge Magnets in mind.

**Comment by mikeveeckmans** [comment]
@parthlawate @puneet0191 Thank you. As soon as we have a clear budget, i'll get back you.

**Comment by amitkumarj441** [comment]
Hey @puneet0191 ,

I'm new to Joomla and recently I started contributing to Joomla-pythagoras, currently Niels Braczek is mentoring me! I haven't attended any Joomla event till now and I would like to participate into this event. Please let me know how to participate into this event.
Looking forward to join your team!

Cheers,
Amit Kumar Jaiswal

**Comment by DanaIdzik** [comment]
Hello guys :) We would love to take every possible promotional material which you can share :))) we expect 200 attendes this year :) lets stay in contact :)

**Comment by amitkumarj441** [comment]
Hi @DanaIdzik ,

Please let me know where're you organizing the event! I would like to participate into this event! Please do share me the link.

Cheers,
Amit Kumar Jaiswal

**Comment by DanaIdzik** [comment]
@amitkumarj441 hi :) 
Of course, our JoomlaDay is in Poland, in Gliwice..  Here is the map:
http://www.joomla-day.pl/lokalizacja
Our website is fresh so still in Polish :) we will make english parts soon as possible

**Comment by mikeveeckmans** [comment]
@DanaIdzik please start a new topic/issue for Jday Poland. 
@amitkumarj441 : please contact @puneet0191  directly so that these topipcs can stay on topic. 
Thank you.

**Comment by puneet0191** [comment]
@mikeveeckmans Any update on this request?

**Comment by mikeveeckmans** [comment]
@puneet0191 no sorry, still awaiting budget approval from OSM before i can make a commitment

**Comment by mikeveeckmans** [comment]
@puneet0191 sorry we couldn't do anything. Just got budget yesterday.

**Comment by puneet0191** [comment]
I understand Mike :+1:  thanks
