### ISSUE TITLE
[copywriting] Teasing article for 3.7

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#40]
Would be nice to have asap a teasing article about 3.7. 
It seems many people are not aware of the new features as well as the release date (even if these infromation are of course already publicly available)
If not possible, teasing campaign will be only on Social Media (already started - four more to come, images already done)

**Comment by cpaschen** [comment]
I've written a VERY short teaser blog post:
https://docs.google.com/document/d/1b11lkNGBoocyyQ70S3gCiLi-yMZwqcDP4E21LmIHFG0/edit#

Please review/edit/rip apart!

**Comment by Sandra97** [comment]
Another version can be found here:
https://docs.google.com/document/d/1CUJSgnW1WZvLI7-1Xsm5ev9A_1Ag7DGhlXaOiK6iQEA/edit

@cpaschen Thanks to tell me when it's ok, and when I can publish it on jorg. Thank you!

**Comment by Sandra97** [comment]
FYI, I'll publish Rowan's version on jorg on Monday. We have already waited enough, let's go like that

**Comment by yvesh** [comment]
+1

**Comment by parthlawate** [comment]
It's good to go from me.. my changes and edits are incorporated !

**Comment by Sandra97** [comment]
Closing this task as the blogpost has been published today.
