### ISSUE TITLE
[copywriting] New structure Blogpost 

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#41]
It would be a good idea when transition is ended to write a blogpost to explain a bit the new structure. It appears many users are a bit lost and don't really understand it.

**Comment by Sandra97** [comment]
A really good idea from @roland-d 
"The graphic would be good to be filled with the names of the people who have been voted in"

Link to the graphic: https://community.joomla.org/images/blogs/leadership-blog/joomla_leadership_structure.png

**Comment by Sandra97** [comment]
@cpaschen @parthlawate @pranavlawate Have you started working on it? Could be maybe a good idea to ask Ken and/or TJ for help?

**Comment by parthlawate** [comment]
Have explained to @pranavlawate about the structure and given him content to read up on. A high level idea is kept here https://docs.google.com/document/d/1lApJVLYxYyjDWFnRt0QtFKEIWpuwwa3nqQyZ-kJDmS4/edit But i think we should get help from Ken and TJ for this as they will know it inside out !

**Comment by parthlawate** [comment]
@pranavlawate Any updates on this ? Would be good if you can share any drafts you have !

**Comment by ufuk-avcu** [comment]
After three months we can close this issue for inactivity or is @pranavlawate is actually working on this? If someone is willing to pickup this again, we can reopen this issue.
