### ISSUE TITLE
[copywriting] Beta3 Release post

### ISSUE THREAD

**Issue by cpaschen** [joomla/joomla-marketing#42]
I've created a beta 1 release post here:

https://docs.google.com/document/d/1NSfFXuVcXxOhoc9_ul0kolsmQeaRZIrbmnPTcoax8PM/edit#

To be completely honest, I just took the 3.7 beta 1 and updated it. No need to re-write an entire article for what is a release announcement. There are some things that need to be proofed and possibly updated.

Please review and comment.

**Comment by Sandra97** [comment]
I've modified it to fit well to Beta 3, did a pic and posted it on dev.
