### ISSUE TITLE
[copywriting] joomla.org updates to reflect the new structure

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#43]
I need help to update some pages of jorg:

- https://www.joomla.org/about-joomla/the-project.html
- https://www.joomla.org/mailing-lists.html

Thank you

**Comment by zero-24** [comment]
@Sandra97 can you close than: https://github.com/joomla/joomla-websites/issues/853 ?

**Comment by Sandra97** [comment]
Done!

**Comment by zero-24** [comment]
:+1:

**Comment by Sandra97** [comment]
@parthlawate @pranavlawate @cpaschen Could you help me on this?

**Comment by parthlawate** [comment]
Ideally the blog post and this should go together ? Once copy for the blog is done the same can be used as a basis for this. Overall between the Press release and structure blog posts & content, i think now that structure is done that should get higher priority

**Comment by Sandra97** [comment]
Update: Michael did the work the marketing team was supposed to do and updated the content of the Project page.
Thank you Michael!

**Comment by parthlawate** [comment]
Thank you Michael for picking this up !

**Comment by Joomv** [comment]
Closing this.
