### ISSUE TITLE
[BlogPost] Announcement for 3.7 stable release

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#44]
Thanks to start preparing the announcement for 3.7 stable release which will be published on jorg.

**Comment by pranavlawate** [comment]
@Sandra97 
I've written a first draft for the 3.7 release. 
https://docs.google.com/document/d/1TAsHeCXGOXd79iFKslpOED_uvS57kUcK30YV3LAn-uk/edit?usp=sharing

**Comment by zero-24** [comment]
> standard-term support release

Should we not call it a minor release? As we don't have standard / long and short term releases any more ;)

**Comment by zero-24** [comment]
Can we reopen this until the questions are cleared vs. the poste is published?

**Comment by Sandra97** [comment]
Also, @pranavlawate your blogpost is the jorg announcements for 3.7 stable.
But we need a Press Release that can be used outside our properties, sent to hosting companies, blogs or whatever. So we need a "sexy" article and not a technical one.

**Comment by cpaschen** [comment]
Sandra, can you created a new 'task' for a Press Release for 3.7?

NOTE: A press release is a 'standard' document. There are expected 'structures' and styles. It's not at all like writing other marketing copy and has to be written properly. 
They, by nature, aren't "sexy", but also aren't "technical".

I can give more info/tips in the actual task for this.

We will also need a 'task' for 'releasing' the press release, as it needs to be properly released through the appropriate services (hopefully we have or will have subscriptions to those services by then).

**Comment by Sandra97** [comment]
This Task was for the Press Release not for the announcements like mentioned in my title... But it turned into something else (which is needed too of course)
I'll create rename this one and create a new one

**Comment by Sandra97** [comment]
Closing this issue as we have a blogpost under review by 3.7 marketing team + production.
