### ISSUE TITLE
Youtube update links in the default text to HTTPS

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-marketing#48]
Hi,

there are a great new video about 3.7 can someone fix the links in the default text to HTTPS?

https://www.youtube.com/watch?v=NtwDE5Paxd0

IIRC there is also some defaut text maybe this should also be changed there 😄

**Comment by cpaschen** [comment]
Thanks.
Sandra can you follow-up on this?

**Comment by Sandra97** [comment]
I can't, I don't have access to YouTube (yes, there's an account I don't have access to... because I refused) but don't worry it will be edited

**Comment by Sandra97** [comment]
And the download link is not the right one too. I'll ask for the change

**Comment by Sandra97** [comment]
Links and text edited as many information were really out of date. 
Closing this issue.
Re-open if needed.

**Comment by zero-24** [comment]
Thanks :+1:
