### ISSUE TITLE
[Press Release] 3.7 stable release

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#49]
I think it would be nice to have an official Press Release presenting 3.7. 
It could be published there: [Media Alerts & Press Releases ](https://www.joomla.org/about-joomla/the-project/media-and-press-contact.html
And it could also be sent to some influencers, blogs, hosting companies...

**Comment by parthlawate** [comment]
Have created a starter article here copying from the 3.5 Press release here. https://docs.google.com/document/d/1CZELxTgw3v1MAw6BUim-ZYJ1Sz6ToHd9niORDpnqKhI/edit 

@pranavlawate can you start editing this ? @cpaschen @Mark can you review format ?

**Comment by franz-wohlkoenig** [comment]
@Sandra97 [News](https://www.joomla.org/announcements/release-news/5699-the-next-version-of-joomla-is-just-around-the-corner.html) talkes about "over 700 improvements". What i remember this "700" are born at a Time where 3.7 was sharp under thie Number.

Now 3.7 is at 1000+.

**Comment by mbabker** [comment]
It really depends what you want to call "improvements".  If it's simply based on the commit count, then it's over 1200 last I knew.  Also remember though that a good number of those commits are either test infrastructure related or admin things (code style, version bumps around releases, branch merges, etc.), so that should be factored out of the number.

Maybe 700 stays a fair number to use, maybe not.  I'll leave that for the marketers to decide on 😉

**Comment by Sandra97** [comment]
I know and you're right about the number.
But whatever is the number, talking about "improvements" is not really exact,  as we can't consider for example that correcting a double quote is an imporvement and we can't say Over 1 000 issues fixed, sound really bad
So it's just a "marketing" thing ;)

**Comment by franz-wohlkoenig** [comment]
It's a marketing Thing and its not counting Numbers – right. I was hangig about the "700" as PR-Numbers was <700.

**Comment by Sandra97** [comment]
@cpaschen 

Elements needed in this blogpost:

- Main Features
- Downloads
     - Buttons to Downloads site for full package as well as upgrade packages
     - Link to Technical Requirements https://downloads.joomla.org/technical-requirements
     - Link to New installation instructions https://docs.joomla.org/J3.x:Installing_Joomla
     - Link to Update instructions https://docs.joomla.org/J3.x:Updating_from_an_existing_version
     - Link to the 3.7 FAQ https://docs.joomla.org/Category:Version_3.7_FAQ
- Landing Page https://www.joomla.org/3 (launch on the same day at the stable) - Already available in over 25 languages
- Imagery for our users https://docs.joomla.org/J3.x:Joomla_3.7_Imagery
- Embed Video (video not published yet - available in over 25 languages)
- Thank You Page https://www.joomla.org/3/thank-you
- Help Joomla! development
- What's coming next, link to the roadmap https://developer.joomla.org/roadmap.html

**We'll need this blogpost to be ready for review before Sunday 23 April**.

Thank you!
