### ISSUE TITLE
Brand Manual - Edits

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#50]
As agreed during the London Sprint, please:

- Remode all 'Draft' mentions
- Improve lisibility of the brand manual
- Replace joomla.org/brand by https://tm.joomla.org/
- Replace all links to http://opensourcemattersorg... by https://tm.joomla.org/
- Replace joomla.org/contribute by https://www.joomla.org/contribute-to-joomla.html

Thank you!

**Comment by siddharthkabra** [comment]
Could you point me to the open file (ai) for the brand manual.

**Comment by Sandra97** [comment]
It's an InDesign file. You'll find it here: https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8TTM3bE5va1AweW8
Just ask for access and I'll grant you one.

**Comment by franz-wohlkoenig** [comment]
@Sandra97 if theres is something to layout, i'll do. Using QuarkXPress.

**Comment by Sandra97** [comment]
Thanks Franz for offering your help! 
At this step, it's only small edits of the current layout which are needed. 
But if there's a decision after this 1st mission to change more elements, then I'll contact you.

**Comment by Joomv** [comment]
Please lets not convert to Quark.  Most of our users operate adobe licenses, at least everyone I know who would be editing this moving forward.  Moving this into a Quark file type would render everyone useless.

**Comment by Sandra97** [comment]
I agree with Rowan on this point. Most of us are using InDesign, not Quark. Better use a format used by most.

**Comment by franz-wohlkoenig** [comment]
An Argument like: Better use a CMS use by most.

**Comment by parthlawate** [comment]
@siddharthkabra can you pick this up and close it please ?

**Comment by Sandra97** [comment]
Note that Alison is currently working on it so that it can be done asap.

**Comment by Sandra97** [comment]
We did many edits on the Brand Manual in order to correct typos, non sense, lack of consistency...
We're also removing mentions to the marketing group and email of marketing in order to replace them by mention the Trademark & Licensing Working Group + email of the TM group, as  the Brand Manual is under their team and should not be under marketing team.

**Comment by cpaschen** [comment]
Great thank you from the Marketing team for removing it from our 'to-do' list. I always wondered why it kept coming up in our discussions and not under Trademark.
However, we'll be glad to use it! :-)

**Comment by AlisonAMG** [comment]
[2017_Joomla_Brand_Manual.pdf](https://github.com/joomla/joomla-marketing/files/913656/2017_Joomla_Brand_Manual.pdf)
Hi All
Here is the PDF of the Joomla Brand Manual. With the help of Sandra several corrections were made and since this will be utilized as a PDF we have also incorporated linked from the Table of Contents to the sections and also from the FAQ back to the referring pages. 
The master InDesign file will be placed into the marketing docs area momentarily. 
Have a great day!

**Comment by Sandra97** [comment]
Big thank you Alison!
@jeckodevelopment Could you please check it and tell us if all seems good?
Thanks!

**Comment by AlisonAMG** [comment]
Thank you @Sandra97 two sets of eyes find things better. Glad to help. :)

**Comment by jeckodevelopment** [comment]
will do Sandra, thanks everyone :)

**Comment by jeckodevelopment** [comment]
Looks good.
Awesome job. Thanks

**Comment by Sandra97** [comment]
@jeckodevelopment 
Here's the link to the Drive where you can find the PDF:
https://drive.google.com/file/d/0By_CBGYGBbU8SWg1bUlrUHhRb2M/view?usp=sharing (public)

And source files: 
https://drive.google.com/drive/u/0/folders/0B_QTydv-xNbqWjFFSnhvT3d5QTg (restricted access)

Closing this issue as all is ok now.
Thank you!

**Comment by jeckodevelopment** [comment]
Thank you ;) 
Can you please create a short link for the Brand Manual? 
So i'll put in the TM website.

**Comment by Sandra97** [comment]
Here it is: https://joom.la/JoomlaBrandManual
(Thank you Radek)

**Comment by jeckodevelopment** [comment]
one word: awesome.

Thanks ;)
