### ISSUE TITLE
[copywriting] Call for Designers

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#51]
Hello,

Parth and Elisa worked on a call for a Lead Designer last December. Chris reviewed it in January
https://docs.google.com/document/d/1WKmm4dkTdk234PVHLBWgi1f2DdIW57VvemmbntRD2_c
https://docs.google.com/document/d/11GTm9wMbhLJZLaxsf9MTzJaZFZ3uitciwPyqmm3eDWw

We are in March and nothing has been published.
We desperately need volunteers in all areas of marketing.

Thank you.

**Comment by franz-wohlkoenig** [comment]
thanks @Sandra97 for keeping things alive.

**Comment by parthlawate** [comment]
Thanks @Sandra97  as updated on Glip, a wider call for volunteers and a full campaign around this is planned starting with a JCM article by @cpaschen .. which should be the first priority to go out.. Chris can you do this ? Have edited some of your text and it looks good to me

**Comment by cpaschen** [comment]
That article is posted here:
https://docs.google.com/document/d/1CwhHPUKJI4sLPPfxPqHCK1w7Ol0TwEdOiR62NBwkaeU/edit
(general 'teaser' for volunteer campaign)

We still need to get our onboarding process fixed (we can't just tell people 'go sign-up for glip' ... that is a nightmare to wrap your head around.

But please comment on the article posted here so we can move this ahead.

**Comment by Joomv** [comment]
@cpaschen  Can you open it up to comments for CJO email addresses please?  I get view only

**Comment by cpaschen** [comment]
That article has already been submitted to the JMAG for publishing.
We will follow that up with individual position notices throughout April (after the mag is published).
We're working on a campaign for that process now.

**Comment by parthlawate** [comment]
Closing this since @ufuk-avcu has opened a new issue specifically for call for designers
