### ISSUE TITLE
[Imagery] New Open Graph Image

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#53]
Hello!

Our OG image is currently this one: 
![joomla-org-og](https://cloud.githubusercontent.com/assets/4682328/24081684/16367eb2-0c97-11e7-84dc-fcf4b35f4ce1.jpg)

What about creating a new one in order to have some consistency with our Twitter Card? See #34 

Requirements for the OG image:
- 1200x630px for HR devices
- Minimum 600x315px
- Ratio: 1.91:1

@tonypartridge Could you help with this?

Thank you!

**Comment by Sandra97** [comment]
Google Drive for the source file when approved: https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8SDNMMW5sSm5rYXM

**Comment by parthlawate** [comment]
checking if @siddharthkabra can pick this up ?

**Comment by siddharthkabra** [comment]
Created a few variants..

![joomla visual design_ 03-04-2017_jpgs-04](https://cloud.githubusercontent.com/assets/25842720/24608545/99d36088-1894-11e7-9e77-906dbd19462f.jpg)
![joomla visual design_ 03-04-2017_jpgs-05](https://cloud.githubusercontent.com/assets/25842720/24608548/9b000ec0-1894-11e7-99fb-608648516779.jpg)
![joomla visual design_ 03-04-2017_jpgs-06](https://cloud.githubusercontent.com/assets/25842720/24608550/9c66c772-1894-11e7-85ad-1bc6e581238c.jpg)

**Comment by siddharthkabra** [comment]
![joomla banner pooja](https://cloud.githubusercontent.com/assets/25842720/24658469/67cabdc4-1967-11e7-9496-f87984d1afda.jpg)
![joomla_banner_gayatri](https://cloud.githubusercontent.com/assets/25842720/24658472/68e84d34-1967-11e7-8925-b7451ddd6215.jpg)

**Comment by siddharthkabra** [comment]
@parthlawate @Sandra97 OG banner

**Comment by Sandra97** [comment]
Thanks Siddharth! 
But as already mentioned, for consistency reason, I would prefer the Open Graph image to look like the Twitter Card.
See #34

**Comment by siddharthkabra** [comment]
@Sandra97 ok. May be my team didn't get that right. Will check it out and update 👍

**Comment by Sandra97** [comment]
Thanks Siddharth!

**Comment by siddharthkabra** [comment]
![1200 x 630px](https://cloud.githubusercontent.com/assets/25842720/24828235/8f58955c-1c76-11e7-975f-d3758056b475.jpg)

**Comment by siddharthkabra** [comment]
@Sandra97

**Comment by Sandra97** [comment]
Thanks @siddharthkabra 
Looks fine to me.
I'll test it to be sure of the display.
Then, don't forget to add the psd file in the drive

**Comment by siddharthkabra** [comment]
@Sandra97 heres the link to the file: https://drive.google.com/open?id=0BwjFP5aCU4hPNjQxdnY2T2lLSnc

**Comment by Sandra97** [comment]
Thank you!

**Comment by Sandra97** [comment]
Tests successful.
Closing this issue.
