### ISSUE TITLE
[other] Twitter-News less redundance

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-marketing#54]
Example of redundance Information:
![1](https://cloud.githubusercontent.com/assets/8235763/24296057/c4431042-109d-11e7-9405-50fc79176c96.JPG)

- There are 4 Places having similar Information (2x "new Router", 1x "New Router", 1x "Modern Router")
-  There are 4 Places having similar Information (2x "3.7.0", 2x "3.7").

My suggestion is to reduce similar Information in this small Place.

**Comment by cpaschen** [comment]
This was a technical post, not marketing.

**Comment by franz-wohlkoenig** [comment]
where to post this Issue please? https://github.com/joomla/developer.joomla.org?

**Comment by mbabker** [comment]
What is your issue?  Content, the cards generated via metadata (and now uneditable because of platform caching on Twitter and Facebook)?

**Comment by Sandra97** [comment]
I don't think it's the right place. 
And it's not an issue.
And the post you're talking about is not the Twitter one which was "Information about the status of #Joomla 3.7 and the new router #development #cms #release #websites"
I agree that it's not the best strategy to just copy/paste the title of an article in the post.
But I don't see here any issue with having router and Joomla 3.7 in the picture, title and description tag.

**Comment by Sandra97** [comment]
And the goal of this post was to make people read this article, and believe it worked really well.

**Comment by franz-wohlkoenig** [comment]
My suggestion is to spend a little more information than 4x Times same (if technical possbile): i would change the third time of "Information about new Router an Joomla 3.7" to "We plan a 3.8 release with a new router included". So you got one Time new Information.

**Comment by mbabker** [comment]
The second line is the meta description for the article, not us explicitly putting something in to duplicate info.  It's just how Facebook grabs that data.

**Comment by franz-wohlkoenig** [comment]
thats what i mean by "if technical possible" cause i don't know how this kind of quattro-information comes together.

**Comment by franz-wohlkoenig** [comment]
@Sandra97 you're right, it was on Facebook, not twitter; will change Title.

**Comment by mbabker** [comment]
Just for reference.

The Facebook cards are based on OpenGraph.  The actual share card will pull an image specified by the metadata, the item's title, and the meta description (a couple other things too, not important for discussion).

The Twitter card uses a pretty similar concept.

So while we could tweak that text to have optional extra info, it really wouldn't be that great because that would also affect the search result listing if we used the meta description as a "teaser" spot like your idea about the 3.8 release went.

**Comment by cpaschen** [comment]
Franz  (and all) as noted originally, this is not a 'marketing' issue. 
And as Michael has pointed out, there is no marketing benefit to changing this.
Thanks for your interest in improving the efforts of our social sharing.
This issue should now be considered closed.

**Comment by franz-wohlkoenig** [comment]
thanks @mbabker for Information.
