### ISSUE TITLE
[imagery] New structure

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-marketing#55]
Hello,
I don't remember if there's already a request for that, but i can recall that it has been discussed several times.
It'd be nice to have an image of the structure with names/teams

![](https://community.joomla.org/images/blogs/leadership-blog/joomla_leadership_structure-800.png)

**Comment by Sandra97** [comment]
Do you know where is the source file?

**Comment by jeckodevelopment** [comment]
ehm no  :P

**Comment by mikeveeckmans** [comment]
It was made by Chiara, please contact her.

**Comment by Sandra97** [comment]
Thanks Mike!

**Comment by Sandra97** [comment]
I found the source file: https://drive.google.com/drive/u/0/folders/0B-WMsfRg_wivfm9sZXJQZ3JsVy1oVXpQQkx2ZXdXdGZ4aUl2c2gyc29VNXBXSjBZZjJWbFE

@AlisonAMG Could we look at that together to edit it?

**Comment by AlisonAMG** [comment]
Sure thing Sandra

**Comment by Sandra97** [comment]
I'm working on it, but it will be a .psd as I'm really too bad with .ai

**Comment by Sandra97** [comment]
@jeckodevelopment Could you tell me if it's ok:

![structure-july2017](https://user-images.githubusercontent.com/4682328/27769487-55e75a6e-5ef8-11e7-8a2e-1b84e2b6d194.jpg)

**Comment by yvesh** [comment]
Great work @Sandra97!! +1

**Comment by Sandra97** [comment]
I won't do that twice 😝

**Comment by JoeJoomla** [comment]
Wow, what a great job Sandra.

Joe

**Comment by Sandra97** [comment]
As the tasks is done and nobody asked for any changes, I consider this task as achieved.

Source file is here: https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8U0VMemNOTkZ0VUk
If anyone needs an access, just ask me and if I'm in a good mood, I'll maybe accept to grant access ;) 

I'm closing this issue.

**Comment by jeckodevelopment** [comment]
Thank you @Sandra97 and excuse me for the huge delay :)
