### ISSUE TITLE
[IDEA] 

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-marketing#56]
Hi all,

I posted this post on the Facebook nospam group
https://www.facebook.com/groups/joomlanospam/permalink/10154221470800997/

Since then I had 3 volunteers sign up.  I think we as a community could take this idea a little further.  Firstly, by all sharing our own positive experiences of being a Joomler, and secondly by providing people with an easy template to share.  We want it to be personal to the person sharing, but if it was pushed from central, had a central point of contact, with correct onboarding that would be really useful.

As I already piloted my idea and it got 3 new volunteers I guess it works.  I mainly got this idea because I am part of business networking group BNI and they are masters at pushing their own product.  I think we could do better at it, but it needs to be a cultural development from the centre.

I'm in Glip if you need more, or more responsive via Skype square-balloon.

**Comment by parthlawate** [comment]
I'm part of BNI back here in Pune, India as well.. This can definitely work and help get the work out. I think i'd replied to this on one of the open chats in Glip .. Will post it again here. Having a sharing template of how you volunteered is a fantastic idea - that happening across all channels and inviting people to go via a central onboarding process. 

As discussed by me with a lot of the leadership, we need a full time Joomla 'HR' department who can ensure we get and retain people from various fields. This is right up that lane!

**Comment by uglyeoin** [comment]
There is a "recruitment" group in Glip, maybe that should become the HR group.  I definitely think this is a great idea.  So many newcomers don't know where to start, and since putting out this Facebook post, I realised, I also don't know where to start.

**Comment by yvesh** [comment]
So we now have an official joomla recruitment team, if anyone is interested to join just ping in the public glip group or get in contact with us over the volunteers portal!

https://twitter.com/joomla/status/863011288657559553

**Comment by ufuk-avcu** [comment]
Yes. I think the recruitment team is the right place. If you need any assistance to get in this group you can ask me or @yvesh .
