### ISSUE TITLE
[IDEA] Press / Media Portal

### ISSUE THREAD

**Issue by Joomill** [joomla/joomla-marketing#57]
Hi,

At this moment I miss a overview of the material that is available. A "portal" would be verry handy when you want to give to write a blog post about a new feature or give a presentation on events etc.
Now you need to look at the marketing on github, links to protected google docs ... forget it ... and then you just go on google image search, does not look great if you need to increase the size of a small image ..
I cannot find it. And it must be available somewhere you might think.

For a customer I have access to the portal of Lego and it works soooo easy.
Everything is available, by category, in PSD (good resolution), fonts included, in all languages, etc.
![unnamed](https://cloud.githubusercontent.com/assets/1471185/24667086/6d82092a-1962-11e7-870d-194365ade1ac.png)

I don't think it's much work. Just a Joomla install, download manager (like docman or something) and some people who have the right to upload. It can be used for texts, (social media) images and a powerpoint-template for example.

When you need any help, i'm ready to assist.

**Comment by Sandra97** [comment]
I like your idea.
Note that we ajready have several resources publicly available, even .ai and .psd files (logos, fonts....)
You can give a look there: https://docs.joomla.org/Category:Joomla!_Resources

**Comment by Joomill** [comment]
Thanks for the link Sandra97,
I should never found it there, it looks like a link for the Joomla Resources Directory (JRD) :)

But it's a good start. Maybe when you can add resources for other Joomla sites (JED, certification, etc.) you can do the same on that pages.

**Comment by ufuk-avcu** [comment]
Merged here: https://github.com/joomla/joomla-marketing/issues/111
