### ISSUE TITLE
New Slogan for Joomla! (Call for ideas)

### ISSUE THREAD

**Issue by yvesh** [joomla/joomla-marketing#58]
We don't really have an inspiring and outstanding slogan, something that connects directly to us and makes a good sub-line. (Except JBeer) 

Some slogans used before (Thanks @Sandra97 for doing the research):

The Free Software Powering Millions of Websites
The web made stronger by Joomla!
Connecting billions
Inspired by Millions
Designed by you

Ping @tonypartridge

**Comment by MATsxm** [comment]
I'm just passing through...

**Comment by Hackwar** [comment]
Power through Simplicity.

**Comment by ufuk-avcu** [comment]
Power in flexibility
Be unique, use Joomla
Be unique
Time to unique
The web ecosystem
Rock your next project
Build your web
Unleash your creativity, be Joomla
Defining the Web

**Comment by franz-wohlkoenig** [comment]
> Independence in flexibility

**Comment by aDaneInSpain** [comment]
"Empowering content creation"

Also there are a lot of ideas/discussion in the comment section of [my article in the Magazine](https://magazine.joomla.org/issues/item/3229-a-tag-line-that-sticks).

**Comment by ruchikanagarkar** [comment]
Joomla!
 - one solution for easy & secure website
 - imagine and make with Joomla!
 - download, install and launch
 - take your website to next level 
 - The Power of efforts
 - website building made easy

**Comment by aDaneInSpain** [comment]
For me a tag line should be able to stand alone and give people a sense of what the product is. 

So "Power in flexibility" or "The Power of efforts" or "Power through Simplicity" as has been suggested is way to vague. You could be talking about a car or any other product really. 

The tag line should describe the product (and preferably some USP's).

**Comment by JoeJoomla** [comment]
“Joomla! - Open Source website Content Management System software at it’s best”

Best regards,

Joe Sonne

**Comment by tonypartridge** [comment]
@yvesh my apologies in the delayed response. 

I like @JoeJoomla 's :-)

“Joomla! - Open Source website Content Management System software at it’s best”

Could be refined as:

“Joomla! - Open Source CMS software at it’s best”

**Comment by MATsxm** [comment]
“Joomla! - A software to build and manage your website”

**Comment by SniperSister** [comment]
"Way better than WordPress" ;)
"You platform for awesome websites"

**Comment by degobbis** [comment]
Joomla! - The better way for building wesites

**Comment by brianteeman** [comment]
whatever it is - the language should be simple and not complex. not everyone is a native english speaker so complex language such as Independence in flexibility is way too complex language


PS 
Power in Simplicity was the Mambo catchphrase so it was suggested in irony (I assume)

**Comment by MATsxm** [comment]
+1 with @brianteeman and please be Open and don't talk to a Community who already knows what Joomla! (or a CMS or Open Source) is.

**Comment by ufuk-avcu** [comment]
Maybe we can collect first and then evaluate. Should be better for the creativity and uniqueness.

**Comment by ot2sen** [comment]
Efficient, Reliable and Secure software for your website

**Comment by m-b-o** [comment]
Joomla! - The platform for great websites

**Comment by Didldu-Florian** [comment]
A few slogans based on your needs, becaue you just need it :) you know it!
- Joomla! - _The Open Source CMS which meets to your needs_
- Joomla! - _Your source, your CMS, your needs_
- Joomla! - _Because you need it_

**Comment by JoeJoomla** [comment]
Another entry building on @tonypartridge 's refinement of my original entry:

Joomla! _The worlds best Open Source CMS_

**Comment by tonypartridge** [comment]
That's the one for me!

**Comment by aDaneInSpain** [comment]
That should be... 

> Joomla! The **world's** best Open Source CMS

And that is a claim that we can not back up. Every person reading it will know it is just marketing fluff. So it becomes meaningless. Also it does not say anything about **why** it is the best, which would be nice.

**Comment by mikeveeckmans** [comment]
Joomla! Your multilingual, multi-functional web building platform (or tool)

**Comment by Sandra97** [comment]
What is Joomla made for? Building websites.
A slogan without mentioning 'websites' does not make sense to me.
Using 'CMS' and 'Open Source' means everybody know these terms, I have big doubts about that.

**Comment by mikeveeckmans** [comment]
Joomla! Your multilingual, multi-functional website platform (or tool)

**Comment by Sandra97** [comment]
Honestly, if we want a new slogan and a good one, I think 1st that only an native speaker can help with that and a professional. Not us.

**Comment by asysta** [comment]
i think it is a good decision to collect ideas for the slogan from the community.
a professional doesnt do anything else in the first step

**Comment by aDaneInSpain** [comment]
Some of us are not native speakers but tend to have better command of the language than some native speakers. Also... some of us **are** professional marketeers and copy writers. ;-)

I think we can come up with something good as a team. But yeah, some of the suggestions here are clearly not made by people with strong command of English and can easily be discarded (in their current form) but the message behind might be an unpolished gem.

**Comment by gorgonz** [comment]
You may anytime correct my English mode of expression ;-), this is the idea:
Joomla - start simple - and rise with growing requirements

**Comment by m-b-o** [comment]
I have another one:
Joomla! - made for professional websites

**Comment by franz-wohlkoenig** [comment]
Get professional, use Joomla!

**Comment by dgt41** [comment]
> The tag line should describe the product (and preferably some USP's).

Totally disagree here, NIKE: Just do it, APPLE it just works. Those could apply anywhere as well. The slogan should be simple, 3 words one verb. 

My suggestion was `empowering the creators`

You don't have to relate the slogan to the product, or you 're getting a boring unattractive slogan

My 2c, anyways

**Comment by Joomv** [comment]
I completely agree with Dimitris here.
I think we're mixing up our Slogan with a mission statement.
Slogan should be short and to the point.
The mission statement is where the longer stuff goes.

**Comment by parthlawate** [comment]
There has been a JCM article on this subject already and now there is a github thread.. I think we need a better media to capture information as in both this cases it would be very hard (manual) to collate all the ideas and then discuss them.. Thoughts ?

**Comment by franz-wohlkoenig** [comment]
@aDaneInSpain wrote some from Community "are professional marketeers and copy writers". Maybe they can input Proposals.

**Comment by JoeJoomla** [comment]
World’s best CMS

**Comment by parthlawate** [comment]
Joomla is what you make it ! 
Joomla. dream BIG, build right !

**Comment by klas** [comment]
Search for slogan is fruitless and arbitrary without a strategic foundation to judge the ideas. For start I would suggest working on continuation of the Parth's blogpost : we first need to define main target group(s), positioning, communication goals and objectives. Or in other words - we first need to define communications strategy before any work on tactics like this makes sense.

**Comment by cpaschen** [comment]
Just to clarify (because this has now come up here and a couple other places), this is not an 'official' Marketing Team project (at this point). That means it is not part of our 'strategic plan' for marketing. Mainly, as Klas pointed out, we need to get some 'foundational' stuff worked out first (which is in the strategic plan and already in process). However, this isn't a bad excercise for those interested to think about and contribute - so that when we are ready to 'officially' tackle this it would be great to have all these ideas and already have a jump-start (or possibly even have the perfect one somewhere here already).

BTW ... just to clarify ... we do already have a 'slogan' (or more appropriately, a 'tag line' - "... because open source matters" (however, I'm guessing we probably all agree that this isn't a very 'compelling' one'. However, at the point this actually becomes 'official' we'll probably take a look at that as well.

So please do continue brainstorming any thoughts you have.

**Comment by jayblaq** [comment]
Joomla! A CMS built with love by Volunteers!

**Comment by Joomv** [comment]
Joomla! The Flexible Platform Empowering Website Creators 
This was decided on by OSM at meeting before JAB.
Closing.
