### ISSUE TITLE
[RFC] Make some resources publicly available.

### ISSUE THREAD

**Issue by Sandra97** [joomla/joomla-marketing#59]
Digging into the numerous Google folders, I found this doc:
https://drive.google.com/open?id=0B0yY6xU4qDVUSjBIbzFJbl9jODA
[joomla_dev_flyer.pdf](https://github.com/joomla/joomla-marketing/files/945208/joomla_dev_flyer.pdf)

Except the fact that, once again, the source file is missing, I think it would be a good idea to make that kind of document publicly available to anyone, as well as centralizing them so that they can be easy to find. 

Thoughts?

**Comment by Sandra97** [comment]
Same idea for this document:
https://drive.google.com/drive/folders/0B_YDoF6orMdAemRwRVNoX0hzMGc?usp=sharing
[DiscoveringJoomla.pdf](https://github.com/joomla/joomla-marketing/files/945221/DiscoveringJoomla.pdf)


For this one, seems we have the source files, which is a good thing as it would need some updates.

**Comment by Sandra97** [comment]
Another one... 
The idea of a document/presentation on Joomla main core features is IMO a good idea, but it needs to be redone.

https://drive.google.com/open?id=0B5urv6tZN8XEOVA3QUMtNTdFRjg
[The new Joomla Core Features.pptx](https://github.com/joomla/joomla-marketing/files/945223/The.new.Joomla.Core.Features.pptx)

**Comment by AlisonAMG** [comment]
Those would be great for JUGS to use.

**Comment by Sandra97** [comment]
Yes!

**Comment by AlisonAMG** [comment]
Just thinking about those files and there was some great assets used in them but it's been my experience that trying to extract graphics from anything MSoft destroys them. Do we have any idea where these basic design assets are? Do we own them? Were they another design resource that vapourized?

**Comment by Sandra97** [comment]
Except the Core Features ones, it seems they have been done by Chiara and for some we have the vector files. But I don't know more than that.

**Comment by AlisonAMG** [comment]
Where are the ones we have living?

**Comment by AlisonAMG** [comment]
Also we will want to be sure that whatever design arrangement J had with her is honoured, ie that assets designed by her for us are for use by J only and not released to the public domain/all J users.

**Comment by Sandra97** [comment]
Agree with you. Let's wait for @parthlawate and @cpaschen comments to see if they can help with that and what they think

**Comment by Sandra97** [comment]
Chiara was more than just a contributor, she did many designs and really good ones.
We already have many marketing materials on Jdocs https://docs.joomla.org/Category:Marketing_materials so yes, we can put more resources on JDocs.

**Comment by parthlawate** [comment]
Yup Chiara was the design lead for the project. Its a good idea to collate all marketing collateral together along with Source files. I think final links should be from jDocs. Where should we host all the src files ? Those we might want to keep in gdrive and link from jDocs

**Comment by Sandra97** [comment]
As usual, nobody is giving a flying f**** so I've started a folder and will do what I can when I can. 
At least, we have something... https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8UGVkZ0RNbXlKQ28

I'm closing this issue or it will stay open for centuries.

**Comment by tonypartridge** [comment]
@joomv has hacked tont's github just to say we love you have some gin
