### ISSUE TITLE
[communication] What about a common template for Newsletters?

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-marketing#6]
Many teams of the Joomla! project use newsletters to inform people and subscribers about news and progresses.
It seems that AcyMailing is one of the most used components to send newsletters.
What about a common template?

In this way all the teams could use the same look & feel for communications, news and updates.

**Comment by mikeveeckmans** [comment]
@jeckodevelopment thank you for the suggestion, this is an ongoing project. 
Some of the ideas you can already find here https://drive.google.com/folderview?id=0B4GyNQAWmZQ9Q1FsZlhJVHVGQjA&usp=sharing 
It's not only newsletters but also press releases etc... 

However we still need someone to make it happen, interested?

**Comment by jeckodevelopment** [comment]
Are you going to share AI files to easily work on teaser images for newsletters, blog posts and press releases?
Let me know how can I help

**Comment by Sandra97** [comment]
@jeckodevelopment I'm finishing the 2017 templates for our blogposts and social media (.psd files). Once done, I will make the folder available for all the teams or webmaster who may need them. 
If you need other sizes, just tell me. I'm not the best at Photoshop but I can manage it ;) 

For the newsletter template, Richard from the Certification Marketing Team showed me their newsletter template and we think we can use it as a base for the common template for all our newsletters. 

Also, I really think we should start thinking of a way to have a common place for all newsletters, instead of each team having its own one separately. 
And would be nice if everybody can use AcyMailing for that. It's a Joomla! extension, so it's also a way to promote Joomla! by showing people that you can do really good newsletter with J! ;)

Any toughts?

**Comment by jeckodevelopment** [comment]
+100 for the common template.

Not sure with the common place, just because each team has its lists and it should be easy for each one to send newsletters as needed, without asking other teams.

**Comment by Sandra97** [comment]
Each one has to be able to send its own newsletters when they want of course, as well as having automated newsletters, for example for new releases. But for sure, centralising lists is not easy at all.
In my dream, having everything centralised could mean a centralised place for subscription so that users can subscribe to the newsletters they want from one place, without having to visit each site to subscribe to each newsletter separately.

**Comment by jeckodevelopment** [comment]
I agree with your view, you know.
BTW, for example, in Certification we have users subscribed automatically to a specific list when they are registered to the website. So, maybe it couldn't work

**Comment by Sandra97** [comment]
Yes, it can prevent to do that.
I think we should organize a meeting with all people who are currently managing newsletters and the ones who would like to have one. If we work all together we can at least have some consistency (using all the same template) and find ideas to help users to find and susbscribe easily to newsletters.

**Comment by cpaschen** [comment]
It should be easy for users to sign-up for multiple email newsletters. As long as AcyMailing is installed on a main site (joomla.org etc.) then it can be set-up to automatically send out 'smart' newsletters. Teams can just add content items that are automatically then sent out to users who subscribe to their team news. It would also allow us to just send out one newsletter to each person with a summary of all updates (IF a person wanted that). And all the teams would need to do is create Joomla content items.
Then nobody would have to mess with any design stuff (other than the content items) AND all the newsletter content would be archived on the main site AND would improve rankings of Joomla.org and ease of users finding all J!team content.

**Comment by jeckodevelopment** [comment]
As said, please consider specific needs, like automatical subscription when joining a particular user group.

**Comment by Joomv** [comment]
We now have the following set up for the project:-
1. Elastic Email
2. ACY Mailing.

This is currently being used by Certification, CJO and UX.

There is a template available with graphics and a simpler template without.

We need to stop using mailchimp and other services and consolidate into ACY/Elastic.

The exception is the JED, they are using ACY and SendGrid due to to some techinical requirements.

Any other domains/teams needing access to ElasticEmail are welcome to contact me for setup.

Rowan

**Comment by Sandra97** [comment]
Thank you Rowan! I'll contact you as I would like to have an automatic newsletter for jorg and maybe some others too.

**Comment by Sandra97** [comment]
joomla.org newsletter is ready!
https://www.joomla.org/newsletter.html

**Comment by parthlawate** [comment]
Looking great @Sandra97 ! 
A few text changes i'd like to suggest.. Where you have "Receive Joomla! Announcements and latest News by subscribing to the joomla.org newsletter!" 
Can we say 
"The official Joomla! Newsletter is the best way to stay updated on the latest project news and important announcements. Subscribe today !"

**Comment by Sandra97** [comment]
Edited!

**Comment by Sandra97** [comment]
Developer Newsletter will be ready really soon too. Using quite the same template to be consistent.

![dev](https://user-images.githubusercontent.com/4682328/27006232-cec5117c-4dfc-11e7-9ea4-6719596f620a.png)

**Comment by parthlawate** [comment]
Cool ! Ideally we should have all the Subscriptions in one place so users Know what to choose 

1. Official Joomla! News & Announcements
2. Developer updates 
3. Events
4. User Groups
5. Extension Directory
6. Certification
7.

**Comment by Sandra97** [comment]
That's the idea. 
Let us first set up everything and then we'll see that.

And in the near future, it could be nice if the marketing team can help creating a regular newsletter to promote Joomla in general.

**Comment by Sandra97** [comment]
Developer's Newsletter is ready!
https://developer.joomla.org/newsletter.html

**Comment by franz-wohlkoenig** [comment]
Thanks, found one issue:
![1](https://user-images.githubusercontent.com/8235763/27010288-0beb1db8-4ea1-11e7-81cb-9136acfb1920.jpg)

**Comment by Sandra97** [comment]
That's what happens when I start working at 5am ;)
Thanks @franz-wohlkoenig, it's corrected

**Comment by Sandra97** [comment]
@helvecio @JacquesR, would be nice if you can use for the JCM newsletter the same system as us (AcyMailing) and use the same basis for your newsletter template.

**Comment by parthlawate** [comment]
@sandra97 yes marketing definitely will ! Before we do that we need to promote the newsletters itself to get enough subscribers on each.. getting them in one place will definitely help.. we will cross promote the newsletters between all the teams to ensure all people know which ones are available.  One thing to confirm - all these are on CJO now ?

**Comment by Sandra97** [comment]
It's of course already my plan to promote these 2 new newsletters on our social media channels.
jorg, dev and jug newsletters are hosted in CJO.

**Comment by parthlawate** [comment]
What i'd like to get to is a common sigh up form like this one http://drupal.us2.list-manage1.com/subscribe?u=618af7a460cf93cf211231139&id=6934bc4d06 

We don'
t need to have it as extensive as in our case its more for newsletters.. Not a single sign on

**Comment by Sandra97** [comment]
We will make it happen. 
Better to move little step by little step. 
I've been waiting for 2 years now to have a newsletter. Now we have something and can move forward.

**Comment by AlisonAMG** [comment]
That magic is MailChimp. I know that sort well.

**Comment by Sandra97** [comment]
Mailchimp? No way! ;)

**Comment by AlisonAMG** [comment]
That is what that Drupal form is. 

Side effect of JAB - reading your comments and hearing your voice. lol

**Comment by parthlawate** [comment]
Yeah looks like it is ;) !  Too bad Drupal is using an external provider.. But ACY does allow having a common subscription form for multiple lists as well.. So we can go to that once we get all the newsletters in one place.. I think we should do that before we promote it.. As that way the promotion will get more value..

**Comment by Sandra97** [comment]
I will start promoting jorg and dev newsletter next week. It's not perfect of course, but it's better than nothing. 
I've been waiting the previous marketing team to take care of that during 2 years, and each time it was "we're working on it", you can imagine at one time I was fed up of waiting and so Rowan and I took care of it.

**Comment by AlisonAMG** [comment]
Even with Drupal using MailChimp that is one hell of a complex setup and not something done quickly or without a hell of a pile of planning and mapping.

**Comment by Joomv** [comment]
Closing this because its now up and running
