### ISSUE TITLE
[interviews] Interview the leadership

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#61]
The plan is to interview the Leadership and publish it on the https://magazine.joomla.org/ . If is going well, we can open this process to more people or maybe to the entire community.

We need 1 or 2 volunteers, who is responsible for this. The work to be done is following:

- [x] Gather generic questions
- [x] Setup a google form or whatever
- [ ] Contact leadership
- [ ] Create a new category called "Interviews" on https://magazine.joomla.org/
- [ ] Correct the interviews if they contains mistakes
- [ ] Publish the interviews on weekly basis on https://magazine.joomla.org/
- [ ] Promote the published Interviews on https://docs.joomla.org/Social_Media_Working_Group
- [ ] Task done. Congratulation!

**Comment by Sandra97** [comment]
Have you seen with the JCM for publishing on a weekly basis? Usually, it's only once a month and they don't usually accept to publish at another time

**Comment by parthlawate** [comment]
Nope its only monthly .. We can have 1-2 interviews per month in each issue

**Comment by Joomv** [comment]
@parthlawate  @ufuk-avcu  where are we at with this?

**Comment by parthlawate** [comment]
No interview after the initial one with George which was published in this JCM as well. Next one We'll plan out when we meet later this week

**Comment by ufuk-avcu** [comment]
@parthlawate this is an another project. We setup a google form. I think you mean the video interview... @yvesh any news about the rest?

**Comment by yvesh** [comment]
@ufuk-avcu 3 responses so far. Robert J. and @jeckodevelopment still missing ;)

You have full edit and review access to the form. For the other 5 members we should set up some different questions, like we talked about. But you can start by publishing the 3 ones which are ready.

**Comment by jeckodevelopment** [comment]
I should have answered to this @yvesh .
If i didn't could you please send me again the link?

**Comment by yvesh** [comment]
@jeckodevelopment https://docs.google.com/forms/d/e/1FAIpQLSe4shucOoJd-y7MGlDQNBBkQo-yePuAI7oYNhWSBVWC7Ab8Zw/viewform?usp=sf_link

**Comment by jeckodevelopment** [comment]
I answered this some weeks ago... but i can do it again

**Comment by jeckodevelopment** [comment]
Done

**Comment by Sandra97** [comment]
@ufuk-avcu @parthlawate Any news about these interviews?

**Comment by ufuk-avcu** [comment]
@Sandra97 no sorrry. We have not every respone yet. I know that Yves ask several times for this...

**Comment by jeckodevelopment** [comment]
@ufuk-avcu Who is missing?

**Comment by mikeveeckmans** [comment]
@yvesh : any update on the input of the interviews ?

**Comment by yvesh** [comment]
@mikeveeckmans Added you as form admin, so you can check yourself :-)

**Comment by mikeveeckmans** [comment]
Thanks!!


On 6 Nov 2017, at 12:59, Yves Hoppe <notifications@github.com<mailto:notifications@github.com>> wrote:


@mikeveeckmans<https://github.com/mikeveeckmans> Added you as form admin, so you can check yourself :-)
