### ISSUE TITLE
[design] Create imagery for the thank you campaign

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#63]
**For whom:** 
Official Partners, Official Sponsors
https://www.joomla.org/sponsor.html
https://www.joomla.org/current-sponsors.html
https://www.joomla.org/about-joomla/partners.html

**Why?**
Say thank you to our sponsors and partners the are helping with our project.

**Is for:**
- Social Media

**Tasks:**
- Use official social imagery Template - (link per request)
- Create imagery using at least the logo of the company
- Create also a global imagery, one for sponsors  and one for partners
- Provide as PSD
- Ask for review
- For any question contact @Sandra97

**Comment by shirdesign** [comment]
it this a design for the social media? @Sandra97

**Comment by ufuk-avcu** [comment]
I updated the task. Its mainly for social media i think.

**Comment by Sandra97** [comment]
Yes it is for Social Media.
Note that I won't have a single second this week to work on the pictures and copywriting for this campaign (or on anything by the way). 
Hope that someone from the social media team or marketing team can start wooking on it.

**Comment by shirdesign** [comment]
@ufuk-avcu  @Sandra97 Where can I find the Use official social imagery Template? 
I will do it during next week. 
Also who should I talk to for text and review? as Sandra is not go to be available?

**Comment by Sandra97** [comment]
@shirdesign I just granted you persmissions to the template folder: https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8eC05TE5hTnRkWEU

I don't have time to create the pictures and do the copywriting but don't hesitate to contact me on Glip.

**Comment by shirdesign** [comment]
@Sandra97 great - I will do the pictures during next week and will be in touch on Glip.

**Comment by Sandra97** [comment]
@shirdesign Did you had time to start working on the pics?

**Comment by shirdesign** [comment]
Sorry, Sorry - completely slip my mind... I will work on it tomorrow / Tuesday.

**Comment by Sandra97** [comment]
Thanks Shirat!

**Comment by shirdesign** [comment]
Ok - Started working on the task - 
A few Q so I can run with it: 
1. where can I get good quality logos for the sponsors and partners? 
2. What are community sponsors? I can't see their logos...
3. Where can I get the original Heart image from the sponsor page? I need it good quality and also it has a Hebrew mistake. 
4. I thought for the sponsor text use the text from the page + put the heart + in each post the logo and name of the sponsor :
Thank you to our sponsors
who help Joomla! grow and improve, worldwide.

and for the partners text:
hank you to our partners
who help Joomla! grow and improve, worldwide.

@ufuk-avcu @Sandra97

**Comment by Sandra97** [comment]
1- Not sure we have, do like me, Google them ;)
2- For community sponsors, I'll ask if we should do something or not about them
3- No idea where is the source file. You can find another one here: https://drive.google.com/drive/u/1/folders/0By_CBGYGBbU8R1VuSVNXbEJOODg
If you don't like it, you can search for another one in our 123RF library (just ask me so that I can create your an access) 
4. Ok for me!

**Comment by shirdesign** [comment]
Are we on a deadline? 
I'm starting the weekend early and need to know if to push a few more hours of work - a.k Joomla fun;) or I can continue on Sunday...

**Comment by Sandra97** [comment]
Hi Shirat, 
As far as I know, we don't have a deadline.

**Comment by Sandra97** [comment]
I'll work on this with @AlisonAMG if she is ok. We need to move forward on that. 
Even if there's no real deadline, we can't wait months to start this campaign. 
Can someone provide me more hours in a day? ;)

**Comment by shirdesign** [comment]
@Sandra97 Sorry for not being more available. I could use some more hours a day as well if someone can sell them to me. 
Did @AlisonAMG took the assignment? so I will know if to take it off my to do list?

**Comment by Sandra97** [comment]
@shirdesign I will see to work on a template for this campaign so that we can be consistent and then the 3 of us can produce all the imagery for it.

**Comment by Sandra97** [comment]
@eXsiLe95 will take care of the graphics for this campaign. Thank you Lukas!

**Comment by Sandra97** [comment]
Graphics will be available in this [folder](https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8MDVoVjZwNVBHWFE)

**Comment by Sandra97** [comment]
Alison did all the pics. The Social Media Team will soon start the campaign.
Thank you @AlisonAMG
