### ISSUE TITLE
[calender] Collect all important Dates relevant to the project

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#65]
We would like to create a calendar for the project.  This would include all upcoming internal events like

Joomla Events, Joomla Releases

**Tasks**
- Collect Dates relevant to the project
- and enter them here: https://docs.google.com/spreadsheets/d/16xNRWDYBZxC3bL5LfYLlihEBQr3pH02wM1mon81OtjI/edit#gid=0

**Comment by Sandra97** [comment]
Personally, I honestly don't think we should do posts about international days which are not related to the internet, like Wolrd Cancer Day, Women's Day, Youth Day of all that kind of things.

**Comment by Sandra97** [comment]
And could you please move your sheet to the right folder: 
https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8YVVvTWdOMExHb2M

Thank you!

**Comment by parthlawate** [comment]
I agree.. Its seen as very bad tactics to use un related events and occasions.. We should only stick things that relate to Joomla as a product and project

**Comment by Sandra97** [comment]
I've started to fill the calendar: https://calendar.google.com/calendar/render?mode=day&date=20170624T104055#main_7%7Cday-1+24280+24280+24280

**Comment by brianteeman** [comment]
Hope this helps
https://spreadthejoomlalove.com/history

**Comment by JoeJoomla** [comment]
I really like that page on spreadthelove.com/history btw. Very nicely done.

**Comment by brianteeman** [comment]
Thanks @JoeJoomla its just a blog category with a template override
