### ISSUE TITLE
[video] Joomla Official Video Script

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#68]
Work on and finalise the Script for the Joomla Video. Last version can be found here : https://docs.google.com/document/d/1Xug_fpbtP2JcAytWYVYoAQ_0d2nPLEObL1wrXzMI5lk/edit# 

**Requirements :**
Video Length : 1 Min 
Good to haves : Accessible (with voice over & subtitles)

**Comment by cpaschen** [comment]
If you want US-English voice over for the video let me know (I have studio and do voice-overs and radio work).

**Comment by cpaschen** [comment]
I can also help write script if needed.

**Comment by Sandra97** [comment]
Duke offered me his help for the video. I said a big YES immediately of course!

**Comment by parthlawate** [comment]
Thats great @Sandra97 @cpaschen can you collaborate with Duke on this ? Would be great if both of you can get a team together to make this happen. Chris you are already on the Video group. @Sandra97 do you know Duke's Glip Id ?

**Comment by Sandra97** [comment]
@cpaschen Duke is on Glip but he usually doesn't use Glip.

**Comment by cpaschen** [comment]
I don't have the bandwidth to be building a team right now - but I do have time to do 'assigned tasks' related to this sort of thing (i.e. write copy, record copy, etc.)
Is Duke on Github? If so, can you 'assign' this to him (and me) and we could connect and collaborate here (I'm not active much in Glip right now either).

**Comment by cpaschen** [comment]
Also, can we have some 'direction' for this video? What is the main 'goal' or focus? Do we have a 'target audience'? Do we have a deadline (JWC etc.)?

**Comment by Sandra97** [comment]
I don't know if Duke is on GitHub or not. But I gave him the link of this issue.
The goal of this video is to give an overview of Joomla. It's a global promotion video. 
Deadline was years ago ;)

**Comment by cpaschen** [comment]
Duke - do you have some ideas on this? 'overview of Joomla' is rather huge/broad.
It would be helpful to have a more specific goal - 'sales', instruction, etc. And are we aimed at users, developers, integrators, etc.
I'll defer to others on these details, but we will need establish that (and who's going to do which aspects of this) to get it rolling.

**Comment by Sandra97** [comment]
This is going nowhere. I'm closing this issue.
I would love to have a 'professional' video to promote Joomla but this is a huge task not achievable for the moment. Let's focus on short videos.
