### ISSUE TITLE
[content update] Update the social media posts to bring it up2date

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#69]
We have a great list of tweets, but they are outdated. If we can update them and add new ones, we can use it for the social media team.

**Tasks:**
- go through the existent ones and update them
- look for outstanding tweets and make them bold
- and add new ones

https://docs.google.com/spreadsheets/d/1KZ2k1IsoTuwMxrRdH9I1zRgiuM9gNZ1YGzgNZXL0yow/edit?usp=sharing

**Comment by Sandra97** [comment]
https://docs.google.com/document/d/14pHmjsEMu-UYbEwJuvH8oVL1A52_9571uaK2at1rIHo/edit
Mike and I started working on this doc last year. 
Any help is more than welcome to continue it. 
If nobody does, well, I'm afraid that as usual I will have to take care of it by myself

**Comment by parthlawate** [comment]
@Sandra97 Sure we'll help :) I think however moving everything into an XLS with tabs might make it easier to manage. Are you ok with Doing that ? I can organise some help to make this happen..

**Comment by Sandra97** [comment]
The format is not important for me, it can be an XLS. 
The folder where to add the file: https://drive.google.com/drive/u/0/folders/0By_CBGYGBbU8ZUMzdGpLdEJtTWM
Thank you!

**Comment by Sandra97** [comment]
I've started to create pictures, posts and issues in the social media repo so that someone can make it happen. 
No need to have several issues open for that. Except if someone wants to help me with copywriting and pictures. OK, I AM DREAMING AGAIN! ;)
So I'm closing this issue.
