### ISSUE TITLE
Take a Group Photo at Make it happen

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#72]

**Comment by ufuk-avcu** [comment]
![20170603_172626](https://cloud.githubusercontent.com/assets/13818234/26784901/34d5a978-4a00-11e7-921d-a838d401cde1.jpg)
![20170603_172619](https://cloud.githubusercontent.com/assets/13818234/26784902/34d6e93c-4a00-11e7-8287-42ead1a5aa18.jpg)
![Uploading 20170603_172607.jpg…]()
