### ISSUE TITLE
Send Post JAB 17 Newsletter for Make it Happen Attendees

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#73]
We need to send a thank you newsletter to all attendees who attended the Make it Happen

https://docs.google.com/document/d/1cpujtZ-JhlSITWCBBABBl5QiEJiNd69tYTLjhsprQjw/edit#

**Comment by parthlawate** [comment]
Newsletter template is ready with some content. To be updated post JAB with a link to JAB achievements post

**Comment by Sandra97** [comment]
Any update about that?

**Comment by Sandra97** [comment]
No news after 22 days. It won't happen obviously.
I'm closing this issue.

**Comment by parthlawate** [comment]
There was no list collected at JAB .. I have content ready but no one to send it to.. so I have published article on JCM
