### ISSUE TITLE
Write Blog about Achievements at the JAB 17 Make it happen for marketing 

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#74]

**Comment by ufuk-avcu** [comment]
Images: https://github.com/joomla/joomla-marketing/issues/72

**Comment by Sandra97** [comment]
Any news about that?

**Comment by parthlawate** [comment]
Started here by @ufuk-avcu .. Have modified and added to it.. In the Queue now for JCM July 

https://docs.google.com/document/d/1hosK8-iC3rZGdbsGYO-HssDtxphUICmi2gQ0xP9jC1g/edit#

**Comment by Sandra97** [comment]
Article published in the July issue of JCM.
I'm closing this issue.
