### ISSUE TITLE
[Ready for proposal] Find a print provider

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#76]
We need a fully managed external shop provider for the new shop.joomla.org. They should be capable to manage the logistics and invoicing and all the stuff.

**Comment by Joomv** [comment]
I’ve already spent a considerable amount of time on this, can I consider this as the Request for Proposals that I have been waiting for for over 8 months?

Rowan

**Comment by mikeveeckmans** [comment]
any movement?

**Comment by Sandra97** [comment]
Let's see to make a RFP.
We need to re-open the shop.
@ufuk-avcu If you're ok, could you give the green light for a RFP?

**Comment by yvesh** [comment]
Don't forget to include the stuff we need for VET in the calculation @ufuk-avcu @Sandra97 :-) There is a print team on glip, please keep us involved there.
