### ISSUE TITLE
[jug] Involve and aggregate JUGs

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#77]
We should set a agenda for every six months and send the JUGs newsletter to engage them to test bugs, write blog posts or take pictures and share this stuff on the social media with defined hashtags like:

- jugbug
- jugpicture
- jugcopywriter
- ...

**Comment by Joomv** [comment]
We already have a monthly JUG newsletter that goes out to JUG’s

We welcome any team to submit content/calls for volunteers etc for inclusion in the newsletter.

We have plans to engage JUG’s more and to improve interaction between them.

JUG’s also provide items for the monthly “JUG Round up” Article in the magazine.

Rowan

**Comment by Sandra97** [comment]
Involving JUGs is part of the new marketing strategy. We are already doing this (not enough for sure but we do baby steps in the right direction)
And this task is not enough defined and no guidelines. So I'm closing this issue.
