### ISSUE TITLE
[event] JoomlaDay Poland 2016 - Promotional Materials 

### ISSUE THREAD

**Issue by DanaIdzik** [joomla/joomla-marketing#8]
Hello :)
JDay Poland is opened for every kind of support (promotional materials) :) Our event will take place in 24-25 september, we expect 200 attendes this year, @mikeveeckmans what you can share with us? :)

Regards
Dana

**Comment by mikeveeckmans** [comment]
@DanaIdzik as soon as i have a clear view on the budget i will get back to you. This might be next week. 
Would you also require the booth etc ?

**Comment by DanaIdzik** [comment]
ah yes! it would be super! Thank you!

**Comment by DanaIdzik** [comment]
hey hey @mikeveeckmans :) remember me? :D

**Comment by mikeveeckmans** [comment]
@DanaIdzik Yes, but i still have no confirmation on the budget... So at this point i can't confirm anything.

**Comment by DanaIdzik** [comment]
hello @mikeveeckmans :) what is your situation? any info about materrials for JDay Poland? Thank you

**Comment by DanaIdzik** [comment]
hey @mikeveeckmans 
It is a time for all promotion of OSM from our part. We started promotion in Social Media, now we will do it in other websites joomla.pl, fundacja.joomla.pl and joomla-day.pl - thats only info :)

And the last thing is: We need (if you want to and can share ofcourse) and advertisement / (or) a gift for participants inside the events bag  (condition: delivery within 16.09.2016 r.). Every sponsor send something like this :)

Can you give the information will OSM share with us by "something" inside this events bag?

Thanks

**Comment by mikeveeckmans** [comment]
Hi @DanaIdzik , i can send you stickers and flyers. What's the current registration number?

**Comment by DanaIdzik** [comment]
right now weve got 109 people registered

**Comment by DanaIdzik** [comment]
@mikeveeckmans right now weve got 109 people registered

**Comment by DanaIdzik** [comment]
@mikeveeckmans I need your help. WE will make big promotion of OSM on Joomla.pl (its gold sponsor).
Do you want to share a special graphic with size: 750 x 450 with osm logo (or what u want) and the special text about this organisation? 
If you have no time we can share the same info like e have now on Joomla-day.pl
Dana

**Comment by mikeveeckmans** [comment]
@DanaIdzik please share same info as on joomla-day.pl 
Shipment sent.
