### ISSUE TITLE
Define benefits of Joomla for Professional Web Agencies

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#80]
https://docs.google.com/spreadsheets/d/1RJOWl0VQvyoMAa1xjcRkUqHpIXVjIl6pfp3zgWhbt50/edit#gid=0

Old Raw Data 
https://docs.google.com/spreadsheets/d/1I3qQuRXDhmXXs6YslALrs0upC1Ab2Jzd0P3vMwOhiWQ/edit#gid=286699914

**Comment by Sandra97** [comment]
We have now the benefits page and the brochure. It's of course not enough, but at least it's something. 
And this task is not well defined, no guidelines are provided so chances are vey low that anyone jumps in.
So I'm closing it.
