### ISSUE TITLE
[STRATEGY] Strategy to define Joomla Campaign to promote Joomla to Web Agencies [4 hours]

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#81]
https://docs.google.com/document/d/1KtgXq_2q9wf9a7UnYl1FnLlB_JP7Ss5aexcofoGcilQ/edit

**Comment by Sandra97** [comment]
We have far too many tasks open for too long that go nowhere for a lack of resources / interest. The new marketing strategy gives guidelines for thsi kind of promotion. Let's do things step by step to be sure we  have achievable goals according to our resources.
