### ISSUE TITLE
Bad Joomla Blogs - Refute them

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#83]
Compile and Refute bad blogs about Joomla

https://docs.google.com/spreadsheets/d/15ZHbAaxLJRgPQsMAZD18u4o4Cr76NKu52-TGyPsp2nM/edit#gid=0

**Comment by netamity** [comment]
Do you mean blogs giving an unfair review or misinformation about Joomla?

**Comment by parthlawate** [comment]
Yes thats the idea..

**Comment by ufuk-avcu** [comment]
Closed. We can reopen this, if we have more volunteers. We should consider to teach the people about this, instead aof doing it byself.
