### ISSUE TITLE
Write to Companies that use Joomla & Get testimonials from them

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#84]
Content for the email 
https://docs.google.com/document/d/1BiNaDxFAD7ncXc8xAr3S3Gmo__0UHzb2wox2tZgJ_Zg/edit

Google form to Submit Testimonial 
https://docs.google.com/a/community.joomla.org/forms/d/e/1FAIpQLScKTIYE3bq6YpIvlJg3kM49rfyioeafZCUMQd2iQ5e5R_nVfQ/viewform

**Comment by Sandra97** [comment]
Any update on that?

**Comment by parthlawate** [comment]
Form is ready. Campaign is being planned. Overall updates on all campaigns started at JAB i would take in July when most will be ready to be launched

**Comment by mikeveeckmans** [comment]
Do you guys need a review on the form and content of the mail ?

**Comment by parthlawate** [comment]
Yes please @mikeveekmans ! Always :) .. it's been privately circulated so far.. but pls do review .. we can add the changes before wide circulation

**Comment by mikeveeckmans** [comment]
@parthlawate can you assign please 
I can't anymore :-P

**Comment by mikeveeckmans** [comment]
On the form,  also ask for some references, contact details, how long they are using joomla, ...

**Comment by parthlawate** [comment]
@mikeveeckmans assign what ? you mean give edit access to form & Doc ?

**Comment by parthlawate** [comment]
When you say references what do you mean exactly ? Sites they have done ?

**Comment by parthlawate** [comment]
Made some changes to the form pls check

**Comment by Sandra97** [comment]
This task went nowhere unfortunately. As for all tasks, this need resources we don't have. So better prioritize our tasks for the moment and focus on J3.9 and J4.
