### ISSUE TITLE
Create an Onboarding checklist for Agencies

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#87]
Here is an example from Loom
![screen shot 2017-06-04 at 7 42 13 pm](https://cloud.githubusercontent.com/assets/673176/26763970/0e289e2c-495e-11e7-9215-2326d7f098a5.png)

Here are some items that we could put on there 

1. View the Introductory  targeted specifically at agencies
2. Make a Profile on the Joomla Resources Directory
3. Sign up for the Joomla Forums 
4. Sign up for the Joomla Stack Exchange
5. See how Documentation works
6. Get trained
7. Attend a JoomlaDay Event
8. Attend a Developer Conference

**Comment by ufuk-avcu** [comment]
9. Create a Profile on the Joomla Volunteers Portal

**Comment by Radek-Suski** [comment]
sponsor JoomlaDay™

**Comment by projcodeacious** [comment]
I quite like checklist @parthlawate. Most of the time it is associated with rewards(in terms of points or badges) which make users curious to complete them.

**Comment by ankitify** [comment]
I quite like checklist idea @parthlawate. Most of the time it is associated with rewards(in terms of points or badges) which make users curious to complete them.

**Comment by Sandra97** [comment]
We don't currently have the resources to achieve this and need to prioritize our tasks.
