### ISSUE TITLE
Create a Content Article based on George's interview at JAB (basically a transcript) and Publish it in the July Magazine Issue

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#89]
Source video can be found here https://www.youtube.com/watch?v=JxVagjKq16g&t=4s

**Comment by parthlawate** [comment]
Started here .. https://docs.google.com/document/d/1tl-Sv2hR0rmL5fOxAi_bWOvdCWINds0_UKbu_qb2OAA/edit

**Comment by Sandra97** [comment]
Article published. I'm closing this issue.
