### ISSUE TITLE
Start an Agency Newsletter & Put a Subscribe form

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#91]

**Comment by Sandra97** [comment]
Anyone has prepared some content for that?

**Comment by parthlawate** [comment]
@Sandra97 This is just the 'List' So there will be an agency specific list. What content will go out will vary. This is considered as part of the overall Agencies campaign.. However we do need a list on Joomla.org Newsletter where Agencies can subscribe to it. If you want an introduction to the list it can be as below. 

The Agency List
If you are an agency using Joomla to delivery powerful websites and applications to your customers, sign up to our Agency list to receive updates as well as tips and tricks to make the best of Joomla as a platform to build professional websites and applications. Sign up today !

**Comment by Sandra97** [comment]
As web agencies are our main target, I'm not sure we need a separate subscription form for that. 
And I'm not sure neither we should create I don't know how many newsletters on jorg, it will just be a mess and users will be lost if we have too many newsletters.
jorg newsletter is for the moment only a newsletter with the latest announcement. We will of course keep it to inform our users of the latest stable version.
But we need of course a jorg 'marketing' newsletter to send once a month for example that should have tips and tricks, general information about our properties and things like that.

**Comment by Joomv** [comment]
I think we need to build the strong general lists first.   Once we have those we can look to starting to survey and niche people.  Whilst we're still quite short staffed with a massive backlog, think it best to do the 2 lists we have right then in the future when we've got a good following we can look to break them down.

**Comment by parthlawate** [comment]
The way I see it is that all 'Joomla Customers' should have just one place to subscribe to all available lists. That way its easier to drive more users to sign up overall. 

I would not do a 'Joomla Marketing' newsletter.. Atleast not call it that .. As 'End users' sign up to a Newsletter.. People sign up for Targeted News, Updates, Tips, Tricks that will help them.. Each list should have a target audience and Intent..  Marketing will use the appropriate list depending on what content we have to share.. 

Does that make sense ?

**Comment by Sandra97** [comment]
Let's do step by step. 
If the plan is to create many lists and have many newslteers, it is not a good idea as it's not realistic, I prefer small but achievable plans than big plans which won't happen (,no need to mention that this 'global' newsletter should have been ready 2 years ago...) . 
So let's first start with one 'global' newsletter per month or every 2 months with content provided by the makreting team. And if we can have this one, after one year and if all goes well, we can rediscuss and do more.

**Comment by Joomv** [comment]
I think we both completely understand the "vision" here @parthlawate  but we also know the ecosystem and the staffing levels, as Sandra said.  We've only just launched the main newsletter.  Lets make that one fly, then when it is established, we can look at diversifying them.  Better to have one well maintained strong list than several diluted ones that drop through the cracks.

**Comment by parthlawate** [comment]
Agreed :) I don't think we want many newsletters that are not manned ! Once all are consolidated in once place (Without creating any new ones) we will achieve what i wanted to start with - A common place to promote subscribing to all kind of Joomla updates.. Once we are there. We can add more if needed like you say !

**Comment by parthlawate** [comment]
I'm keeping this one open for now as the overall agency campaign will see a lot of content getting created that could be good stuff for an Agency adopting Joomla. If we see no movement on this one month from now, lets close it

**Comment by agerix** [comment]
As we are doing for our newsletter, you can use custom fields from Acymailing and add them in the subscription form. After that you can use them to add people in list with mass action. For example if you have a radio button Agency Yes/no...

**Comment by Sandra97** [comment]
Before creating I don't know how many newsletters, better to improve the current one and focus on it.
Any help welcome! Just contact me.
I'm closing this issue. 
Re-open if needed.
