### ISSUE TITLE
Create Collateral for Agencies to use to Promote to Joomla

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#92]

**Comment by Aidan38** [comment]
Hello,
could you please be more precise about the needs of this project?

Thank you!

**Comment by Aidan38** [comment]
Hello,
could you please be more precise about the needs of this project?

Thank you!

**Comment by parthlawate** [comment]
Hello Aidan, 

Sure ! The goal is to create ready to use collateral that allows Agencies to Promote Joomla/Sell it as a solution to their clients. Examples could be as below. 

1. An Introduction to Joomla Presentation (Focussed on Clients) showing what benefits the Agency will be bringing to the client by using it as a base for their project

2. Similar to Above case Print Brochure 

3. Ready emails to send clients with same intent as above. 

4. Video Testimonials

Imagine it to be a 'Sales Kit' for Joomla

**Comment by Sandra97** [comment]
We have a brochure since last year. We still need many more elements to promote Joomla correctly but we curretnly don't have the resources for big plans. So let's do baby step by baby step and be realistic with our resources.
