### ISSUE TITLE
[Copywriting] Write a Good Wikipedia Article for Joomla in English

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-marketing#93]

**Comment by ufuk-avcu** [comment]
https://github.com/joomla/joomla-marketing/issues/94

**Comment by Sandra97** [comment]
I'm closing this issue. A wiki is for users maintained by users. 
Replace the current content of the page, your edits will just be reverted. 
Better to find people to check if there's no commercial links and that information are correct and up to date.
I would be happy to see in the history other names than mine....
