### ISSUE TITLE
Update the Wiki Joomla Page in every language

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#94]
We need people from all over to world to update the Wikipages in the different languages. https://de.wikipedia.org/wiki/Joomla

Promote this task on joomla.org to get more people into this.

**Comment by agerix** [comment]
Good idea ! ;)

**Comment by MATsxm** [comment]
@agerix ?

**Comment by agerix** [comment]
Oui Mat ? :)

**Comment by Sandra97** [comment]
I'm not against seeing other french names than mine for edit of the french page ;) 
![a](https://user-images.githubusercontent.com/4682328/27546758-186b329c-5a6a-11e7-95c5-994645e7a122.png)

**Comment by Sandra97** [comment]
Ideas are a good thing, but I would really prefer seeing things being done.

**Comment by agerix** [comment]
Saying it's a good idea is the first step to participation isn't it ? How many people are on github and receive this message ? May be the second step is here for me

**Comment by Sandra97** [comment]
It wasn't against you Eric, it was a general comment ;)

**Comment by agerix** [comment]
No problem Sandra, we know each other and we also know that the things we read are not the feeling we want to give. I'm agree with you, communities are full of ideas ans poor of contributors, I'm not a fan of Github because I don't use it as a developer but I just discover marketing threads here and it's a surprise to see interesting subject ;)

**Comment by parthlawate** [comment]
So whats the next step

**Comment by Sandra97** [comment]
Whe should put that task under the local community department (wen this department is functional). 
I'll continue to update the French and English versions, but for sure would be better if more people can do it and for more languages

**Comment by Sandra97** [comment]
@ufuk-avcu Any progress about that or should I just close this issue?

**Comment by ufuk-avcu** [comment]
@Sandra97 no it's not done. Parth started a new Group in Glip called "Marketing - Wiki Maintenance Group". But we need to collect much more people. There are only 5 people. We should promote that idea. I try to find a copywriter for that...

**Comment by ufuk-avcu** [comment]
Maybe we should consider to write from time to time a blogpost and promote it and don't try to organize it by ourself.

**Comment by Sandra97** [comment]
I've added 3.7.4 and link to the announcement in the EN and FR page.
If ever some of you speak other languages, please update the page in your language.

**Comment by ufuk-avcu** [comment]
Closed. It should be discussed in the local communities to update the wikipedia pages.
