### ISSUE TITLE
Delete Sub Teams

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#95]
https://volunteers.joomla.org/teams/marketing

- [x] Marketing Data Analysis & Metrics Group
- [x] Marketing Public Relations Management Team
- [x] The Joomla! Shop Management Team

**Comment by Sandra97** [comment]
@ufuk-avcu Sander fixed the issue. You should now be able to remove these teams. 
I can't do it myself, I don't have permissions.

**Comment by ufuk-avcu** [comment]
Thank you. Subteams deleted.
