### ISSUE TITLE
[copywriting] More marketing for the Joomla Administrator Certification

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#97]
We have only 117 Certified Joomla Administrators until 09.06.2017. We should do also some marketing for this...

**Comment by Sandra97** [comment]
You should contact the Certification Marketing Team

**Comment by parthlawate** [comment]
Raised it to Richard and asked him to comment here

**Comment by RichardR2H** [comment]
Thanks for noticing. We have two new volunteers onboard recently and we are now restructuring our work and re-plan tasks. We wrote and posted about the 100th Certified Administrators (CA) and we will focus on this group soon to transform them from Certified Administrators to Certification Ambassadors.

**Comment by ufuk-avcu** [comment]
Then i close this. That's great. You are aware of this...
