### ISSUE TITLE
[organizing] Clean Up the marketing@community.joomla.org Mails

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-marketing#99]

**Comment by Sandra97** [comment]
Answer for messages coming from the jorg contact form not related to press request
[jorg_general_contact_form_answer.docx](https://github.com/joomla/joomla-marketing/files/1077379/jorg_general_contact_form_answer.docx)

Note that this message is available in many languages:
https://crowdin.com/project/joomla-official-websites-templates

**Comment by ufuk-avcu** [comment]
Cleaned up all the Support requests ( 500+ ) and postponed the important ones (~10) to next week.
